### ISSUE TITLE
Support for Shared Web Workers

### ISSUE THREAD

**Issue by awwx** [sockjs/sockjs-client#124]
[Shared Web Workers](http://www.w3.org/TR/workers/) support web sockets and XMLHttpRequest, but they don't have access to a DOM and their global environment doesn't include `window` or `document` .  Thus to support for example the websocket transport, the implementation needs to reference `WebSocket` from the global environment (which can be referenced with `self` if desired), instead of using `window.WebSocket` (as `window` is not defined).

A minimally intrusive change might be to rename `_window` to `_global`, and assign it from either `window` or `self`.  Then the code would just need some additional checks for objects not defined... for example, the jsonp transport would need to report that it isn't enabled when `document` isn't available.

Does that sound like a preferred approach?

**Comment by AkeemMcLennon** [comment]
@awwx Did anything ever become of your SockJS branch that was compatible with Web Workers? :-)

**Comment by brycekahle** [comment]
@AkeemMcLennon You should try the latest beta release. It should be compatible.

**Comment by AkeemMcLennon** [comment]
@brycekahle I just noticed your awesome commit that tested web socket support.  If you're ever in SF, let me buy you a drink :-D
