### ISSUE TITLE
Add sub-protocol support

### ISSUE THREAD

**Issue by rstoyanchev** [sockjs/sockjs-client#130]
As a WebSocket emulation layer, it makes sense to support sub-protocols in SockJS. The sockjs-client could have a "protocols" option added with the value passed to the server either through the W3C WebSocket constructor or by setting the `Sec-WebSocket-Protocol` header.

Servers can then choose to add support by checking the `Sec-WebSocket-Protocol` header.

**Comment by allbutone** [comment]
does sockjs support sub-protocols now ?

**Comment by brycekahle** [comment]
@allbutone This issue is still open, so no.
