### ISSUE TITLE
SockJS client not emitting close event when disconnected ungracefully

### ISSUE THREAD

**Issue by byssi** [sockjs/sockjs-client#176]
SockJS is not emitting the close event when the socket has been closed ungracefully, preventing me from automatically reconnecting. SockJS still thinks it is connected with a readyState of 1, but it does not receive any messages, and nor are any messages it 'sends' received by the server.

Test case

```
var sock;
function connect(){
sock = new SockJS("http://yourserver.com");
sock.onopen = function(){ console.log("open") };
sock.onmessage = function(e){ console.log(e.data) };
sock.onclose = function(){ console.log("close"); connect() };
}
connect();
```
1. Run page
2. Disconnect ungracefully (eg, turn on or turn off VPN)
3. No 'close' event is emitted, readyState is still 1, no messages sent or received.

**Comment by blittle** [comment]
@brycekahle I am currently seeing this problem, this is my example code:

```javascript
 var sock = new SockJS('http://localhost/ws');
 sock.onopen = function() {
     console.log('open');
 };
 sock.onmessage = function(e) {
     console.log('message', e.data);
 };
 sock.onerror = function(e) {
     console.error(e);
 }
 sock.onclose = function() {
     console.log('close');
 };
```

The transport does get to websocket, I can view websocket heartbeat frames in the browser. I then kill the server (ungracefully) and I get no event handlers called.

**Comment by brycekahle** [comment]
@blittle What sockjs server are you using?

**Comment by blittle** [comment]
We aren't using sockjs server, but Vert.x SockJS

`io.vertx.rxjava.ext.web.handler.sockjs.SockJSSocket ` on SockJS 3.0.0

**Comment by blittle** [comment]
Should be this something I should report to the Vert.x project?

**Comment by brycekahle** [comment]
Lets grab some debug information first. If you use the non-minified version, run the following in a browser console `localStorage.debug = '*';` and then refresh you should get some debug output.

**Comment by blittle** [comment]
Got it

**Comment by blittle** [comment]
So this is the output before and after I kill the server:

```
sockjs-client:main _transportMessage +0ms h
browser.js:38 sockjs-client:main heartbeat +0ms websocket
browser.js:38 sockjs-client:websocket message event +2s h
browser.js:38 sockjs-client:main _transportMessage +1ms h
browser.js:38 sockjs-client:main heartbeat +0ms websocket
browser.js:38 sockjs-client:websocket message event +2s h
browser.js:38 sockjs-client:main _transportMessage +0ms h
browser.js:38 sockjs-client:main heartbeat +0ms websocket
browser.js:38 sockjs-client:websocket message event +2s h
browser.js:38 sockjs-client:main _transportMessage +1ms h
browser.js:38 sockjs-client:main heartbeat +0ms websocket
browser.js:38 sockjs-client:websocket close event +360ms 1000 
browser.js:38 sockjs-client:main _transportClose +1ms websocket 1000 
browser.js:38 sockjs-client:main _close +0ms null 1000  undefined 1
browser.js:38 sockjs-client:websocket _cleanup +1ms
browser.js:38 sockjs-client:main disconnected +1ms
```

**Comment by brycekahle** [comment]
Hmm, literally two lines before the 'disconnected' debug is the dispatch of the close event.

**Comment by blittle** [comment]
@brycekahle A little more playing around and I get can it to work if I use the single distributable https://github.com/sockjs/sockjs-client/blob/master/dist/sockjs-1.0.3.js whereas it does not work when I run with the npm installed version (loaded with System.js)

**Comment by brycekahle** [comment]
If you want to run the npm version in the browser, you need to use `browserify`. It isn't built for any other packaging system right now.

**Comment by blittle** [comment]
:cry: okay. Thank you for looking into the problem. It does seem weird that it would mostly work other than issues like this.
