### ISSUE TITLE
Support old protocols_whitelist option in addition to the new transports one

### ISSUE THREAD

**Issue by sdeleuze** [sockjs/sockjs-client#215]
In order to make migration to SockJS client 1.0 easier, would you consider supporting the old `protocols_whitelist` option (with a warning in the console) in addition to the new `transports` one ?

This backward compatibility improvement could allow us to [upgrade to SockJS client 1.0](https://jira.spring.io/browse/SPR-12422) in our Spring Framework 4.1.x releases. Without that, we may be forced to wait 4.2 release next year.

If it helps, I can provide a pull request.

**Comment by brycekahle** [comment]
@rstoyanchev I added a warning if the user specifies `protocols_whitelist`.

**Comment by rstoyanchev** [comment]
Sounds good. I think a case could be made to go even farther and fail. For anyone currently relying on the option they might not notice the configuration is being ignored until it causes issues in production.
