### ISSUE TITLE
Firefox: too much recursion (1.0.0-beta.6)

### ISSUE THREAD

**Issue by robvdl** [sockjs/sockjs-client#218]
On Firefox I get "too much recursion" pointing to this line:

https://github.com/sockjs/sockjs-client/blob/b912ce19a2b0069575848ddfd740a3e0980fc652/dist/sockjs-1.0.0-beta.6.js#L5076

This file is in the /dist folder, I don't know where it is located in the actual source.

In Chrome it is working fine, just happens on Firefox.

**Comment by mattj65817** [comment]
My Firefox updated itself to 35.0 yesterday, and ever since that upgrade, I am getting the same error in sockjs-client 1.0.0-beta.10 on Windows. It worked fine with the previous version of Firefox, which I assume was 34.0. Also works fine in Chrome and IE 10. Let me know if there is anything I can do to help fix the issue.

**Comment by robvdl** [comment]
Yes, the problem hasn't gone away for me either, but the problem is not with sockjs-client, but url-parse instead.

There have been other releases of url-parse, but they never actually fixed the problem for me.

I have been using a sockjs-go as a backend, so I was going to look into that maybe, then got quite busy with Python projects and forgot about it for a bit.  Anyway, I doubt the sockjs-go backend will be the issue because it's working fine on other browsers (including Firefox for Windows), also others here are having the issue too.

**Comment by 3rd-Eden** [comment]
@robvdl & others, I've been working on refactor of the `url-parse` to move away from regexp based parsing all together as FireFox's engine cannot handle this in exotic edge cases. So we're aware of the issue and working as fast as we can fix it for all.

**Comment by ttamminen** [comment]
Great work guys! 

Do you know when is it possible to fetch sockjs-client beta-release, so that we can test the fix?

**Comment by lpinca** [comment]
@ttamminen `sockjs-client-1.0.0-beta.12` has been just released.

**Comment by ttamminen** [comment]
Thanks for the info @lpinca! I will update our software tomorrow and see what happens.
