### ISSUE TITLE
Chrome apps don't allow unload event handlers

### ISSUE THREAD

**Issue by alxlo** [sockjs/sockjs-client#223]
When using sockjs 0.3.4 as part of a W3C packaged app (Chrome App), sockjs-0.3.4.js:595
<pre>
utils.attachEvent('unload', unload_triggered);
</pre>

results in an error message "unload is not available in packaged apps."

**Comment by 8026787** [comment]
+1

**Comment by brycekahle** [comment]
Does this actually prevent your app from working? From what I can tell it is just a warning. You can use  https://developer.chrome.com/apps/runtime#event-onSuspend and then close the connection manually if you want.

**Comment by alxlo** [comment]
It really is just a warning and everything seems to work as expected.
