### ISSUE TITLE
WebSockets: max-connections are more than 2...

### ISSUE THREAD

**Issue by pstephenwille** [sockjs/sockjs-client#225]
Thought i'd bring this to your attention.

The documentation looks to be a bit dated as the 2  connection limit hasn't been true for a few years.
FF 36.0 shows a websocket.max-connections of 200, and I assume something similar is true for the other browsers.

Chrome seems to have a limit of 30:
https://code.google.com/p/chromium/issues/detail?id=429419

**Comment by brycekahle** [comment]
You are talking explicitly about Websockets, but there is no guarantee that is the transport that will be used.

**Comment by 3rd-Eden** [comment]
Also your assumption in false in regards to other browsers. IE also has some severe limitations regarding websockets and it can actually limited using system preferences so it means it can be anywhere from 0-1000

**Comment by brycekahle** [comment]
Not to mention a big part of this project is good browser compatibility. The limits of IE6/7 aren't changing.
