### ISSUE TITLE
How to run client tests against other SockJS server

### ISSUE THREAD

**Issue by purplefox** [sockjs/sockjs-client#226]
With the old QUnit tests we used to start our own server on port 8081 and they would run against that, and there was information in the README that explained how to do that (seems to have been removed now).

With the new tests (running make test-local) it seems to start up its own instance of the sockjs-node server and test against that.

How do I configure the new tests so they don't start a sockjs-node server and run against ours instead?

Thanks

**Comment by brycekahle** [comment]
I don't think there is a straightforward way to do that right now. Are you looking to run the protocol tests? Those are located at https://github.com/sockjs/sockjs-protocol.

**Comment by purplefox** [comment]
We're already running the protocol tests, but it was an important part of our QA to run the other tests too...

Seems like quite a bit regression to me to suddenly drop support for all the other SockJS servers...

**Comment by brycekahle** [comment]
The tests in this repo are meant to test the javascript client. Not to test the server.

**Comment by purplefox** [comment]
The tests in this repo may now be only to test the JavaScript client, but that's only because they've been changed to exclusively work in that way - it that wasn't the case in the past.

Going back to the 0.3.4 tag, you can see the old QUnit tests allowed for running against other servers. And trust me I found lots of bugs in the past doing this that didn't show up on the QUnit tests, so it was very useful.

Also here's a post from Marek (original author of SockJS) who explains that running against other servers is useful and desired:

https://groups.google.com/d/msg/sockjs/y3wRuFqObk0/Htas3hhtJFwJ

So, it seems like a really big regression to me, and a bit of a "screw you" to all the non node SockJS server implementations.

Is there any chance of getting this fixed?

**Comment by brycekahle** [comment]
If there are additional tests that should be used to verify server behavior, then they belong in the protocol tests.

**Comment by brycekahle** [comment]
@purplefox I'm going to close this issue. If you think there are valuable tests from the 0.3.4 days, I would love to add those to the protocol test suite. PRs and/or pointing out which tests were helpful would be appreciated.
