### ISSUE TITLE
JSONP doesn't work?

### ISSUE THREAD

**Issue by jkarneges** [sockjs/sockjs-client#227]
I'm forcing the SockJS echo example to use JSONP for testing purposes and it doesn't seem to work. Even if ``jsonp-polling`` is forced via whitelisting as the only allowed transport, the SockJS client library still makes an XHR request to the ``/info`` endpoint which is JSONP-incompatible.

Here's what I did: I checked out the latest ``sockjs-node`` repository and ran ``npm i`` for the echo example. Then, I edited sockjs-node/examples/echo/node_modules/sockjs/lib/trans-xhr.js to remove CORS headers in the response, and I edited sockjs-node/examples/echo/index.html to use a new initialization line:

    var sockjs = new SockJS('http://otherhost:9999/echo', null, {
        protocols_whitelist: ["jsonp-polling"]
    });

The domain "otherhost" is in my /etc/hosts file and points to 127.0.0.1. I then load http://localhost:9999/ in Firefox. Using a different domain name in the SockJS URL ensures requests are cross-domain.

Anyway, it fails with a typical CORS error while fetching the ``/info`` resource. The client library does not appear to attempt anything further. Is there something I'm missing? Thanks!

Update: If I ensure the CORS headers are available on /info, then the JSONP transport otherwise works. For example, when issuing send calls to the ``/jsonp_send`` endpoint, I can see that the transport uses an html form rather than XHR to POST the data.

**Comment by jkarneges** [comment]
False alarm. The utils.isXHRCorsCapable method determines browser-side whether XHR is possible. If I change this method to report CORS as unavailable, then the client will not use XHR to fetch ``/info``. This issue makes testing JSONP harder, since you either have to edit the code manually like this or run an ancient browser (the latter I was trying to avoid ;)).

It would be nice if whitelisting to jsonp-polling on the client-side truly enforced the transport, but I'm mostly just glad I could confirm the transport works. Sorry for the noise!

**Comment by brycekahle** [comment]
Interesting find. I can see about using the transport whitelist when determining what to use for the `info` request.
