### ISSUE TITLE
Making the iframe transport optional without client modification

### ISSUE THREAD

**Issue by jkarneges** [sockjs/sockjs-client#228]
I'm writing my own SockJS server implementation, and I'm concerned about the iframe transport and the need for the server to be configured with a URL to the sockjs client library. If a CDN is used, then it could be decomissioned someday (as I noticed in issue #198). I also wonder about versioning issues, for example if different SockJS client versions try to connect to the same server which has only one client library URL configured.

I think it would be good if the iframe transport could be enabled/disabled server side. It should probably start out disabled, and enabling it would require the administrator to be conscious of the sockjs url issue. This could be the case for my own implementation, as well as the official `sockjs-node` server.

The only problem is that the client seems to insist on iframe support being present. Is there a way the server can return a specially crafted iframe.html that would cause the client to fallback to JSONP without needing a sockjs url?

Maybe for the upcoming 1.0, you could fallback to JSONP if the iframe.html request returns 404? This would simplify the server side, so that disabling is as easy as not serving the file at all.

**Comment by brycekahle** [comment]
You should file an issue on `sockjs-node` to add support for disabling specific transports. Currently there is only a `websocket` options to turn off websockets.

**Comment by brycekahle** [comment]
As far as versioning issues, I've tried to start a discussion in #217

**Comment by brycekahle** [comment]
@jkarneges What does the client do right now if the request for `iframe.html` returns a 404? I would expect it to proceed with the next transport.

**Comment by jkarneges** [comment]
It just stops. To reproduce it, you need a browser without CORS. I tested by simply commenting out the CORS check around line 911:

    utils.isXHRCorsCapable = function() {
        /*if (_window.XMLHttpRequest && 'withCredentials' in new XMLHttpRequest()) {
            return 1;
        }*/

**Comment by jkarneges** [comment]
Hi, any update about making the client proceed to the next transport if iframe is not available?

**Comment by brycekahle** [comment]
@jkarneges Sorry, i haven't been able to work on this yet. If you are itching for a fix, I would happily accept a PR.

**Comment by brycekahle** [comment]
So I did some testing. If you are using:
1. a cross-origin SockJS URL 
2. CORS is not enabled
3. iframe doesn't work

Then yes, it will completely stop. This is because it needs the iframe to do anything cross-origin in the absense of CORS.

If CORS works, but `iframe.html` returns `404`, then everything works as expected. Given that, I'm going to close this issue.

**Comment by jkarneges** [comment]
Hmm, I'm not sure that makes sense regarding transport fallback. JSONP works without iframe. If CORS and iframe are not available then it seems reasonable that the client should fall back to JSONP rather than stopping.

**Comment by brycekahle** [comment]
SockJS currently doesn't support retrieving the `/info` endpoint via JSONP.
