### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by cilia** [sockjs/sockjs-client#234]
According to this post: https://github.com/sockjs/sockjs-client/issues/198#issue-43964802, the milestone 1.0 version was supposed to be released at some point in October or November, 2014. But unfortunately that did not happen. Checking the build and testing status, we see a stream of failures.

Just wondering if the official release of 1.0 is significantly delayed due to some major roadblock. ETA may not be realistic/reliable at this stage, but some update on the project status will be much appreciated by the user community.

Thank you.

**Comment by brycekahle** [comment]
The test failures are just the result of difficulties doing CI testing, not anything wrong with the project. The only thing holding back a proper 1.0 release was waiting to see if any issues cropped up.

**Comment by FZambia** [comment]
+1 to this question - still don't undestand what's blocking from your answer, do you have at least approximate dates of release? Also is there an instruction how to update server side SockJS libraries to fit 1.0 release? What about SockJS v1.0 server protocol tests?

**Comment by brycekahle** [comment]
The 1.0 client is backwards compatible with existing SockJS servers. It speaks the same protocol.

**Comment by FZambia** [comment]
wow, this is wonderful, I was just confused by this v1.0 change:
```
Support EventSource / Server Sent Events outside of iframes
```
Thought that eventsource without iframe must be implemented on server side.

**Comment by brycekahle** [comment]
@FZambia the iframe was only used to get around cross-origin restrictions. Since a lot of browsers now support CORS for SSE, you can utilize them directly.
