### ISSUE TITLE
map file absent from dist folder and from minified file

### ISSUE THREAD

**Issue by jlowcs** [sockjs/sockjs-client#237]
The ```sockjs-1.0.0-beta.12.js``` currently references a ```sockjs.js.map``` that is absent from the ```dist``` folder.

Also, shouldn't that sourceMappingURL be in the minified file instead of the non-minified file?

**Comment by brycekahle** [comment]
I can get the source maps added to the repo. Both versions have source maps because they are combined from individual modules. The source map allows you to debug as if they were still separated out.

**Comment by deependraus** [comment]
Has the map been added? I still do not see it in the dist.

**Comment by brycekahle** [comment]
Not yet. I will close the issue when I have added it.

**Comment by ngocdaothanh** [comment]
Hi, can you add the map file? It's quite annoying when seeing
sockjs.js.map 404 Not Found
in web server access log all the time.

**Comment by brycekahle** [comment]
I've updated the build script to add the file to the `dist` folder. The next release will add the file.
