### ISSUE TITLE
Fallbacks work with 0.3.4 but not with 1.0.0-beta.12 when websocket not sending data

### ISSUE THREAD

**Issue by jlowcs** [sockjs/sockjs-client#238]
I'm trying to connect to a server that allows the creation of a websocket, but no data is sent.

Obviously, there is an issue in our environment, and people are working on it.

That being said, sockjs-client v1.0.0-beta.12 never tries to connect using the fallbacks, while 0.3.4 does.

The timeout is reached, and the ```_transportTimeout``` function is called. The ```_connect``` function is never called again to try the next transport.

I replaced the ```debug``` function with a simple console.log. Here's what's written on the console:

```
same http://192.168.10.181:8180/api/messages <myappurl> false
http://192.168.10.181:8180/api/messages
doXhr http://192.168.10.181:8180/api/messages/info
GET http://192.168.10.181:8180/api/messages/info
withCredentials
readyState 2
readyState 3
status 200
chunk
readyState 4
status 200
finish 200 {"entropy":982913874,"origins":["*:*"],"cookie_needed":true,"websocket":true}
finish Object {entropy: 982913874, origins: Array[1], cookie_needed: true, websocket: true} 25
_cleanup
_receiveInfo 25
info Object {entropy: 982913874, origins: Array[1], cookie_needed: true, websocket: true, nullOrigin: false…}
enabled
enabled websocket
enabled xhr-streaming
disabled xdr-streaming
enabled eventsource
enabled iframe-eventsource
disabled htmlfile
enabled iframe-htmlfile
enabled xhr-polling
disabled xdr-polling
enabled iframe-xhr-polling
enabled jsonp-polling
8 enabled transports
attempt websocket
using timeout 650
transport url http://192.168.10.181:8180/api/messages/495/qcfiybrz
enabled
constructor http://192.168.10.181:8180/api/messages/495/qcfiybrz
cleanup
_transportTimeout
_close undefined 2007 Transport timed out undefined 0
close
_cleanup
disconnected
```

**Comment by brycekahle** [comment]
Thanks for the bug report. I will try and reproduce your issue this evening.

**Comment by Xotically** [comment]
brycekahle can you tell me how i  can set your Fallbacks 0.3.4 i have 0.3.4 in my js/lib client directory and in the html index but its complaining  about not finding http://sim.psim.online/showdown/info i have added addons showdown/info but no content example > no changing entropy: 00000000 how do install it like http://prntscr.com/bkohtf please help
