### ISSUE TITLE
Simple polling

### ISSUE THREAD

**Issue by zgmnkv** [sockjs/sockjs-client#241]
Hi,
As far as I can see, 'xhr_polling' transport is a long polling.
Many http servers, specifically old versions, do not support long polling.
Why don't you support simple xhr polling transport?
Thanks

**Comment by brycekahle** [comment]
The server is the one who determines whether or not it is 'long polling'. If the server returns right away, then it is normal xhr polling.

Do you have a specific sockjs server project that doesn't support long polling?

**Comment by zgmnkv** [comment]
I use spring framework (java) on a server side. It supports long polling, but application server may not support it (e.g. tomcat 6).
Actually I want to use simple polling on a server side and  I can't find how can I configure it if it's possible.

**Comment by brycekahle** [comment]
I'm not sure this is the best framework for you if all you want is normal ajax polling.
