### ISSUE TITLE
SockJS in Phonegap application problem with release mode

### ISSUE THREAD

**Issue by Drazke** [sockjs/sockjs-client#243]
Hi,

I've been using SockJS for client/server websocket connection over SSL in my Phonegap application. Everything works fine when I build it in debug mode on Android, but it doesn't work in release mode(with signing keystore for Android). I get the 1002 error code ('Cannot connect to server') from SockJS.

After some test, I figure it out that this problem occurs only when using SSL, the release version work fine without SSL. 

I'm using the lasted version of SockJS(v1.0.0).

Do you know how to fix that problem ?

**Comment by brycekahle** [comment]
Can you post a request/response trace? You can use something like Charles Proxy to be a man-in-the-middle if you need.

**Comment by Drazke** [comment]
When I used Charles Proxy between my app and my server, the connection was made and I received the data from my server, but after 5s, I got the error 'Server lost session'.

Here is the requests/responses from Charles Proxy during one connection : 

REQUEST:
 GET /echo/754/tuhuj0rz/websocket HTTP/1.1
Host: ***********:****
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: file://
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; Nexus 9 Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/42.0.2311.138 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,en-US;q=0.8
X-Requested-With: com.*****.*****
Sec-WebSocket-Key: oMMAEz8HBLVa7/vr9Tqbfg==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

RESPONSE: 
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: +w5Xrt/TIcYGKJigNNrTUzau9FM=

3 same REQUESTS :
GET /echo/754/rjjovgc4/eventsource HTTP/1.1
Host: *************:****
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/event-stream
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; Nexus 9 Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/42.0.2311.138 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,en-US;q=0.8
X-Requested-With: com.*****.*****

3 same RESPONSES + DATA(not show):
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Content-Type: text/event-stream
Access-Control-Allow-Origin: *
Vary: Origin
Date: Tue, 19 May 2015 10:02:29 GMT
Connection: keep-alive
Transfer-Encoding: chunked

In the last data RESPONSE, I've got the data : 
data: c[1000,"Normal closure"]

Hope this could help.

**Comment by brycekahle** [comment]
It sounds like the server might not be receiving data from the client. Can you confirm that?

**Comment by Drazke** [comment]
Ok, I find out that my server have an error when SockJS switch very quickly between websocket and eventsource. So I fix it and now my application over SSL work fine when I use CharlesProxy but still don't work without CharlesProxy...

**Comment by Drazke** [comment]
I finally find out what was the problem, it's due to the CA root certificate which was missing in my server... CharlesProxy use his own CA root certificate, that why it worked with CharlesProxy.

Sorry for the inconvenience and thank you for leading me to use CharlesProxy which help me to find out.

**Comment by brycekahle** [comment]
No problem! I'm glad you figured it out. Charles Proxy is a great tool. If you use windows, Fiddler is also great.
