### ISSUE TITLE
Re: Long jSON message causing unhandled frame

### ISSUE THREAD

**Issue by dungvu-qe** [sockjs/sockjs-client#251]
We have bugs while using stomp-websocket(ver 2.3.4) with your lib: SockJs(ver 1.0.0). If we send a bigs data via sockjs with Chrome, the connection is broken.
Here is issue from stomp-websocket: https://github.com/jmesnil/stomp-websocket/issues/87
We tried to debugs what it happend, seem like the issue came from SockJs, not stomp-websocket
Could you check this case for me? Sorry if I'am wrong :)

**Comment by brycekahle** [comment]
We have tests that echo 8K messages. Do you have more information? If you use the non-minified version, run the following in a browser console `localStorage.debug = '*';` and then refresh you should get some debug output.

**Comment by dungvu-qe** [comment]
Sorry my late reply,
We cant not show my server site (Domain, IP) in this log, and changed it to
contoso.com
The server is RabbitMQ 3.5.3 use StompJS plugin.
Here the logs as you request, orig msg we sent in this test is 318K.

If you need more info, please request me :)

-- 

*Dung Vu | Developer | Amigo Quant Edge JSC*

**Comment by dungvu-qe** [comment]
https://devzone.quantedge.vn/attachments/download/55663/localhost-1437452223333.log

here my log.

-- 

*Dung Vu | Developer | Amigo Quant Edge JSC*

**Comment by brycekahle** [comment]
Thanks. I will take a look.

**Comment by brycekahle** [comment]
I don't see anything that indicates sockjs-client is at fault here. This log on line 43
> ```sockjs-client:websocket close event +164ms 1006 ```

indicates it received a `close` event from the browser websocket object.

**Comment by dungvu-qe** [comment]
You right, its always happen on Chrome (with my test case). IE and firefox
still fine. Have you got any idea for this case?

-- 

*Dung Vu | Developer | Amigo Quant Edge JSC*

mobile: +849 0896 6639 <//mobile:%20+849%200896%206639>
email: dung.vu@quant-edge.com
skype: dung.vt

Amigo Quant Edge JSC
Suite #503, IPH Building
241 Xuan Thuy Street, Cau Giay Dist
Hanoi, Vietnam

tel: +84 (4) 7300 8999 <//tel:%20+84%20(4)%207300%208999>
fax: +84 (4) 7300 3999 <//fax:%20+84%20(4)%207300%203999>
web: www.quant-edge.com
------------------------------

This message (including attachments, if any) is confidential, may be
privileged and is intended for the above-named recipient(s) only. If you
have received this message in error, please notify me by return email and
delete this message from your system. Any unauthorized use or disclosure of
this message is strictly prohibited.

Amigo Quant Edge JSC assumes no responsibility for errors, inaccuracies or
omissions in these materials, and does not warrant the accuracy or
completeness of the information contained within these materials. Amigo
Quant Edge JSC shall not be liable for any special, indirect, incidental,
or consequential damages, including without limitation losses, lost
revenues, or lost profits that may result from these materials.

**Comment by brycekahle** [comment]
Test with the latest Canary version of Chrome. If you can make a small reproducible test case, file a bug with the Chrome team. Alternatives would be to send smaller messages, but I don't know if that is possible in your case.

**Comment by dungvu-qe** [comment]
by default webstomp split big msg to smaller msgs with size =
maxWebSocketFrameSize (
https://github.com/jmesnil/stomp-websocket/blob/master/lib/stomp.js).

But send via Chrome, this still auto close connection :(
Here the sample code get from Stomp-Websocket, if you want to look up.

-------------------------------
function Client(ws) {   this.ws = ws;   this.ws.binaryType = "arraybuffer";
this.counter = 0;   this.connected = false;   this.heartbeat = {   outgoing:
10000,   incoming: 10000   };   *this.maxWebSocketFrameSize = 16 * 1024;*
this.subscriptions = {};   this.partialData = '';   }

------------

Client.prototype._transmit = function(command, headers, body) {   var out;
out = Frame.marshall(command, headers, body);   if (typeof this.debug === "
function") {   this.debug(">>> " + out);   }   *while (true) {*   *if
(out.length > this.maxWebSocketFrameSize) {*   *this.ws.send(out.substring(0,
this.maxWebSocketFrameSize));*  * out =
out.substring(this.maxWebSocketFrameSize);*   *if (typeof this.debug ===
"function") {*   *this.debug("remaining = " + out.length);*  * }*  * } else
{*   *return this.ws.send(out);*  * }*  * }*   };

-- 

*Dung Vu | Developer | Amigo Quant Edge JSC*

mobile: +849 0896 6639 <//mobile:%20+849%200896%206639>
email: dung.vu@quant-edge.com
skype: dung.vt

Amigo Quant Edge JSC
Suite #503, IPH Building
241 Xuan Thuy Street, Cau Giay Dist
Hanoi, Vietnam

tel: +84 (4) 7300 8999 <//tel:%20+84%20(4)%207300%208999>
fax: +84 (4) 7300 3999 <//fax:%20+84%20(4)%207300%203999>
web: www.quant-edge.com
------------------------------

This message (including attachments, if any) is confidential, may be
privileged and is intended for the above-named recipient(s) only. If you
have received this message in error, please notify me by return email and
delete this message from your system. Any unauthorized use or disclosure of
this message is strictly prohibited.

Amigo Quant Edge JSC assumes no responsibility for errors, inaccuracies or
omissions in these materials, and does not warrant the accuracy or
completeness of the information contained within these materials. Amigo
Quant Edge JSC shall not be liable for any special, indirect, incidental,
or consequential damages, including without limitation losses, lost
revenues, or lost profits that may result from these materials.

**Comment by brycekahle** [comment]
I would look into either Chrome itself, or the server implementation.

**Comment by kusto777** [comment]
Hi, I have same issue...

Here is my RabbitMQ (3.4.3) logs for this eror.

.log

=ERROR REPORT==== 21-Jul-2015::16:12:48 ===
Error in process <0.4605.0> on node 'rabbit@STAS-PC' with exit value: {{badmatch,<<273 bytes>>},[{cowboy_http_websocket,websocket_data,4,[]},{cowboy_http_protocol,upgrade_protocol,3,[]}]}


sasl.log

=SUPERVISOR REPORT==== 21-Jul-2015::16:12:48 ===
     Supervisor: {<0.3058.0>,cowboy_requests_sup}
     Context:    child_terminated
     Reason:     {{badmatch,<<1,254,62,133,119,170,60,108,44,136,121,24,22,
                              157,118,63,51,207,82,37,32,192,125,71,6,216,88,
                              59,79,221,85,84,66,219,90,9,13,248,78,45,60,221,
                              81,61,24,210,116,26,20,226,106,27,2,154,127,43,
                              52,159,101,31,22,196,12,35,56,147,90,46,14,155,
                              19,88,24,218,125,95,15,232,78,62,62,192,95,71,
                              79,242,12,32,78,238,81,53,14,192,79,26,17,251,
                              74,57,37,218,68,7,62,199,8,5,32,249,95,84,27,
                              217,83,67,24,146,74,89,62,193,107,58,79,198,88,
                              24,51,243,9,21,1,248,93,26,78,229,77,14,19,224,
                              112,29,1,249,70,5,66,223,121,27,79,227,4,25,60,
                              159,5,67,35,226,110,60,51,133,115,27,70,226,95,
                              43,50,251,23,95,66,211,79,41,92,156,105,10,70,
                              211,10,91,30,226,113,62,54,193,19,45,5,194,86,
                              54,16,193,79,88,27,154,116,11,36,211,116,3,37,
                              216,109,85,51,249,19,84,63,200,118,88,31,217,84,
                              4,33,153,77,54,13,228,120,10,58,225,111,0,50,
                              147,126,21,79,243,14,35,61,154,111,3,2,206,23,
                              56,2,255,106,67,18,229,126,6,66,221,90,25,29,
                              195,10,37,4>>},
                  [{cowboy_http_websocket,websocket_data,4,[]},
                   {cowboy_http_protocol,upgrade_protocol,3,[]}]}
     Offender:   [{pid,<0.4605.0>},
                  {name,cowboy_requests_sup},
                  {mfargs,{cowboy_requests_sup,start_request,undefined}},
                  {restart_type,temporary},
                  {shutdown,brutal_kill},
                  {child_type,worker}]

**Comment by brycekahle** [comment]
I think this is a stomp-websocket issue, please comment on the issue there.

**Comment by kusto777** [comment]
It doesn't seems to be the truth... 
I tried to send same message using direct sockjs method call.
Same result - works in IE and lost connection in Chrome.

**Comment by brycekahle** [comment]
Still against stomp server? That is where I think the issue is. That OR Chrome itself. If it works in IE and Firefox, how could it be the client library?



—
Bryce

**Comment by EmadAlblueshi** [comment]
Any updates regarding Chrome ?
