### ISSUE TITLE
Node.js XhrDriver doesn't use https module for https URL

### ISSUE THREAD

**Issue by snoopaloop** [sockjs/sockjs-client#254]
Hello,

Our sockjs endpoint is fully https, so when connecting with node.js client, the XhrDriver only will use the node `http` module to do the request, and won't use an `https` request (making everything fail).

Should I force a different transport that would use https for the `/info` requests?

Not sure if this is something you want to change, or I could submit a pull request to change this. I didn't find any related issues, so if this is a non-issue, I will just do a local patch because I'm only using this for testing.

Thanks

**Comment by brycekahle** [comment]
Thanks for the bug report. I will definitely take a look at this. 



—
Bryce

**Comment by snoopaloop** [comment]
@brycekahle Thanks for the quick reply.

**Comment by brycekahle** [comment]
I just published `1.0.3` which should fix the issue.

**Comment by snoopaloop** [comment]
@brycekahle :+1:
