### ISSUE TITLE
Error 1002 on sockjs-client connect. (client version 0.3.4)

### ISSUE THREAD

**Issue by n0n0n0** [sockjs/sockjs-client#255]
From time to time our web client got this error on connect (1002). On server side console I see only 1 string at moment of error: ```GET /<prefix>/info 1ms 200```. When connection established ok, there is second line must be on server side console: ```GET /<prefix>/<4 digit>/<random string>/websocket```.
So i cant understand where is problem? How i can debug this situation? This kind of error could be 1-2 times per day of work our sockjs-client.

**Comment by brycekahle** [comment]
There should be an error message along with code. If you can get that, that would help trace the issue. I also suggest using the latest version of the client, which is 1.0.3 right now.

**Comment by n0n0n0** [comment]
I will try use 1.0.3 version. I will write here about results.
About error message: I cant say anything about it, when error occurs, I got phone call and user told me what he saw on screen (special message, that depends on error code, in this case error code = 1002, and i dont no, is there could be different messages on same error code? If we look to sockjs code we will see this ``` that._didClose(1002, 'Can\'t connect to server', true);``` at 986 line v0.3.4 sockjs client)
