### ISSUE TITLE
Client appears to not send Sec-WebSocket-Version

### ISSUE THREAD

**Issue by nickmiller-wf** [sockjs/sockjs-client#256]
I'm currently utilizing `sockjs-client` to communicate with a Go service using [`gorilla/websocket`](https://github.com/gorilla/websocket). `gorilla/websocket` does some checks on the connection upgrade, the very first being a version check [here](https://github.com/gorilla/websocket/blob/master/server.go#L96)

Initializing my test connection via

```
new SockJS('/api/v0.1/test/ws')
```

causes my handler to error out with the message: `"websocket: version != 13"`, as specified by the `gorilla/websocket` setup above. The WebSocket [RFC](https://tools.ietf.org/html/rfc6455#section-4.2.1) specifies this as a requirement.

If I can get confirmation that this is in fact a `sockjs-client` issue, I'd be happy to take a stab at a PR. Thanks!

**Comment by brycekahle** [comment]
Are you trying to just establish a raw websocket connection? `sockjs-client` expects to be talking to a sockjs server, so the request you are seeing is likely the initial `info` request, not a WebSocket connection.

**Comment by nickmiller-wf** [comment]
Yeah my hope was to just upgrade the initial connection and use that for the websocket connection. Definitely seeing that `/info` path getting hit... So do I need to return a special response on `/info` and use that next client request as the connection to upgrade?

**Comment by brycekahle** [comment]
Sounds like you just want a normal WebSocket, so `sockjs-client` is not what you want. Just use the WebSocket API that the browser implements. See https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API for a starting point.

**Comment by nickmiller-wf** [comment]
All right, sounds good. Thanks
