### ISSUE TITLE
SockJS('http://localhost:5672') connetion fails with  No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by BoykoAlex** [sockjs/sockjs-client#258]
Hi,
I'm connecting to a local RabbitMQ with SockJS-client from a web UI (hosted locally as well).
The call is SockJS('http://localhost:5672') this results in closed connection moments later. The error is: XMLHttpRequest cannot load http://localhost:5672/info?t=1439855084292. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
Should I set something on the RabbitMQ server to grant localhost:8080 access? Any idea what to look at exactly?
Thanks in advance!

Cheers,
Alex

**Comment by brycekahle** [comment]
`sockjs-client` needs to talk to a SockJS server (like `sockis-node`). If you just want raw WebSockets, I suggest you use the native WebSocket APIs. See https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API for more info.
