### ISSUE TITLE
Enable debug logging in console

### ISSUE THREAD

**Issue by leolux** [sockjs/sockjs-client#260]
How to enable debug logging as stated in line 627?

```
if (process.env.NODE_ENV !== 'production') {
  // Make debug module available globally so you can enable via the console easily
  global.dbg = require('debug');
  debug = global.dbg('sockjs-client:main');
}
````
I couldn't find any information about the keywords "debug", "logging" and "mode" in the documentation https://github.com/sockjs/sockjs-client#sockjs-class

**Comment by brycekahle** [comment]
Use the non-minified version of the library. Then issue this command in your browser console `localStorage.debug = '*';` and reload.

**Comment by leolux** [comment]
Got it, thanks!
That's an awesome feature. Where to read on?

**Comment by brycekahle** [comment]
It is using the [debug](https://github.com/visionmedia/debug) module. If you want to scope the logs to a particular transport or file, you can find out what it passed to `debug` (example https://github.com/sockjs/sockjs-client/blob/master/lib/transport/websocket.js#L12) and do `localStorage.debug = 'sockjs-client:websocket';` instead.
