### ISSUE TITLE
EventSource response has a MIME type (“text/html”) that is not “text/event-stream”

### ISSUE THREAD

**Issue by Volodymyr128** [sockjs/sockjs-client#261]
Get this error whyle trying to create new SockJS(http://localhost:3000/sjs). Full description you may find here http://stackoverflow.com/questions/32506980/sockjs-eventsource-response-has-a-mime-type-text-html-that-is-not-text-eve

**Comment by brycekahle** [comment]
I will try and take a look this evening. If you can capture the response from the Network tab that would help.
