### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by agrawal-mohit** [sockjs/sockjs-client#262]
I'm seeing this message on browser console and the connection is not happening. 

The server is on a remote machine. Do I need to specify any CORS header ? How ?

**Comment by brycekahle** [comment]
Look in your network tab to see which request it is. Then post as much details as you can.

**Comment by brycekahle** [comment]
Looking at the linked issue looks like this was a bug elsewhere.

**Comment by marcoippolito** [comment]
@brycekahle I'm having now the same problem which I described here: https://github.com/sockjs/sockjs-client/issues/497
Would you be so kind in helping?
Thank you in advance
