### ISSUE TITLE
WebSockets on iOS

### ISSUE THREAD

**Issue by derekm** [sockjs/sockjs-client#264]
Apparently there is a bug in the iOS implementation of WebSockets.

A workaround is described here: http://stackoverflow.com/a/10883816/2355587

Basically, the value of "this" is lost in the WebSocket callbacks, so you need to reference your own private copy of "this" in callbacks (e.g., "var me = this", "var self = this", "var that = this", etc.).

In my own use-case, Apache's mod_proxy_wstunnel prohibits SockJS from falling back to XHR Streaming when WebSockets fails on iOS, so my chat feature doesn't work in QA on iOS mobile devices.

**Comment by brycekahle** [comment]
SockJS is already doing this.

**Comment by derekm** [comment]
Ok, thanks for the notice. We adopted SockJS maybe two or 3 months ago. Maybe we need to upgrade if it was implemented since that time. Do you know which release first got this support?

**Comment by brycekahle** [comment]
Anything >= 1.0.0
