### ISSUE TITLE
When used in nodejs context, accept an outgoing interface option

### ISSUE THREAD

**Issue by prawnsalad** [sockjs/sockjs-client#272]
I'm trying to develop a sockjs loadtesting tool in nodejs but can't exceed 65,000 clients due to the local port limit on linux. To get around this I need to specify an outgoing network interface (eg. 192.168.1.10, 192.168.1.11) to get 65k outgoing clients per interface. Maybe it's possible already but I haven't found a way.

**Comment by brycekahle** [comment]
We use `faye-websocket-node` and I don't see an option for it to specify the network interface. You will probably need to fork that and this library to passthrough the options.

**Comment by brycekahle** [comment]
You will want to specify the `localAddress` option to `net.Socket.connect` [options](https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener)

**Comment by prawnsalad** [comment]
Thanks, I've actually managed to modify both faye-websocket and sockjs-client to accept a `localAddress` property in the `SockJS` constructor `options` argument. Should I send a PR to both projects? Obviously sockjs-client wouldn't be able to use it unless faye-websocket accept the PR.

**Comment by prawnsalad** [comment]
PR can be found here https://github.com/sockjs/sockjs-client/pull/273

**Comment by brycekahle** [comment]
Once `1.1.0` is released, you will be able to use the new `transportOptions` to accomplish this, like so:

```
var options = {
  transportOptions: {
    websocket: {
      net: {
        localAddress: '192.168.1.10'
      }
    }
  }
};
var sockjs = new SockJS(url, undefined, options);
```
