### ISSUE TITLE
BUGFIX IE 11 Emulated to 8

### ISSUE THREAD

**Issue by ch4p43v** [sockjs/sockjs-client#276]
IE 11 Emulation mode for 8 have a Problem (global.console[level].apply).
Add try catch block:
```
['log', 'debug', 'warn'].forEach(function (level) {
	try {
		var levelExists = global.console && global.console[level] && global.console[level].apply;
		logObject[level] = levelExists ? function () {
			return global.console[level].apply(global.console, arguments);
		} : (level === 'log' ? function () {} : logObject.log);
	} catch (e) {};
});
```
and is's works! ;-)

**Comment by syberkitten** [comment]
Yes, Can verify this issue also occurs on native IE8.

**Comment by syberkitten** [comment]
I would do it as such:
['log', 'debug', 'warn'].forEach(function (level) {
    var levelExists;
    try {
        levelExists = global.console && global.console[level] && global.console[level].apply;
    } catch(e){}

  logObject[level] = levelExists ? function () {
    return global.console[level].apply(global.console, arguments);
  } : (level === 'log' ? function () {} : logObject.log);

});
