### ISSUE TITLE
Can't connect via ws protocol

### ISSUE THREAD

**Issue by Volodymyr128** [sockjs/sockjs-client#278]
Got  exception `Uncaught SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'ws:' is not allowed.` when trying `new SockJS('ws://<my_domain>')`. *How to fix?*

**Comment by danbev** [comment]
@Volodymyr128 If you want to use ```raw``` websocket you should use the following approach: 
https://github.com/sockjs/sockjs-client#connecting-to-sockjs-without-the-client
