### ISSUE TITLE
Googlebot 404s

### ISSUE THREAD

**Issue by timothyclemansinsea** [sockjs/sockjs-client#280]
Googlebot does not handle SockJS well. I'm seeing a lot of https://ws.insideyourgovernment.com/ws/info?t=1451709948433	AJAX	Temporarily unreachable	--

**Comment by brycekahle** [comment]
Where are you seeing that? Your server logs. Googlebot should be running JavaScript just like a browser would.

**Comment by timothyclemansinsea** [comment]
Yes in my server logs.

**Comment by brycekahle** [comment]
Is that a valid URL for your sockjs server?

**Comment by timothyclemansinsea** [comment]
Yes

**Comment by brycekahle** [comment]
Are you by chance using MeteorJS? I found this http://stackoverflow.com/questions/26987190/googlebot-returns-with-ajax-temporarily-unreachable-in-meteor-js-application

**Comment by timothyclemansinsea** [comment]
No I'm using Python/Tornado

**Comment by brycekahle** [comment]
Are your sockjs URLs allowed by your `robots.txt`?

**Comment by timothyclemansinsea** [comment]
I dont have a robots.txt

**Comment by brycekahle** [comment]
That may be the source of the issue then. This library is not intended for Googlebot or other web crawlers though. I'm not going to devote any of my time to fixing issues specifically affecting crawlers. If you want to invest the time to troubleshoot, find issues with the library, and want to submit a PR I would happily accept it.
