### ISSUE TITLE
Support for Safari versions greater than 5 not mentioned in README.md

### ISSUE THREAD

**Issue by tareqak** [sockjs/sockjs-client#281]
In https://github.com/sockjs/sockjs-client#supported-transports-by-browser-html-served-from-http-or-https, it only mentions Safari 5. What about Safari versions after 5?

**Comment by brycekahle** [comment]
It looks like 5 and 5.1 utilize hixie-76, but 6+ uses standard rfc6455 for WebSocket. The other transports are likely the same. I'll update the table soon.
