### ISSUE TITLE
Find a way to stop registering a global

### ISSUE THREAD

**Issue by wraithgar** [sockjs/sockjs-client#282]
The `dbg` variable that is attached to global by this module is making other projects that require this fail testing, when leaking globals are part of their test suite.

Is there any way that variable can be either optional, or removed from globals?  I understand the reason is for aiding in console debugging but I can't help but think there's an alternative to that which doesn't require leaking globals.

**Comment by brycekahle** [comment]
If you are using the browser built minified version, it should already have that removed. If you using it within a node environment, setting `NODE_ENV` to `production` will prevent it from being registered.

I've gone ahead and removed that line as well. I found a way to enable the debug using localStorage, so I don't need the global anymore.

**Comment by wraithgar** [comment]
You're a saint, thank you so much.  The `NODE_ENV` solution wasn't going to work in our use case cause that's set to `test` during node testing.
