### ISSUE TITLE
Client Timeout errors for sockjs behind nginx

### ISSUE THREAD

**Issue by GauravRachchh** [sockjs/sockjs-client#283]
SockJS client (v1.0.0) & server uses "xhr-polling" as transport protocol. Whenever sockjs server is behind load balancer(nginx), we observe frequent  timeout error in logs. In nginx logs we observed "client prematurely closed connection" error frequently.

```
2016/01/04 16:33:37 [info] 4303#0: *17860 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: xx.xxx.xx.243, server: , request: "POST /services/server/sockjs/cobrowse/agent/517/hxzd3vdm/xhr?t=1451905561440 HTTP/1.1", upstream: "https://xx.xxx.xx.120:443/services/server/sockjs/cobrowse/agent/517/hxzd3vdm/xhr?t=1451905561440", host: "xx.xxx.xx.114", referrer: "https://xx.xxx.xx.243:8443/acs/client/main/agent/"
2016/01/04 16:33:37 [info] 4303#0: *17862 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: xx.xxx.xx.114, server: $host, request: "POST /services/server/sockjs/cobrowse/agent/517/hxzd3vdm/xhr?t=1451905561440 HTTP/1.1", upstream: "http://127.0.0.1:9080/server-3.0.0.1.0.7/sockjs/cobrowse/agent/517/hxzd3vdm/xhr?t=1451905561440", host: "xx.xxx.xx.114", referrer: "https://xx.xxx.xx.243:8443/acs/client/main/agent/"
2016/01/04 16:33:49 [info] 4303#0: *17855 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: xx.xxx.xx.243, server: , request: "POST /services/server/sockjs/cobrowse/agent/517/zxnvzbbr/xhr_streaming?t=1451905534623 HTTP/1.1", upstream: "https://xx.xxx.xx.120:443/services/server/sockjs/cobrowse/agent/517/zxnvzbbr/xhr_streaming?t=1451905534623", host: "xx.xxx.xx.114", referrer: "https://xx.xxx.xx.243:8443/acs/client/main/agent/"
2016/01/04 16:33:49 [info] 4303#0: *17853 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while reading upstream, client: xx.xxx.xx.114, server: $host, request: "POST /services/server/sockjs/cobrowse/agent/517/zxnvzbbr/xhr_streaming?t=1451905534623 HTTP/1.1", upstream: "http://127.0.0.1:9080/server-3.0.0.1.0.7/sockjs/cobrowse/agent/517/zxnvzbbr/xhr_streaming?t=1451905534623", host: "xx.xxx.xx.114", referrer: "https:/xx.xxx.xx.243:8443/acs/client/main/agent/"
2016/01/04 16:33:50 [info] 4303#0: *17864 client closed connection while waiting for request, client: xx.xxx.xx.243, server: xx.xxx.xx.114:443
```

Is there any fix available for this issue?

**Comment by brycekahle** [comment]
Do you know what version of nginx and node you are using?

**Comment by GauravRachchh** [comment]
nginx version is   nginx/1.8.0

**Comment by GauravRachchh** [comment]
Any updates 

Thanks,
Gaurav

**Comment by brycekahle** [comment]
It is difficult for me to know if this is an nginx configuration issue or actually a problem with sockjs. Do you have reproduction instructions?

**Comment by GauravRachchh** [comment]
Reproduction Steps:
1. Run 30+ sessions.
2. Server side heartbeat is 5 seconds.(we tried with changing to default 25 seconds as well)
3. Observer nginx logs.
4. Observation is timeout error occurs when content length is 0 http header
Request header
Path:/services/server/sockjs/cbserver/agent/200/jfl3nnc1/xhr_streaming?t=1452674069449                                            Time:[13/Jan/2016:14:25:42+0530]                                                                                                       
Latency:2.011ms                                                                                                                         SERVER_IP:10.133.XX.XXX:443                                                                                                              RequestHeaders                                                                                                                           Host:10.133.73.114                                                                                                                      User-agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.7 Safari/534.34                               |
Accept:*/*                                                                                                                               
Accept-Language:en-US,*                                                                                                                  Accept-Encoding:gzip                                                                                                                     Connection:Keep-Alive                                                                                                                    Origin:https://148.XXX.XXX.XXX:8443                                                                                                      Content-Type:application/x-www-form-urlencoded                                                                                           Content-Length:0

**Comment by brycekahle** [comment]
These are not sufficient reproduction steps. I need to know what SockJS server you are using. The nginx configuration, custom server code, etc. Closing until better information is given.
