### ISSUE TITLE
Dose sockjs support http2？

### ISSUE THREAD

**Issue by zhaohaifeng** [sockjs/sockjs-client#284]
My server now uses http2, and before using springmvc + sockjs + stomp, good effect, now use tls of http2, resulting in sockjs can not connect, what can I do it?

**Comment by brycekahle** [comment]
What is the specific error you run in to? I can say that supporting HTTP2 is not a big priority since that is only supported by the newest browsers which also support real WebSockets.

**Comment by FZambia** [comment]
I ran Centrifugo (https://github.com/centrifugal/centrifugo) using Go 1.6beta1 release yesterday (it has HTTP/2 built into standard library) - SockJS xhr-streaming and eventsource worked just fine. Moreover as it uses single connection to the server - there is no limit for open tabs to the same domain.

**Comment by zhaohaifeng** [comment]
I got error:"WebSocket connection to 'wss://xxxx/ws/719/fmi1p8h7/websocket' failed: Error during WebSocket handshake: Invalid status line",but websocket can work properly！
