### ISSUE TITLE
simple request->response mechanism?

### ISSUE THREAD

**Issue by gbaumgart** [sockjs/sockjs-client#286]
I guess its rather a question for StackOverflow but I will try here first: Does anyone knows a library which can do a simple JSON-RPC like mechanism with Sock-JS? I searched a lot but I can't find anything working. I was looking at the source code of the server and the client but it seems that all related methods are of the type void (send,emit) and it seems rather difficult to turn this into promises. 
well, any though is welcome.

**Comment by gbaumgart** [comment]
ok, back to socket.io then.

**Comment by brycekahle** [comment]
@gbaumgart I'm not aware of any libraries that sit directly on top of SockJS for this. You can use Primus with SockJS as the transformer, and then use the primus-responder plugin.

**Comment by gbaumgart** [comment]
nice, thank you, Bryce. I will try that.

**Comment by vitalets** [comment]
> Does anyone knows a library which can do a simple JSON-RPC like mechanism

I needed the same thing and ended up with **websocket-as-promised** library that [supports simple request-response binding](https://github.com/vitalets/websocket-as-promised#sending-requests) by `requestId`. Hope it helps!
