### ISSUE TITLE
Can I stop SockJS from trying other transports if the websocket handshake is refused?

### ISSUE THREAD

**Issue by knockoutuser** [sockjs/sockjs-client#287]
I want to limit the number of websocket connections an user can open to the server, to say 10. When a client tries to open the 11th connection I fail the handshake. But I noticed SockJs client tries to use the next transports.

I want the fallback options to be used if the client does not support websockets, but if I reject the handshake I want the SockJS client to just stop. Is there a way to do that?

**Comment by brycekahle** [comment]
I think the easiest way would be to let the connection establish, but then immediately disconnect it.
