### ISSUE TITLE
iframe popping up in new tab on connection issues.

### ISSUE THREAD

**Issue by ch3tanp** [sockjs/sockjs-client#288]
Everytime when the ActiveMQ server goes down for restart the end user gets new tab popping up(Chrome) with message **"Dont Panic! **_This is a SockJS hidden iframe. It's used for cross domain magic."_
How to prevent the pop up in new tabs?  It's annoying for user to see multiple tabs with this message.

**Comment by brycekahle** [comment]
What version of sockjs-client and Chrome?
