### ISSUE TITLE
Require sockjs failed?!

### ISSUE THREAD

**Issue by dotku** [sockjs/sockjs-client#289]
I'm new to Node.js and just studying it.

I found a package called `reload` which can help me refreash the browser once I change my code (it could help me saving the time to refresh the browser; I found similar function under meteor which is cool).

Well I use npm to install reload as the document says, and add requirejs as well (from the debug console, it is required package). Finally, the code would be:

    <script src="/lib/requirejs/require.js"></script>
    <script src="/lib/reload/reload.js"></script>

And I got a error:

> Uncaught Error: Module name "sockjs" has not been loaded yet for context: _. Use require([])

so I `npm install sockjs`, and place to the page

    <script src="/lib/requirejs/require.js"></script>
    <script src="/lib/sockjs/sockjs.js"></script>
    <script src="/lib/reload/reload.js"></script>

The error keeps the same and doesn't go away, what should I do?

**Comment by brycekahle** [comment]
SockJS is an anonymous AMD module, so you cannot include it that way. If need to, just make a small change to `sockjs.js` to give it a module id.
