### ISSUE TITLE
404 Not Found sockreload/info

### ISSUE THREAD

**Issue by alallier** [sockjs/sockjs-client#290]
GET http://localhost:3000/sockreload/info 404 (Not Found)

Using sockjs-0.3.4.js

Erroring on lines 807 and 841.

Is there enough detail here?

**Comment by alallier** [comment]
Update: Only experiencing this in chrome.

**Comment by brycekahle** [comment]
Unfortunately no. How are you creating the server? What url is it hosted on? Also, there is a much newer version of sockjs available.
