### ISSUE TITLE
a .Net Client?

### ISSUE THREAD

**Issue by Tridy** [sockjs/sockjs-client#293]
Hi.
I know I sound like I am in the wrong place but please don't shoot.

Has anyone tried implementing the communication with SockJS server from a (desktop) .Net Client with [HTTPWebRequests](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest%28v=vs.110%29.aspx) and [WebSockets](https://msdn.microsoft.com/en-us/library/system.net.websockets.websocket%28v=vs.110%29.aspx)?

Thanks

**Comment by brycekahle** [comment]
I'm not aware of one.

**Comment by tmds** [comment]
SockJS includes a url for the raw websocket protocol at /websocket.
The .NET Framework ClientWebSocket should work with that url. You need at least Windows 8 to use it. If you want an earlier version of Windows, you can use WebSocket4Net.

**Comment by Tridy** [comment]
Hi. Thanks for the reply.
about the /websocket
does it mean
if exists: _http://ebba.telldus.com:8001/ws/1/info_
then this should exist? _ws://ebba.teldus.com:8001/websocket_

I am not the owner of the SockJS server, I am trying to consume it. It has a client web page that does the call to the server via sockjs-client.

I [tried to ask on their forum](http://www.telldus.com/forum/viewtopic.php?f=22&t=5892&sid=561dd4f3b0677b69d9d972a70ce9da0a) but did not get any hints from them :(.

There is quite some logic there to reproduce in .Net, like generating session ids, setting rto and rtt and similar. I am trying to follow step by step at this point, at the same time looking into fiddler and existing JS client.

I am trying to get the basic picture and main steps required. Right now, for example, I cannot get how the session id is communicated to the server (and if it does that at all). As far as I got is calling ws/1/info and getting entropy back.  Then I am not sure what happens next.

[Fiddler Screenshot](http://s13.postimg.org/fij3lvprb/client_calls.png)

could someone give me some hints into what to look for and do as the next step?

Thanks a lot!

**Comment by tmds** [comment]
If sockjs uses http://\<url\>/info then at ws://\<url\>/websocket you will find a regular websocket.

The sockjs protocol is described here: https://github.com/sockjs/sockjs-protocol/blob/master/sockjs-protocol.py. You can find there the sections on "# Info test: `/info`" and "Raw WebSocket url: `/websocket`".

**Comment by Tridy** [comment]
Thanks for the tips,
* I can successfully retrieve 'info' via http request from <http://ebba.telldus.com:8001/ws/1/info>
* It seems like I can successfully connect to _ws://ebba.telldus.com:8001/ws/1/websocket_, however when I send a message, and then try to receive,

    * it will timeout on receiving if I just send the message in bytes
    * it will throw 'The remote party closed the WebSocket connection without completing the close handshake.' if I add 2 x 255 bytes in the end, like it is done in the python RawWebsocket test ([line 1283](https://github.com/sockjs/sockjs-protocol/blob/master/sockjs-protocol.py))

I must be doing something wrong with how i am sending and waiting for the message.

```
            [TestMethod]
            public async Task CanGetInfo()
            {
                string receivedMessage = string.Empty;

                CancellationTokenSource source = new CancellationTokenSource(TimeSpan.FromSeconds(10));
                CancellationToken token = source.Token;

                var client = new ClientWebSocket();
                Uri uri = new Uri(@"ws://ebba.telldus.com:8001/ws/1/websocket");
                try
                {
                    // connect
                    Task.WaitAll(client.ConnectAsync(uri, token));
                    Assert.AreEqual(expected: WebSocketState.Open, actual: client.State);

                    //send message
                    byte[] message = GetBytesFromString("Hello world!");
                    var arraySegment = new ArraySegment<byte>(message, 0, message.Length);
                    await client.SendAsync(arraySegment, WebSocketMessageType.Text, true, token);

                    // receive message
                    var buffer = new byte[1024];
                    WebSocketReceiveResult result = await client.ReceiveAsync(new ArraySegment<byte>(buffer), token);
                    receivedMessage = GetStringFromBytes(buffer);

                    // close
                    await client.CloseAsync(WebSocketCloseStatus.Empty, string.Empty, CancellationToken.None);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.Message);
                    receivedMessage = string.Empty;
                }

                Assert.IsTrue(receivedMessage.Length > 0);
            }

            private byte[] GetBytesFromString(string message)
            {
                var list = new List<byte>();
                byte[] bytes = Encoding.UTF8.GetBytes(message);
                list.AddRange(bytes);
                //list.Add(255);
                //list.Add(255);
                return list.ToArray();
            }

            private string GetStringFromBytes(byte[] bytes)
            {
                string result = Encoding.UTF8.GetString(bytes, 0, bytes.Length);
                return result;
            }
        }
```

Is there another test server somewhere where I could test the same functionality? Or could anyone spot what I am doing wrong?

Than

**Comment by tmds** [comment]
You don't need to add 255, 255 to the message.

Are you sure you should send "Hello world!" to the websocket and it is supposed to respond in some way? If the protocol isn't documented, you can check what the website does using your browser's 'developer tools'.

**Comment by Tridy** [comment]
Hi. I thought that sending an unknown to the server message would send the same reply back. From what you say i understand it depends on how the server is configured. I will try to track what kind of messages are sent to and from the browser and reproduce them in my tests.
Thanks!

**Comment by doronguttman** [comment]
If anyone still interested, I've created a .NET port.
Check out [SockJS.NET](https://github.com/sypbiz/SockJS.NET)
