### ISSUE TITLE
Transport based on fetch()

### ISSUE THREAD

**Issue by Type1J** [sockjs/sockjs-client#296]
I am using SockJS in environments where an embedded JavaScript interpreter is used.

I have implemented fetch() in platform specific exposed primitives, and I'd like SockJS to use that fetch() API.

If fetch is available, which at this point it will be in most browsers, then it should be used instead of an XMLHttpRequest based transport.

**Comment by brycekahle** [comment]
A PR for this would be much appreciated, but is not something that is high on my priority list.
