### ISSUE TITLE
Heartbeats and SockJS

### ISSUE THREAD

**Issue by blittle** [sockjs/sockjs-client#297]
Is SockJS currently implementing the proper heartbeat keep-alive protocol as described here: https://github.com/sockjs/sockjs-protocol/wiki/Heartbeats-and-SockJS#sockjs-040-and-later

**Comment by brycekahle** [comment]
No. It wouldn't be too difficult to add though. The hook for the `h` frame is already there: https://github.com/sockjs/sockjs-client/blob/6d4eff4f634a04b9dffa905158644c6de76cc8af/lib/main.js#L248

**Comment by blittle** [comment]
I'm confused, the documentation on that page is worded as if it has been added and that the server expects a response.  Any implementation in the client library would need to have server implementations as well in order for it to be a proper heartbeat keep-alive.

**Comment by brycekahle** [comment]
There was not a 0.4.0 release when I took over maintaining this project. All my work to get it to 1.0.0 was mostly refactoring and bugfixes and involved very little in terms of breaking changes.

You can see this existing open issue #67
