### ISSUE TITLE
Websocketdriver is not a function

### ISSUE THREAD

**Issue by sangra4l** [sockjs/sockjs-client#298]
hi,
i'm using SockJS javascript client and when i try to initialize a new socket with var socket = new SockJS(url) i get this error "Uncaught TypeError: Websocketdriver is not a function".
It doesn't seem to be any documentation regarding this error and i cannot isolate a specific case in which this beaviuor occurs becouse it doesn't present itself every time i run my code.

i'm using the latest version of sockjs.min.js but i already tried to downgrade to previous versions without success; server side i'm using a spring framework java application with sockjs and stomp libraries.
Thank you in advance for any help you can give me.

**Comment by brycekahle** [comment]
What browser are you running it in?

**Comment by sangra4l** [comment]
I'm using chrome...
