### ISSUE TITLE
Malformed request urls due to loose dependency config for url-parse

### ISSUE THREAD

**Issue by octatone** [sockjs/sockjs-client#301]
It took me a while to trace this issue down, but the long short of it is that yesterday's 1.1.0 release of `url-parse` breaks requests made by `sockjs-client` specifically `info-reciever.js`.

Request urls end up with duplicate `host:port` in the final URI string:
`http://localhost:3000/localhost:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=1459265140328-0`

Due to the fact that `url-parse` [is not locked to a version in sockjs-client](https://github.com/sockjs/sockjs-client/blob/master/package.json#L32), the update yesterday broke my local dev setup today when I reinstalled my node modules.

Workaround for anyone using npm 3 is to install the 1.0.1 release listed in sockjs-client's package.json `npm install url-parse@1.0.1`

**Comment by brycekahle** [comment]
Is this a url-parse bug, or a sockjs-client bug? If the former, we should inform them.

**Comment by octatone** [comment]
It's a bug in url-parse, I filed an issue with the dependency as well and they are working on a fix.

However, I consider it a bad practice to assume that semvers mean anything in practice and that the usage of ^ and ~ in package.json should never be used as it leads to your package breaking when a dependency pushes bugs and unintentional breaking changes.  I move to remove all ^ and ~ from your package.json to avoid this problem in the future.

**Comment by 3rd-Eden** [comment]
New version of url-parse is published, this should resolve the issue.

**Comment by brycekahle** [comment]
@octatone If you feel that way about semver, I suggest you shrinkwrap/vendor your applications. I can control the direct dependencies of sockjs-client, but not their dependencies. This makes that proposed change somewhat moot. Thanks for alerting us to the issue though.

@3rd-Eden thanks for the update.
