### ISSUE TITLE
broken package.json

### ISSUE THREAD

**Issue by wegorich** [sockjs/sockjs-client#306]
I suppose it make sense make `"main"` section `package.json`  path to be rooted to `"./dist/sockjs.js"`. The same as it done at `bower` config file.

As for me direct link to dist works fine, but when I load this module through `system.js`, I'm in trouble :(

**Comment by brycekahle** [comment]
This module can also be used from node.js, so it is not correct to point `main` to `./dist/sockjs.js`.
