### ISSUE TITLE
SockJS with NPM and SystemJS

### ISSUE THREAD

**Issue by cexbrayat** [sockjs/sockjs-client#307]
I might be missing something really obvious, but is it normal that the dist version of SockJS is not included in the NPM version ?

It would be awesome for those using NPM and SystemJS to be able to map only one main minified file in the SystemJS config.

**Comment by BlaMaeda** [comment]
I'd like this too, but it looks like they already discussed it in #265 (and it seems unlikely).

**Comment by cexbrayat** [comment]
Thank you @BlaMaeda I missed the issue.

It would be really useful, I hope @brycekahle will consider it.

**Comment by brycekahle** [comment]
I'm using npm to distribute the CommonJS module version of this library since it can be used in node.js. If you want the UMD version, I suggest using bower.

**Comment by cexbrayat** [comment]
I understand your point of view, but a lot of developers have dropped bower for NPM for front-end dev... I'm currently migrating an old project and SockJS-client is the only package among dozens I can't use with NPM.

It would be great if you considered adding the UMD version in the NPM package.
