### ISSUE TITLE
provide `undefined` to  new WebsocketDriver(this.url, undefined, options) will break the connection in Chrome

### ISSUE THREAD

**Issue by anianj** [sockjs/sockjs-client#309]
Hi, i am a webpack user,
the last commit made 3 days ago tried to pass options to WebsocketDriver,by the following code
this.ws = new WebsocketDriver(this.url, undefined, options);

but the second param `undefined` will cause a `Sec-WebSocket-Protocol:undefined` field in request header, which finally cause the connection failure in Chrome, could you check it?

**Comment by mmckeaveney** [comment]
Having the same issue.

**Comment by harboecp** [comment]
`new SockJS("url", undefined, {...})` instead of `new SockJS("url", null, {...})` solved the error for me.
See also https://github.com/sockjs/sockjs-client/issues/272#issuecomment-215996893

**Comment by brycekahle** [comment]
Does using `[]` instead of `undefined` fix the issue?

**Comment by Nifury** [comment]
@brycekahle Having the same issue when using `new SockJS(url, [])`

**Comment by canuzunoglu** [comment]
Having the same issue.

**Comment by brycekahle** [comment]
@Nifury I was suggesting using `[]` as the second argument to the `WebsocketDriver`, not `SockJS`.

**Comment by Nifury** [comment]
@brycekahle Sorry I thought they were the same. But I'm using SockJS 1.1.0, and `new SockJS(url)` will generate `Sec-WebSocket-Protocol:undefined` in request header.

**Comment by netpro2k** [comment]
:+1: also getting this. In browser `WebsocketDriver` ends up being the native `WebSocket` constructor https://developer.mozilla.org/en-US/docs/Web/API/WebSocket which only expects 2 arguments. If options needs to get passed through to faye-websocket.client additional checks will need to be added.

**Comment by brycekahle** [comment]
What version of Chrome are you using? I cannot reproduce this issue.

**Comment by brycekahle** [comment]
`1.1.1` published with a fix.
