### ISSUE TITLE
Question: 403 on Connect

### ISSUE THREAD

**Issue by benkiefer** [sockjs/sockjs-client#314]
We are seeing failures on the following requests in our application:

 /{endpoint}/{server-id}/{session-id}/xhr_send

and 

 /{endpoint}/{server-id}/{session-id}/xhr_streaming

It looks like these are from CSRF errors, and from what we can see, there is no way for us to hook in and send along the CSRF token (which is available in the page). Is there any way that you can think of for us to pass the CSRF token along in the request?

We are using SockJs with StompJs and Spring Websockets

**Comment by brycekahle** [comment]
There is not a way to send arbitrary data with each HTTP request. You could send the CSRF token over the connection itself and validate that way.

**Comment by harbulot** [comment]
@brycekahle Would it be possible to add an option to send a custom header with the Ajax requests? This would help solve this problem. (Being able to use a function for this header would also add more flexibility.)

**Comment by Vcgoyo** [comment]
same issue...about csrf

**Comment by SureshSc** [comment]
Any solution ?
