### ISSUE TITLE
Can i change sockjs-client's cdn url for hidden iframe?

### ISSUE THREAD

**Issue by karthickinnova** [sockjs/sockjs-client#318]
I'm using vertx3-eventbus-client which internally uses sockjs-client. When i was migrating my project to SSL installed environment, I'm  facing https mixed-content issue because the sock js hidden iframe's script source loads sockjs from http url. PFB

> Mixed Content: The page at 'https://myproject.com/main/' was loaded over HTTPS, but requested an insecure script 'http://cdn.sockjs.org/sockjs-0.3.4.min.js'. This request has data/user/history/iframe.html#g3b5hwyw been blocked; the content must be served over HTTPS. 

hidden Iframe code generated 

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <script>
    document.domain = document.domain;
    _sockjs_onload = function(){SockJS.bootstrap_iframe();};
  </script>
  <script src="http://cdn.sockjs.org/sockjs-0.3.4.min.js"></script>
</head>
<body>
  <h2>Don't panic!</h2>
  <p>This is a SockJS hidden iframe. It's used for cross domain magic.</p>
</body>
</html>
```

how do i change the URL or point to the local sockjs file. I have scanned all the JS files(iframe.js,iframe-bootstrap etc.,) but somehow i couldn't find the origin of URL. I'm facing this issue on production. Any help ASAP is appreciated. Thank you.

**Comment by pmlopes** [comment]
This is a vert.x config issue:

Fixed by: https://github.com/vert-x3/vertx-web/pull/415
