### ISSUE TITLE
url后会添加/info

### ISSUE THREAD

**Issue by uikoo9** [sockjs/sockjs-client#319]
你好，

之前websocket浏览器端使用的socket.io.js，但是体积太大，想换为sockjs，
1.socket.io和sockjs哪个比较好？
2.替换为sockjs后会自动在url后添加/info，这个自动添加的值可以设置吗，没有在api中找到说明

**Comment by uikoo9** [comment]
![Uploading QQ截图20160713163433.png…]()

**Comment by stiv-yakovenko** [comment]
hey, plz translate to english!

**Comment by uikoo9** [comment]
Hello,

Prior to the use of websocket browser socket.io.js, but the volume is too large, would like to change to sockjs,

1.socket.io and sockjs which is better?

2 replacement for the sockjs will automatically after the URL to add /info, the value of this automatic add can be set, not found in the API note

**Comment by uikoo9** [comment]
socket.io.js like this
http://url/socket.io/?EIO=3&transport=polling&t=LNZOxsT

sockjs like this
http://url/socket.io/info?t=1468398812626

    	 var sock = new SockJS(qiaozb.url['classapichat'] + 'socket.io');
    	 sock.onopen = function() {
    	     console.log('open');
    	 };
    	 sock.onmessage = function(e) {
    	     console.log('message', e.data);
    	 };
    	 sock.onclose = function() {
    	     console.log('close');
    	 };

**Comment by brycekahle** [comment]
The `/info` is not configurable and is part of the SockJS protocol.
