### ISSUE TITLE
not work for Chrome 52.0.2743.82 m

### ISSUE THREAD

**Issue by qinxi** [sockjs/sockjs-client#322]
use spring demo  https://spring.io/guides/gs/messaging-stomp-websocket/

chrome console log
```
Opening Web Socket...
stomp.js:145 Web Socket Opened...
stomp.js:145 >>> CONNECT
accept-version:1.1,1.0
heart-beat:10000,10000
```

` stompClient.connect({}, function(frame) {} ) ` the callback method not work

but work for chrome 51

**Comment by brycekahle** [comment]
Can you isolate the failure to something without stomp client?

**Comment by qinxi** [comment]
yep , without stomp client ,it's not work also.



work : chrome 51.0.2704.106 m (64-bit) , edge,IE 11,firefox 47.0

not work : chrome 52.0.2743.82 m, firefox 47.0.1
