### ISSUE TITLE
how to support for all protocol except websocket about SocketJS?

### ISSUE THREAD

**Issue by kervin521** [sockjs/sockjs-client#326]
websocket = new SockJS(url,transports,{devel: true, debug: true,server:"token="+token,transports: transports});

when transports is ['websocket'] , no problem.

but transports  is one of ['xdr-streaming','xhr-streaming','eventsource','iframe-eventsource','htmlfile','iframe-htmlfile','xdr-polling','xhr-polling','iframe-xhr-polling','jsonp-polling']
occur error log:
{"type":"close","bubbles":false,"cancelable":false,"timeStamp":1470392699022,"wasClean":false,"code":2000,"reason":"All transports failed"}

server use Spring WebSocket component
registry.addHandler(handler, "/websocket").setAllowedOrigins("_");
registry.addHandler(handler, "/websocket").setAllowedOrigins("_").withSockJS();

help me!

**Comment by brycekahle** [comment]
This looks like a Spring issue or how you are setting it up. Both of which I'm not familiar. Those other transports definitely work, and can be tested using the smoke test html pages in https://github.com/sockjs/sockjs-client/tree/master/tests/html

**Comment by 805728578** [comment]
IE 9:
1.socketjs-1.0.0.js  support : 'xhr-polling','xhr-polling','htmlfile'
2.socketjs-1.1.1.js  support : 'xhr-polling','xhr-polling','htmlfile','iframe-htmlfile','iframe-xhr-polling'
IE 11:
1.socketjs-1.0.0.js  not support: 'xdr-streaming','xdr-polling','iframe-eventsource','eventsource'
2.socketjs-1.1.1.js  not support: 'xdr-streaming','xdr-polling','eventsource','iframe-eventsource','iframe-htmlfile','iframe-xhr-polling'

Chrome: 
1.socketjs-1.0.0.js  not support: 'xdr-streaming','xdr-polling','htmlfile'
2.socketjs-1.1.1.js  not support: 'xdr-streaming','xdr-polling','htmlfile','iframe-eventsource','iframe-htmlfile','iframe-xhr-polling'

**Comment by 805728578** [comment]
IE 9:
 1.socketjs-1.0.0.js support : 'xhr-polling','xhr-polling','htmlfile'
 2.socketjs-1.1.1.js support : 'xhr-polling','xhr-polling','htmlfile','iframe-htmlfile','iframe-xhr-polling'
 IE 11:
 1.socketjs-1.0.0.js not support: 'xdr-streaming','xdr-polling','iframe-eventsource','eventsource'
 2.socketjs-1.1.1.js not support: 'xdr-streaming','xdr-polling','eventsource','iframe-eventsource','iframe-htmlfile','iframe-xhr-polling'

Chrome: 
 1.socketjs-1.0.0.js not support: 'xdr-streaming','xdr-polling','htmlfile'
 2.socketjs-1.1.1.js not support: 'xdr-streaming','xdr-polling','htmlfile','iframe-eventsource','iframe-htmlfile','iframe-xhr-polling'

**Comment by 805728578** [comment]
&lt;pre&gt;&lt;font color='red' &gt;&lt;b&gt;
IE 9:
 1.socketjs-1.0.0.js support : 'xhr-polling','xhr-polling','htmlfile'
 2.socketjs-1.1.1.js support : 'xhr-polling','xhr-polling','htmlfile','iframe-htmlfile','iframe-xhr-polling'
 IE 11:
 1.socketjs-1.0.0.js not support: 'xdr-streaming','xdr-polling','iframe-eventsource','eventsource'
 2.socketjs-1.1.1.js not support: 'xdr-streaming','xdr-polling','eventsource','iframe-eventsource','iframe-htmlfile','iframe-xhr-polling'
&lt;b&gt;&lt;font color='red' &gt;&lt;b&gt;&lt;pre&gt;
Chrome: 
 1.socketjs-1.0.0.js not support: 'xdr-streaming','xdr-polling','htmlfile'
 2.socketjs-1.1.1.js not support: 'xdr-streaming','xdr-polling','htmlfile','iframe-eventsource','iframe-htmlfile','iframe-xhr-polling'

**Comment by 805728578** [comment]
IE 9:
 1.socketjs-1.0.0.js support : 'xhr-polling','xhr-polling','htmlfile'
 2.socketjs-1.1.1.js support : 'xhr-polling','xhr-polling','htmlfile','iframe-htmlfile','iframe-xhr-polling'
 IE 11:
 1.socketjs-1.0.0.js not support: 'xdr-streaming','xdr-polling','iframe-eventsource','eventsource'
 2.socketjs-1.1.1.js not support: 'xdr-streaming','xdr-polling','eventsource','iframe-eventsource','iframe-htmlfile','iframe-xhr-polling'

 Chrome: 
 1.socketjs-1.0.0.js not support: 'xdr-streaming','xdr-polling','htmlfile'
 2.socketjs-1.1.1.js not support: 'xdr-streaming','xdr-polling','htmlfile','iframe-eventsource','iframe-htmlfile','iframe-xhr-polling'

**Comment by brycekahle** [comment]
Only IE will support XDR because it is a Microsoft technology. This clearly outlined in the README. I urge you to use the [mailing list](https://groups.google.com/forum/#!forum/sockjs) for technical support.
