### ISSUE TITLE
Incompatibile SockJS!

### ISSUE THREAD

**Issue by nileshprataprao** [sockjs/sockjs-client#327]
Hi ,
Lately I started getting below error almost every time. is there update or change I need to perform ?

`sockjs.min.js:2Uncaught Error: Incompatibile SockJS! Main site uses: "1.1.1", the iframe: "1.0.0". `

Thanks,

**Comment by brycekahle** [comment]
This means the version of sockjs your server is using doesn't match what the browser is loading. Change the `sockjs_url` option of https://github.com/sockjs/sockjs-node#server-class.

**Comment by nileshprataprao** [comment]
I am using  sockjs with spring  websocket framework without STOMP .I am not sure if there is a way to provide the client version in the backend . I am using  spring sample [https://spring.io/guides/gs/messaging-stomp-websocket/](url)  .  I tried to point the client lib to cdn and locally both the ways but still getting same error .

`script src="js/sockjs.min.js"
OR 
script src="http://cdn.jsdelivr.net/sockjs/1.0.0/sockjs.min.js"
/script`


still getting same error

**Comment by brycekahle** [comment]
This is because you are getting the error when it is using an iframe transport. The server serves up an HTML file that has the path to the javascript library in it. This is what is controlled by `sockjs_url` in sockjs-node. You need to find the HTML file that is being served up and change it if there is no configuration option.

**Comment by nileshprataprao** [comment]
thanks. it worked.

**Comment by jd-carroll** [comment]
@nileshprataprao I just encountered the same issue, where did you find the html file being served?

**Comment by jd-carroll** [comment]
Found it.  In your `AbstractWebSocketMessageBrokerConfigurer` the code will look something like:
```
@Override
public void registerStompEndpoints(StompEndpointRegistry registry) {
    registry.addEndpoint("/my/custom/endpoint")
        .withSockJS()
            .setClientLibraryUrl("//cdn.jsdelivr.net/sockjs/1/sockjs.min.js");
}
```

**Comment by kwlooi** [comment]
I added the following:

```
registry.addEndpoint("/stomp").withSockJS()
            .setClientLibraryUrl("//cdn.jsdelivr.net/sockjs/1.1.1/sockjs.min.js");
```

But I am still getting this error:

`
`Uncaught SecurityError: Blocked a frame with origin "http://192.168.56.102:8080" from accessing a frame with origin "http://192.168.56.102:8080". The frame requesting access set "document.domain" to "192.168.56.102", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.`
`
