### ISSUE TITLE
Simple and easy server for testing purposes (Windows binary)

### ISSUE THREAD

**Issue by jalbam** [sockjs/sockjs-client#328]
Hello,

Thanks for the library. It is great!

When I was using the client library I also had to create a server in Node.js just for testing.

Sometimes some people just do not want to install or use Node.js so I decided to share my test server at GitHub: https://github.com/jalbam/sockjs_test_server_nwjs

This simple and minimalistic test server uses NW.js and is already compiled in a self-extracting binary for 32-bit Windows. The source is included and can be modified, improved, enhanced and can be ported to any other platform as Linux or Mac OS X easily using NW.js.

I hope this can be useful for someone.

Cheers,
 Joan

**Comment by brycekahle** [comment]
@jalbam This content is probably better to be posted on the mailing list. Issues are not meant for long-running content.
