### ISSUE TITLE
StompJS Console Logging stops abruptly in IE8

### ISSUE THREAD

**Issue by Azeezullahkhan** [sockjs/sockjs-client#332]
I am trying to get a stream using SOCKJS (which connects browser and my server) and I could confirm my stream is working fine from my browser console logs(with the help of STOMPJS ). I am using IE8 browser for getting my stream , after some point of time I don't see browser console logs getting logged but I could see stream is happening properly which I could confirm from my server logs.

Sample Message getting logged in my console : LOG: <<< MESSAGE destination: xxxxx content-type:application/json;charset=UTF-8 subscription:sub-1 message-id: xxxxxx content-length:119

I could see the above message log is displayed every two minutes from my browser console but it stopped abruptly and I could see this happening only in IE8 .

Can anyone please advise me what needs to be done ? or Is there any restriction in IE 8 regarding it?

Thanks in advance

**Comment by brycekahle** [comment]
Do you have a small example app that demonstrates the issue?
