### ISSUE TITLE
Improve documentation on event arguments

### ISSUE THREAD

**Issue by achimnol** [sockjs/sockjs-client#338]
I've just noticed that `onclose()` gets error information such as "wasClean", "code", and "reason".
These information are very important when I have unexpected closing problems and check if there are errors in my server-side codes.

Unfortunately current documentation (e.g., [README](https://github.com/sockjs/sockjs-client/blob/0b4879d/README.md)) do not provide sufficient information on such event handler arguments but only [test codes do](https://github.com/sockjs/sockjs-client/blob/0b4879d/tests/lib/transports.js#L76). Documenting them would make it much friendly for application developers.

**Comment by brycekahle** [comment]
@achimnol The codes are the WebSocket standard codes.
