### ISSUE TITLE
400 / Bad Request

### ISSUE THREAD

**Issue by FakeMr** [sockjs/sockjs-client#340]
请求 URL: http://localhost:8080/zb/api/sockjs/websocket/info?t=1477143063351
   请求方法: GET
   状态码: 400 / Bad Request

Http 400  why?

**Comment by FakeMr** [comment]
'protocols_whitelist' is DEPRECATED. Use 'transports' instead.   sockjs.min.js (第 3573 行)
GET http://localhost:8080/zb/api/sockjs/websocket/info?t=1477144830428
400 Bad Request
"NetworkError: 400 Bad Request - http://localhost:8080/zb/api/sockjs/websocket/info?t=1477144830428"

**Comment by brycekahle** [comment]
Can you please include the full request and response?
