### ISSUE TITLE
url-parse@1.1.4 breaks info request

### ISSUE THREAD

**Issue by andkom** [sockjs/sockjs-client#341]
url-parse 1.1.4 changes ([commit](https://github.com/unshiftio/url-parse/commit/33f76864d49a492a1540fecb9e254bdf10610e58)) now causes double slashes in the info request:

url `http://example.com:8000` becomes `http://example.com:8000//info` and results 404

**Comment by brycekahle** [comment]
Thanks for the bug report. I see there are several releases of `url-parse` since `1.1.4`. Is this still an issue?

**Comment by 3rd-Eden** [comment]
Im pretty sure that we fixed that in the last release. Next time try to also report it at the url parse repo ;-)

**Comment by andkom** [comment]
Fixed! Thanks
