### ISSUE TITLE
Receiver continue to work after transport explicitly closed

### ISSUE THREAD

**Issue by FZambia** [sockjs/sockjs-client#342]
Hi!

This can be closely related to #308 as I first came across with a problem when reproduced infinite reconnect loop. But in my case though it was `xhr-polling` instead of `xhr-streaming`.

I supposed that it could be an error in my app so for now reduced my question to simple example.

Using [this echo example](https://github.com/sockjs/sockjs-node/tree/master/examples/echo). Here is my diff:

```diff
diff --git a/examples/echo/index.html b/examples/echo/index.html
index 4173454..7e45c28 100644
--- a/examples/echo/index.html
+++ b/examples/echo/index.html
@@ -1,7 +1,7 @@
 <!doctype html>
 <html><head>
     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
-    <script src="http://cdn.jsdelivr.net/sockjs/1.0.1/sockjs.min.js"></script>
+    <script src="http://cdn.jsdelivr.net/sockjs/1.1.1/sockjs.min.js"></script>
     <style>
       .box {
           width: 300px;
@@ -41,8 +41,8 @@
     </div>
 
     <script>
-        var sockjs_url = '/echo';
-        var sockjs = new SockJS(sockjs_url);
+        var sockjs_url = 'http://100.96.160.215:9999/echo';
+        var sockjs = new SockJS(sockjs_url, null, {"transports": ["xhr-polling"]});
         $('#first input').focus();
 
         var div  = $('#first div');
@@ -58,7 +58,7 @@
 
         sockjs.onopen    = function()  {print('[*] open', sockjs.protocol);};
         sockjs.onmessage = function(e) {print('[.] message', e.data);};
-        sockjs.onclose   = function()  {print('[*] close');};
+        sockjs.onclose   = function()  {print('[*] close'); sockjs.close();};
 
         form.submit(function() {
             print('[ ] sending', inp.val());
```

Steps to reproduce:

1) Start server on 0.0.0.0 interface
2) Use its external ip in SockJS url - in my case it's an ip given to me by wi-fi router
3) Open example
4) Turn off internet connection (turn off wi-fi)
5) Send message to chat - `close` message will be printed
6) Turn wi-fi on.

All operations must be done in less than 25 seconds

After this I expect that nothing happens after turning wi-fi on as sockjs was already closed. But xhr receiver continue to work. See this picture (close event happened right at moment when that red log line was printed, then I turned wi-fi on):

![screen shot 2016-11-17 at 15 49 22](https://cloud.githubusercontent.com/assets/1196565/20389981/8c068656-acdd-11e6-9e8e-5bfc5d0c91bf.png)

After wi-fi on chat stops working - this is normal as we closed sockjs and have not done any reconnect.

Similar behaviour for xhr-streaming - xhr streaming receiver continues to work endlessly.

In my app this results in stale browser connections I can not control.

Is this a bug?

UPD: Also reproduced infinite reconnect loop in my app using `xhr-streaming` transport, not only `xhr-polling`

**Comment by FZambia** [comment]
Looks like this fixes a problem:

```diff
diff --git a/lib/main.js b/lib/main.js
index 10b1a41..e61a6de 100644
--- a/lib/main.js
+++ b/lib/main.js
@@ -291,6 +291,7 @@ SockJS.prototype._transportClose = function(code, reason) {
   debug('_transportClose', this.transport, code, reason);
   if (this._transport) {
     this._transport.removeAllListeners();
+    this._transport.close();
     this._transport = null;
     this.transport = null;
   }
```

**Comment by FZambia** [comment]
Created pull request with this. Not sure how this affect rest of the library but it seems reasonable to close transport there. @brycekahle please could you look at this?

**Comment by brycekahle** [comment]
@FZambia Thanks for the bug report. I will take a closer look as soon as I can.

**Comment by FZambia** [comment]
@brycekahle I checked fix out yesterday, looks like all problems gone away. Thanks!!
