### ISSUE TITLE
InvalidStateError: SockJS has already been closed

### ISSUE THREAD

**Issue by lpinca** [sockjs/sockjs-client#344]
A Primus user has recently run into an issue with an [`error`](https://github.com/sockjs/sockjs-client/blob/b3c9141fb5932b48d172d317ee34307c39c3cfa9/lib/main.js#L340) thrown by the SockJS client.

After some debugging we removed Primus from the equation and found that the error is thrown when`sockjs.close()` is called soon after establishing a connection with the SockJS server.

In this [gist](https://gist.github.com/lpinca/494eff98deeef1531b734a38c0f6fe46) you can find a test case to reproduce the issue.

This is what is logged on the terminal

```
$ node server.js 
SockJS v0.3.18 bound to "/foo"
listening on *:3000
GET /foo/info?t=1479749847394 2ms 200
GET /foo/990/nyvuspip/websocket 5ms (unfinished)
POST /foo/990/5uyfzfq1/xhr_streaming?t=1479749847418 3ms (unfinished)
``` 

and this is what is logged on the browser console

![screen shot 2016-11-21 at 18 38 49](https://cloud.githubusercontent.com/assets/1443911/20493608/d7f5e5ae-b019-11e6-8b1e-8b07670f8c3e.png)

![screen shot 2016-11-21 at 18 39 54](https://cloud.githubusercontent.com/assets/1443911/20493636/f4fa3df8-b019-11e6-984a-6523aa04d82d.png)

From a quick look, it seems the last POST request in the screenshot isn't aborted when `sockjs.close()` is called.

P.S. I wasn't able to reproduce the issue in Firefox.

**Comment by lpinca** [comment]
Possible duplicate of https://github.com/sockjs/sockjs-client/issues/308.

**Comment by FZambia** [comment]
See also #342

**Comment by r0stig** [comment]
When I recreate this issue this is the debug output in Chrome:

![debug output](https://snag.gy/sfIojX.jpg "Debug output")

It looks like the close handler is being called twice since we get to the onerror-handler for the websocket object. This commit fixed the issue but I'm not sure that the correct way to fix the issue: https://github.com/r0stig/sockjs-client/commit/4cdff770c40adaa9d1ab3970014122fe0e5c8d54

**Comment by FZambia** [comment]
@r0stig hi, btw just to make things clear - the fix from #342 just does not affect this issue right? or it results in another error you showed on screenshot?

**Comment by r0stig** [comment]
@FZambia the fix in #342 make no difference in this issue, same error with or without the fix.

**Comment by lpinca** [comment]
#342 seems redundant, at least in this case, as `_transportClose` is called when the `close` event is emitted on the transport object, so the transport should be already closed.

**Comment by brycekahle** [comment]
@lpinca Thanks for the bug report. I will take a look as soon as I can.
