### ISSUE TITLE
WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by shinigami1992** [sockjs/sockjs-client#353]
Hi guys, thank you for your awesome library.

I've used sockjs-client for connecting my web app to a spring websocket web server, the problem is that when i refresh related browser page, sometimes (about 5%) this error will happen.

`WebSocket connection to 'ws://localhost:4568/ws/379/lsb17jhg/websocket?X....' failed: WebSocket is closed before the connection is established`

maybe useful to say that I didnt call disconnect or close anywhere in my code.

Thank you.

**Comment by brycekahle** [comment]
What browser? Was the WebSocket connected when you refreshed? If not, this could just be a browser warning.

**Comment by Southpaw17** [comment]
Have you tried ending the socket connection before refreshing the page?  There is a similar issue to this on the Primus Issue Tracker: https://github.com/primus/primus/issues/398

The suggested workaround there is to do the following:

`window.addEventListener("beforeunload", function (event) { primus.end(); });`

**Comment by mmobini** [comment]
@brycekahle Google Chrome on OSX. yeah when i refresh page it will connect.

@Southpaw17 Thanks for your hint. What's equivalent code in sockjs-client? Should I use Primus library to overcome this issue? 
 
Thanks.

**Comment by brycekahle** [comment]
@MajeedSan It does appear we will close the websocket on `unload` without ensuring that the `open` event has fired. https://github.com/sockjs/sockjs-client/blob/4027289acdf484ae511f6ad286761517f61419b6/lib/transport/websocket.js#L43-L46

**Comment by brycekahle** [comment]
Unfortunately we don't have any other way to stop the websocket from continuing the connection attempt (other than relying on the browser to stop it) on page unload. I think it is safe to ignore the browser warning. What do you think?

**Comment by ryanbrandenburg** [comment]
We have the same problem (though through a couple layers of indirection because we're seeing it from angular webpack) but it happens 100% of the time.

Repro steps:
1. Install a [3.0 preview of dotnet](https://dotnet.microsoft.com/download/dotnet-core/3.0).
1. `dotnet new angular`
1. `dotnet run` from within the new template.
1. Visit the page and check the console to view the warning (error on Firefox).
