### ISSUE TITLE
access-control-allow-origin header always: *

### ISSUE THREAD

**Issue by jonathanvandriessen** [sockjs/sockjs-client#357]
I have an issue with the access-control-allow-origin header in my SockJS web sockets: no matter how I set the access-control-allow-origin header, it always contains the value: *.

I use the following code:

```
const oldHttpServerListeners = WebApp.httpServer.listeners('request').slice(0);
WebApp.httpServer.removeAllListeners('request');

const newListener = function(request, response) {
  const args = arguments;

  response.setHeader('Pragma', 'no-cache');
  response.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate, private');
  response.setHeader('Content-Type', 'text/html');
  response.setHeader('X-Content-Type-Options', 'nosniff');
  response.setHeader('X-XSS-Protection', '1; mode=block');
  response.setHeader('Access-Control-Allow-Origin', null);
  response.setHeader('X-Frame-Options', 'DENY');
  response.setHeader("Access-Control-Allow-Origin", 'http://localhost:3000');

  _.each(oldHttpServerListeners, function(oldListener) {
    oldListener.apply(WebApp.httpServer, args);
  });
};
```

This snippet of code works fine for adding all other other headers to web sockets.

From what I understand, SockJS would set a value for the Access-Control-Allow-Origin to * if no value was set yet. However, it seems that SockJS overrides the value I set?

**Comment by brycekahle** [comment]
Is this issue for sockjs-node? This repo is for the browser/Node.js *client* which does not set that header.
