### ISSUE TITLE
Version 1.1.2 doesn't work with ancient Opera (eg. 11.10)

### ISSUE THREAD

**Issue by slovdahl** [sockjs/sockjs-client#359]
Opera 11.10 gives me the following error when the page with the sockjs-client script is loaded:

![error from Opera console](https://cloud.githubusercontent.com/assets/1417619/23253773/63db26f4-f9be-11e6-80ae-4899e4cf2faa.png)

I understand that Opera 11.10 is close to 6 years old, but it's still a regression from 1.1.1.

Unfortunately I don't have the skillset myself to investigate and fix this issue, any help is appreciated. Opera 11.10 can be downloaded from http://www.opera.com/download/index.dml/?ver=11.10.

**Comment by brycekahle** [comment]
Thanks for the report. I'll take a look when I can.

**Comment by brycekahle** [comment]
`1.1.4` should be fixed for you.
