### ISSUE TITLE
Client for iOS and Android App. 

### ISSUE THREAD

**Issue by Tejas-narola** [sockjs/sockjs-client#361]
Is there any client lib available for iOS and Android App ?

**Comment by FZambia** [comment]
What SockJS library do you use on server side (SockJS-node, SockJS-python....)? Some of the implementations support raw Websocket endpoint so you can just connect to your server using any Websocket library.

**Comment by Tejas-narola** [comment]
We use sockjs over stomp with spring framework .

**Comment by Tejas-narola** [comment]
Will websocket lib work for stomp with spring framework .

**Comment by brycekahle** [comment]
I'm not aware of an Objective C/Swift or Java client. In most cases, this library is best for folks connecting from a browser to a server.
