### ISSUE TITLE
sockjs for react native

### ISSUE THREAD

**Issue by Excrulon** [sockjs/sockjs-client#365]
I was looking into using stomp+sockjs in a react native project. So far, stomp seems okay. sockjs, however, has several issues. The import paths are messed up since it's for browser. For example:

Doing some weird stuff here:
https://github.com/sockjs/sockjs-client/blob/master/package.json#L7-L11

Change this line here:
https://github.com/sockjs/sockjs-client/blob/master/lib/transport/websocket.js#L6

to:
```
  , EventEmitter = require('../event/emitter')
```

And it fixes that instance. There are like 20 more of these paths to be updated (not all the same). After all those paths are fixed, I get this:

```
Object prototype may only be an Object or null.

stack:
inherits\inerits_browser.js:5
sockjs-client\lib\transport\websocket.js:59
...
```

Not sure about this one. It may have to do with crypto? No clue, really.

Any ideas? Anyone have any success getting this to work with react native?

**Comment by brycekahle** [comment]
The `require` you linked to is for Node.js. `browserify` [changes it](https://github.com/sockjs/sockjs-client/blob/master/package.json#L11) to what you posted.

You need to use the code built for the browser, which is in the `dist` folder.

**Comment by Excrulon** [comment]
Might you have any idea how I would do that? Is there a way to specify in a require or import?

**Comment by brycekahle** [comment]
`var SockJS = require('sockjs-client/dist/sockjs.js');`

**Comment by mdvacca** [comment]
Hi @Excrulon,
Did you make it work stomp+sockjs in react-native?

**Comment by binshu68** [comment]
I am also curious if stomp+sockjs works in react-native. Feedback is highly appreciated.

**Comment by Excrulon** [comment]
Nope, doesn't work out of the box. Gave up bothering.

**Comment by PavelJ** [comment]
Since this is first match on Goggle for things related to SockJS and React Native - version 1.1.4 works using following small fix in this fork: https://github.com/datso/sockjs-client/commit/34150437996b9f5ad169b60e638fe50f8608d724 .

**Comment by Junam** [comment]
@PavelJ Thanks for that comment, I was digging for many hours to find a solution to react-native and stomp over websocket, the small fix you mentions worked like a charm, I am able now to send message from web client to android app, will test to reverse flow soon.

**Comment by fuj1w4r4** [comment]
Hi guys,

I managed to run it in react-native. My backend is using spring boot. But here is the problem, the initialization of sockjs is not stable but sometimes it works.

Whoops! Lost connection to <the url>

Anyone here have such experience?

Please help.

**Comment by Malikkhoja** [comment]
Facing Same issue as @fuj1w4r4

**Comment by StefanoMartella** [comment]
Same issue here

**Comment by StefanoMartella** [comment]
Same as @fuj1w4r4, in my case the problem was that I was using `http://localhost:8080/chat` as websocket url; since I'm on an Android emulator I had to use `http://10.0.2.2:8080/chat` instead. More details here:
https://stackoverflow.com/a/5495789/9121838
