### ISSUE TITLE
SockJS AMD support issue

### ISSUE THREAD

**Issue by UltraNemesis** [sockjs/sockjs-client#366]
I am facing problems loading SockJS in my JS framework which is organized as AMD modules that are loaded using require.js.  

I need to load it as a dependency in my own unnamed (anonymous) AMD module. The module file looks something like below.

```
define(
	// Module Dependencies
	[
		'lib/SockJS/sockjs'
	],
	function(SockJS) {
		// Do something with sockjs.
	}
)
```

Ultimately, these modules are combined using r.js into a single file which is then used in the applications
 
Earlier versions of sockjs (0.3.x) used to be plain js file and I had no problem getting it to work in my project. But the latest versions seem to be built using browerify which I guess is causing the problem. I also tried running the file through browerify-umdify to generate an UMD, but that is also not helping me.

**Comment by brycekahle** [comment]
We already package as a UMD, so you should not have to do that.
