### ISSUE TITLE
SockJS keeps connections open and creates new at page refresh

### ISSUE THREAD

**Issue by wardloockx** [sockjs/sockjs-client#370]
Hi,

I'm having an issue with duplicate connections. When I connect and refresh the browser page the conn close event handler is called multiple times (+1 for every page refresh).

So what's the best approach to close connections? When a user refreshes the page, should he re-use the connection or not? 

I was expecting that calling close() or end() on the connection object (on server side close handle) would kill the connection, but looks like this is not true.

Anyone that can help me out on this?

```
this.channelConnection.on('connection', function(conn) {

        console.log('Channel: Connection ' + conn.conn.id);

        //Push the current video
        that.clients[conn.conn.id] = {connection: conn};

        that.emit('connectionCreated', conn.conn.id);

        conn.on('close', function () {
            console.log('Close connection ' + conn.conn.id);
            conn.conn.close();
            //conn.conn.disconnect();
            delete that.clients[conn.conn.id];
            that.emit('connectionClosed', conn.conn.id);
        });

        conn.on('data', function (msg) {
            console.log('Received data from ' + conn.conn.id);
            that.emit('dataReceived', {connection_id: conn.conn.id, data: JSON.parse(msg)});
         });


    });
```
This is the output from my script

> SockJS v0.3.18 bound to "/party"
> ChannelManager: Creating channel video
> GET /party/info?t=1491504541191 2ms 200
> GET /party/708/04bap4um/websocket 2ms (unfinished)
> Channel: Connection 3d088196-6ef5-44b5-84be-dde6938378ad
> new video loaded
> 305
> 304
> 303
> 302
> 301
> Close connection 3d088196-6ef5-44b5-84be-dde6938378ad
> GET /party/info?t=1491504547458 1ms 200
> GET /party/001/nuqjme3k/websocket 1ms (unfinished)
> Channel: Connection fa27e629-825f-4c59-8e34-54fbd28bbae9
> sending current video to fa27e629-825f-4c59-8e34-54fbd28bbae9
> 300
> 299
> 298
> 297
> 296
> 295
> 294
> Close connection 3d088196-6ef5-44b5-84be-dde6938378ad
> Close connection fa27e629-825f-4c59-8e34-54fbd28bbae9
> GET /party/info?t=1491504554582 0ms 200
> GET /party/548/fexfqlr0/websocket 0ms (unfinished)
> Channel: Connection bfde9c6f-5134-4c11-ac77-085fbaacb757
> sending current video to bfde9c6f-5134-4c11-ac77-085fbaacb757
> 293
> 292
> Close connection 3d088196-6ef5-44b5-84be-dde6938378ad
> Close connection fa27e629-825f-4c59-8e34-54fbd28bbae9
> Close connection bfde9c6f-5134-4c11-ac77-085fbaacb757
> GET /party/info?t=1491504556527 0ms 200
> GET /party/256/rlqhm4mz/websocket 0ms (unfinished)
> Channel: Connection e115308c-ecda-487a-a743-4376b0634e86
> sending current video to e115308c-ecda-487a-a743-4376b0634e86
> 291
> 290
> 289

You can clearly see that after each browser refresh a new connection is made + the server side close handler is triggered for every old connection. 

The problem in my case is that when I send something from my client to the server (after a few page refreshes), all messages are duplicated (because there are multiple connections open).

**Comment by brycekahle** [comment]
This sounds more like a server bug in sockjs-node where it is emitting `close` events multiple times. Can you move this issue over there with good repro steps? Thanks!
