### ISSUE TITLE
SockJsTransportFailureException

### ISSUE THREAD

**Issue by PrasanthTJ** [sockjs/sockjs-client#374]
Receiving the below error whenever client is trying to subscribe to my server for the first time and in very few seconds it is trying for the second time, which results in successful connection. This happens for every user.

I'm using this as I have very frequent updates from my server to client.

Sockjs version - 1.1.1

INFO  [stdout] ERROR 4820 --- [32.3.97:8080-10] o.s.boot.context.web.ErrorPageFilter     : Forwarding to error page from request [/websocket/test/895/hhbovijb/websocket] due to exception [Uncaught failure in SockJS request,  nested exception is org.springframework.web.socket.sockjs.SockJsTransportFailureException: WebSocket handshake failure; nested exception is java.lang.IllegalAr
gumentException: No 'javax.websocket.server.ServerContainer' ServletContext attribute. Are you running in a Servlet container that supports JSR-356?]

**Comment by brycekahle** [comment]
This is clearly a server-side Java exception. This project is for the JavaScript client.
