### ISSUE TITLE
Upgrading process

### ISSUE THREAD

**Issue by Andarist** [sockjs/sockjs-client#375]
Hey,
we are considering switching to the SockJS from the engine.io and I was wondering if built-in upgrade process is something in the scope of the SockJS or lack of it is a design decision and won't be ever supported?

**Comment by brycekahle** [comment]
That sounds out of scope. SockJS is meant to be just be WebSocket emulation for platforms/environments that cannot support them.

**Comment by brycekahle** [comment]
I think I misunderstood your original question. SockJS uses a downgrade process. It will first try WebSocket and then downgrade to other transports if that does not work.

**Comment by brycekahle** [comment]
> Under the hood SockJS tries to use native WebSockets first. If that fails it can use a variety of browser-specific transport protocols and presents them through WebSocket-like abstractions.

Extracted from the README.
