### ISSUE TITLE
client disconnected after heat-beat time passed in react-native

### ISSUE THREAD

**Issue by mmobini** [sockjs/sockjs-client#377]
I've a web application which its client side is written using _sockjs-client_ and _stomp_ and it's working fine in browser.

Now I'm trying to develop a mobile application using react-native but I've a problem:
About 40 seconds (my heart beat time is also 40s) after connecting to the server, I get following error:

`Whoops! Lost connection to ..`

**Comment by mmobini** [comment]
I have find out the reason of this issue which is related to stompjs library. (check [this issue](https://github.com/jmesnil/stomp-websocket/issues/133) in stompjs)

**Comment by Malikkhoja** [comment]
+1
