### ISSUE TITLE
How to use wss instead of ws when using https

### ISSUE THREAD

**Issue by Lexanius** [sockjs/sockjs-client#379]
Hi

when using sockjs the client try to use ws instead of wss and after this it is fallback to xhr.
```
XHR finished loading: GET "http://127.0.0.1:8100/ws/info?t=1494413418627".
WebSocket connection to 'ws://127.0.0.1:8100/ws/166/l0nwezo5/websocket' failed: Connection closed before receiving a handshake response
XHR finished loading: POST "http://127.0.0.1:8100/ws/166/egcbr14a/xhr_send?t=1494413418764".
```
I test the connection with a connection via wss only and it work. but sockjs cant use it.
There was no XHR messages in the log.
When i use `const socket: WebSocket = new SockJS(url, void 0, {transport: ["wss", "https"]}) as WebSocket;` it cannot create a connection.

Do i understand the system right, is it using secure websockets? How can i force it to use secure websocket?

Lexanius

**Comment by brycekahle** [comment]
If you use `https` for SockJS URL, it will use `wss`.

**Comment by ijazm123** [comment]
how can I encrypt websocket protocol without using ssl/tls? Will wss work over http?
