### ISSUE TITLE
NodeJS Application creates new processes of itself

### ISSUE THREAD

**Issue by ipa-big** [sockjs/sockjs-client#383]
We are using sockjs-client in a nodeJS application to setup a websocket connection on a redhat based virtual machine. Unfortunatelly, the application starts new processes of itself after a period of time and interferres the original connection (there is only one connection supposed to be at a time). 

If I do "ps aux | grep node" multiple processes show up. 

![pasted image at 2017_06_09 11_09 am](https://user-images.githubusercontent.com/18415320/27025418-b67bb760-4f5a-11e7-9aa6-0726e5314901.png)

(I edited the image a little to show just the important stuff...)

**Comment by brycekahle** [comment]
There is no code in this project that would fork/create processes. I would search your application code.
