### ISSUE TITLE
why it makes call over cdn

### ISSUE THREAD

**Issue by shreychaturvedi123** [sockjs/sockjs-client#384]
cdn.jsdelivr.net/sockjs/1.0.1/sockjs.min.js

In sock.js file on line 181 , why it is making call to cdn , and why it can't require this file in bundle?

**Comment by brycekahle** [comment]
I'm not seeing the line you are referencing. Can you include a GitHub link to it?

**Comment by dlangerenken** [comment]
Seems like this is done through a dev-dependency:
"sockjs": "^0.3.17"
which calls https://cdn.jsdelivr.net/sockjs/1.0.1/sockjs.min.js

**Comment by dlangerenken** [comment]
I found a solution for my problem, maybe it relates to @shreychaturvedi123's problem:
https://github.com/sockjs/sockjs-client/issues/327

Basically, if you're using Spring and a SockJS Server, you would need to set the client-library url to the correct path, e.g. mine is: 

     .setClientLibraryUrl("https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.1.4/sockjs.min.js");

**Comment by jimaek** [comment]
jsDelivr also has the latest version as it pulls files directly from npm

https://cdn.jsdelivr.net/npm/sockjs-client@1.1.4/dist/sockjs.min.js
https://cdn.jsdelivr.net/npm/sockjs-client/

**Comment by brycekahle** [comment]
@dlangerenken The dev dependencies do not end up in the bundled js.

You are correct that you need to configure your server to load a version of the SockJS client in an iframe that matches what you are loading in the browser. This is very clear in the [documentation for sockjs-node](https://github.com/sockjs/sockjs-node#server-class) but I don't control the docs for Spring.
