### ISSUE TITLE
Incompatibile SockJS! Main site uses: "1.1.4", the iframe: "1.0.0"

### ISSUE THREAD

**Issue by BustyLoli-Chan** [sockjs/sockjs-client#388]
I am constantly getting this issue while trying to use sockjs-client with Waterfox 54.0.0.1 (64-bit)
I've noticed that there is an iframe.html that gets downloaded in the network tab that says 
```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <script>
    document.domain = document.domain;
    _sockjs_onload = function(){SockJS.bootstrap_iframe();};
  </script>
  <script src="https://cdn.jsdelivr.net/sockjs/1.0.0/sockjs.min.js"></script>
</head>
<body>
  <h2>Don't panic!</h2>
  <p>This is a SockJS hidden iframe. It's used for cross domain magic.</p>
</body>
</html>
```
And accordingly I do end up downloading `https://cdn.jsdelivr.net/sockjs/1.0.0/sockjs.min.js`
I've noticed however that the included version of sockJS that is bundled is version 1.1.4 and I believe this is what is causing my version mismatch error. 

I believe this is an issue that may need to be fixed, although personally I am not quite sure how to fix it. It could also be that I myself am doing something wrong. If you could offer me any insight on this issue I would be extremely grateful!

**Comment by brycekahle** [comment]
The version used in the iframe is a server setting. What server are you using?

**Comment by BustyLoli-Chan** [comment]
We are using some form of Tomcat, with Spring bolted on top. 
Where would I configure this setting?

**Comment by brycekahle** [comment]
Whatever is acting as the actual SockJS server would have the setting. The iframe is served by the SockJS server, so it controls the content including the URL to the SockJS library.

**Comment by BustyLoli-Chan** [comment]
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-fallback-xhr-vs-iframe 
I think I managed to find the page here...
It's most likely falling back to a default cdn using sockJS version 1.0.0

I do wonder why it's falling back to iframe to begin with though. I am esentially using firefox, and I even get this error frequently in chrome. Nobody else on my dev team seems to have issue however.

**Comment by BustyLoli-Chan** [comment]
Alright so I did fix that issue, but I also discovered that JSONP fails and it seems like xhr `htmlfile?` requests also fail. Do you know anything about what might be causing this or how to configure these in spring? I can't find any documentation about it anywhere.

**Comment by brycekahle** [comment]
I will need more information about the failures. If you can get browser javascript console and request logs, that will help. Please open a new issue with that information.

**Comment by rstoyanchev** [comment]
This could be related to CORS if you're [restricting origins](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/socket/config/annotation/StompWebSocketEndpointRegistration.html#setAllowedOrigins-java.lang.String...-). If you turn up logging on the org.springframework.web.socket.sockjs package you'll get indication of that.

**Comment by jamesjieye** [comment]
I had this issue with Spring WebSocket. I put the Spring behind Nginx server. All requests through Nginx. I added the following to port `80`.

```
location / {
    proxy_pass http://localhost:8080;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
}
```
And in the server log, it showed: `Handshake failed due to invalid Upgrade header: null`. This is because the upgrade header is not passed from Nginx to Spring. 

To fix this, change the setting to the following:


```
location / {
    proxy_pass http://localhost:8080;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;

    # For WebSocket upgrade header
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

**Comment by maanasa** [comment]
I have the exact same issue which the OP has. I am using Internet explorer 11.0.60
There is an iframe getting downloaded with exact same message -
```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <script>
    document.domain = document.domain;
    _sockjs_onload = function(){SockJS.bootstrap_iframe();};
  </script>
  <script src="https://cdn.jsdelivr.net/sockjs/1.0.0/sockjs.min.js"></script>
</head>
<body>
  <h2>Don't panic!</h2>
  <p>This is a SockJS hidden iframe. It's used for cross domain magic.</p>
</body>
</html>
```

Whereas I have specified Sockjs version to be 1.1.4

fallback happens to xhr streaming which does not succeed and continuous retries.

@TheeRFG how did you fix this? The link you specified - https://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-fallback-xhr-vs-iframe takes me to general spring docuemtnation of websockets.

**Comment by demonfchan** [comment]
`registry.addEndpoint("/portfolio").withSockJS().setClientLibraryUrl("http://localhost:8080/myapp/js/sockjs-client.js");
`
@maanasa configure like this at spring

**Comment by TakiRahal** [comment]
Same probleme:
[
![Screenshot from 2019-05-01 18-37-35](https://user-images.githubusercontent.com/14108577/57031700-4ef69380-6c40-11e9-979f-63292009d32f.png)
![Screenshot from 2019-05-01 18-37-57](https://user-images.githubusercontent.com/14108577/57031701-4ef69380-6c40-11e9-9131-2e5534728ee6.png)

](url)
