### ISSUE TITLE
IE9 certificate based login causes xhr requests to be aborted?

### ISSUE THREAD

**Issue by zthomas1** [sockjs/sockjs-client#392]
In IE9 when the page is cert based login, the xhr_streaming requests get aborted by IE9.  Any thoughts would be appreciated.

**Comment by brycekahle** [comment]
Can you provide more details on "cert based login"? Steps to reproduce would be helpful.

**Comment by brycekahle** [comment]
You are correct about the Origin header. You cannot combine `Access-Control-Allow-Origin: *` and `Access-Control-Allow-Credentials: true`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Credentialed_requests_and_wildcards

**Comment by zthomas1** [comment]
One last thing if I may, is there a way to hack the sockjs file to force it withcredentials for testing?  I’m on 0.3.4
Thank you, and you rock.

-Zach

**Comment by brycekahle** [comment]
Host your own version of the file and manually edit it. 😄

**Comment by zthomas1** [comment]
Access-Control-Allow-Origin is now set  and requests are still being aborted by IE9

this is all same-domain requests.
