### ISSUE TITLE
Cannot connect to the server, return 500

### ISSUE THREAD

**Issue by firejq** [sockjs/sockjs-client#394]
I use sockJS with spring websocket.

server configure:
```Java
@Override
public void registerWebSocketHandlers(WebSocketHandlerRegistry webSocketHandlerRegistry) {
	webSocketHandlerRegistry.addHandler(recordHandle(), "/recordHandle")
		.addInterceptors(new RecordHandshake()).setAllowedOrigins("*");

	webSocketHandlerRegistry.addHandler(recordHandle(), "/recordHandle/sockjs")
		.addInterceptors(new RecordHandshake()).setAllowedOrigins("*").withSockJS()
		.setClientLibraryUrl("//cdn.bootcss.com/sockjs-client/1.1.4/sockjs.min.js");
}
```

client:
```JavaScript
var websocket = new SockJS("http://127.0.0.1:8080/recordHandle/sockjs");
```

But I cannot connect to the server. These are the error in the Chrome:
![image](https://user-images.githubusercontent.com/14916943/28622035-9efe1228-7245-11e7-989a-38a2446df521.png)

I do not know why and how to solve.

**Comment by theshying** [comment]
我也遇到了这个问题，你是怎么解决的啊？

**Comment by brycekahle** [comment]
If you are getting 500s, you need to examine your server logs to find out what the error is. This is not a js client issue.
