### ISSUE TITLE
location.procotol include final ":", and 2 line miss it

### ISSUE THREAD

**Issue by SenYu** [sockjs/sockjs-client#395]
from MDN: 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/protocol

in html, `protocol` is usually equal to `https:`, `http:`, `file:` and so on.

but I found in `https://github.com/sockjs/sockjs-client/blob/master/lib/main.js#L78`

```javascript
if (loc.protocol === 'https' && !secure) {
    throw new Error('SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS');
  }
```
where the final ":" is missed

**Comment by SenYu** [comment]
when you visit a page with `https` protocol , and try to connect a websocket with `http` protocol. it just emit a error, and no useful error message.

after debugger, it is caused by above condition.....

**Comment by brycekahle** [comment]
Fixed in https://github.com/sockjs/sockjs-client/pull/396
