### ISSUE TITLE
Can react-native use it?

### ISSUE THREAD

**Issue by QuYunFengg** [sockjs/sockjs-client#398]
![image](https://user-images.githubusercontent.com/29081440/28917623-d9fa1906-7878-11e7-9d0d-9faa03cccbcb.png)

**Comment by shamas** [comment]
On react-web stack one of the fallback methods recursively cause the entire VM to fork off and restart, duplicating infinitely. I think some of "the fallbacks" won't play nicely.

**Comment by prsn** [comment]
I have used this library for my react-native app. I was able to receive notification on iOS simulator but when tested it on android device I got issue with `Networking.sendRequest()` method.

I forked it and made the required changes to run over Android device. 
Here is the link to that forked: 
https://github.com/prsn/sockjs-client

**Comment by olegdizus** [comment]
@prsn Can you make PR? Your solution helps me too.

**Comment by prsn** [comment]
@olegdizus ,
Good to hear that it helped you. Surely will create PR for this.
Sorry for the delay response, I didn't see the notification :) .
