### ISSUE TITLE
xhr_streaming

### ISSUE THREAD

**Issue by ghost** [sockjs/sockjs-client#400]
I have application that write with spring websocket and using sockjs in client
in some browser sockjs dose not connect and after request /websocket change request  to /xhr_streaming
i dont know why dose not connect and why request to this url?
is websocket is relate to network or antivirus?

**Comment by azizkhani** [comment]
+1

**Comment by brycekahle** [comment]
@azizkhani It is likely related to the network between the client and your server. The entire point of this library is to fallback to non-websocket transports when websockets are not available/working. If you want to know the precise reason why websockets did not work in your case, you will need to gather more details.

**Comment by azizkhani** [comment]
@brycekahle  how can gather more details of network problem ?
why in some client work and in some client dose not work?

**Comment by yairGit** [comment]
Hi,

i have experienced connection closed on slow networks with similar issue.
i modified the rtt value in the lib and it solved it for me but it is a "dirty" solution.

the change to  /xhr_streaming is a default sock js behavior that he is trying other transport protocols.

**Comment by brycekahle** [comment]
> why in some client work and in some client dose not work

This is the very nature of a network issue. Some client's networks will allow websockets, others will not.

**Comment by brycekahle** [comment]
Closing this issue because falling back to other transports is expected/desired behavior.
