### ISSUE TITLE
issue with reverse proxy

### ISSUE THREAD

**Issue by okaiyong** [sockjs/sockjs-client#402]
I am using Spring for backend websockets and stomp over sockjs for front end. 
I have reverse proxy infront of my app server which is tomcat v7. 

We do not have any issue of having websocket connections when client hit tomcat directly. 
When web proxy is in placed, the websocket connection is ok with IE11 browser but not on chrome or FF.
It always fail to XHR streaming, polling and fail consistently. Any way to inrease the timeout  or any advice what is the root issue?

**Comment by brycekahle** [comment]
Since you state the issue only arises when you put your proxy in place, it is clear that is where the issue is. Unfortunately, I do not have the time to help you debug issues that are not caused by SockJS.
