### ISSUE TITLE
Transport timeout too short cause Transport close..

### ISSUE THREAD

**Issue by binlaniua** [sockjs/sockjs-client#403]
## my connect code
```javascript
var socket;
if (that.isIE9()) {
	socket =  new SockJS(url)
} else {
	socket =  new SockJS(url, null, {transports:'websocket'})
}

```

## i found code at  "SockJS.prototype._connect"

```javascript
var timeoutMs = (this._rto * Transport.roundTrips) || 5000;
this._transportTimeoutId = setTimeout(this._transportTimeout.bind(this), timeoutMs);
```

## i log the timeoutMs  is 698
![image](https://user-images.githubusercontent.com/5960462/29676447-af80be56-892a-11e7-9d1d-578f31106ad3.png)

**Comment by binlaniua** [comment]
i set transport {transport: 'websocket'}

**Comment by antonselukh** [comment]
Let's see if this pull request solves the issue. I had similar client issues

**Comment by dazraf** [comment]
Hi, are the PR 412 and 413 sufficient to close this issue and release this feature in the next release please? thanks.

**Comment by chrislhardin** [comment]
1.3.0 doesn't have the transport timeout configuration feature. Is there a beta release or do I just need to build my own until it gets released? The current calculated timeout is way too short for my app.

**Comment by brycekahle** [comment]
@chrislhardin The referenced PR #413 has not been merged, thus it is not in master yet.
