### ISSUE TITLE
Invalid frame header error

### ISSUE THREAD

**Issue by kirankashalkar** [sockjs/sockjs-client#406]
With Chrome 60.0.3112.101 on Mac OSX, I see the following error:

```
WebSocket connection to 'wss://<fqdn>/multiplex/174/234doqh5/websocket' failed: Invalid frame header
```

This is with the sample code provided at https://github.com/sockjs/websocket-multiplex/blob/master/examples/sockjs/index.html

My server is Node 8.5 with Express 4.

I see a similar issue on Firefox 55 as well:
```
The connection to wss://<fqdn>/multiplex/891/culiunjj/websocket was interrupted while the page was loading.
```

**Comment by brycekahle** [comment]
This sounds like a network issue. Somehow the websocket frame is getting corrupted.
