### ISSUE TITLE
eventsource dependency too old: 0.1.6

### ISSUE THREAD

**Issue by christophercr** [sockjs/sockjs-client#407]
Hi, I just noticed that this library (used by webpack-dev-server btw) has a dependency to eventsource with a very old version: 0.1.6 ([released in Feb 2015](https://github.com/EventSource/eventsource/releases?after=v0.2.0)!).

I'm wondering why hasn't this been upgraded to a more recent version or even the latest one. It seems that there has been a lot of [bugs/issues fixed since version 0.1.6](https://github.com/EventSource/eventsource/blob/master/HISTORY.md) ;)

I noticed this since I'm implementing Server Sent Events in my app and I spotted two deps of the eventsource library in my package-lock.json. I use the latest version but I see that webpack-dev-server=>sockjs-client uses a very old one.

I thought this could be interesting for you...

**Comment by brycekahle** [comment]
@christophercr I was waiting for https://github.com/EventSource/eventsource/issues/60 to be fixed.  It is also work to ensure the changes they made do not break SockJS (again).

**Comment by christophercr** [comment]
Oh I see, well it seems it is solved now :)
