### ISSUE TITLE
Uncaught Error: Incompatibile SockJS! Main site uses: "1.1.4", the iframe: "1.0.0".

### ISSUE THREAD

**Issue by zq99299** [sockjs/sockjs-client#409]
Uncaught Error: Incompatibile SockJS! Main site uses: "1.1.4", the iframe: "1.0.0".

在spring4.2.3中使用，js使用sockjs-client 1.1.4 提示以上错误，但是npm仓库中并没有 sockjs-client 1.0.0 的的版本

In the use of spring4.2.3, js use sockjs-client 1.1.4 suggested above mistakes, but npm warehouse and no sockjs-client 1.0.0

**Comment by zq99299** [comment]
我在服务器中设置了 
I set it up in the server
```java
        registry.addHandler(new MyHandler(), "/api/myHandler").setAllowedOrigins("*")
//                .addInterceptors(new HttpSessionHandshakeInterceptor())
                .withSockJS()
                .setClientLibraryUrl("//cdn.jsdelivr.net/sockjs/1/sockjs.min.js");
```
可以链接了，但是刚链接上就断开了
Can be connected, but just connected to disconnect
```java
WebSocket connection to 'ws://localhost:9105/api/myHandler/229/a00f0zin/websocket' failed: Connection closed before receiving a handshake response
```

**Comment by brycekahle** [comment]
You need to change the `sockjs_url` parameter when creating the server to match the version you are serving on the front end.
