### ISSUE TITLE
Veracode violation CWE ID 80 reported in sockjs version 0.3.4

### ISSUE THREAD

**Issue by sohonisaurabh** [sockjs/sockjs-client#415]
Hi,

I am using sockjs on wrapped inside AngularJS 1.x to implement web socket communication. For every production deployment, Veracode static scan is run on the codebase to detect potential security violations in JS files.

In a recent scan, Veracode reported the violation given below:

![veracode-xss-cweid80](https://user-images.githubusercontent.com/20185422/33647005-a594ba24-da78-11e7-8b04-3241efc976da.png)

The exact line of code where the violation is reported is given below:

![sockjs-veracode-violation](https://user-images.githubusercontent.com/20185422/33647033-d7c32b98-da78-11e7-899f-ef99277b177b.png)

From my initial analysis, sanitizing the input would fix this issue.

Can someone help me with the correct fix?

Thanks,
Saurabh

**Comment by brycekahle** [comment]
Thanks for reporting this, but I do not believe a real XSS vulnerability exists here. It is generally accepted that you escape/sanitize when rendering into the DOM (as [OWASP recommends](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.231_-_HTML_Escape_Before_Inserting_Untrusted_Data_into_HTML_Element_Content)). SockJS is not doing that anywhere in the library. In the same way it would be incorrect to escape/sanitize in the browser provided WebSocket object, it is incorrect to do so in SockJS.

If you are worried about protecting your application, I suggest reading the linked OWASP guidelines for XSS. In a rough sense, you should escape/sanitize any user provided data if it will end up rendered on the page.

Hope that helps!

**Comment by sohonisaurabh** [comment]
Hi @brycekahle,
 You are right, only if the data is rendered on the page, then there is a risk. I was not sure of this as Veracode listed it as a vulnerability, hence confirmed.

Thanks
