### ISSUE TITLE
SockJS connection rejected because of CORS rules

### ISSUE THREAD

**Issue by ycordier-pro** [sockjs/sockjs-client#416]
In XHR default client, the "withCredentials" is set to true by default: 
https://github.com/sockjs/sockjs-client/blob/a1028ed46db22e0f98d5529c0828529a8521ca6f/lib/transport/browser/abstract-xhr.js#L75

The comment above says:
```
// Mozilla docs says https://developer.mozilla.org/en/XMLHttpRequest :
// "This never affects same-site requests."

```
but in fact, the Mozilla doc doesn't say this anymore...

And this seems to be causing some issues when running SockJS client from a static HTML page served from the local file system (URL with file://) or when used within a mobile webview object , because the "Origin" header set by the majority of browsers is "null" (tested on Safari, Chrome and Firefox).

This leads to the following error when SockJS tries to connect thru websocket transport and first wants to get the "info" for the websocket connection :

```
Failed to load [xxxx__removed__xxxx]/eventbus/info?t=1513268107382: 
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'null' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

On server side we must keep '*' as the Access-Control-Allow-Origin because the connection must be kept opened to any incoming domain.

Commenting out line 75 of abstract-xhr transport resolves the issue, and SockJS still works fine in a "normal" context (when the page using SockJS is served on a standard web server thru http or https).

I'm wondering whether this can be completely removed, or whether something can be done to set the XHR withCredentials parameter from SockJS options or any transport options ?

Thanks for your feedback!

**Comment by brycekahle** [comment]
What server (and version) are you running?

**Comment by ycordier-pro** [comment]
I'm using Vert.X 3.5.1 with embedded SockJS event bus bridge.
On client side we have sockjs client v1.1.2 which is served by the same domain from which we load the page initiating the sock JS client connection.

Did something change on this XHR withCredentials option from the time I submitted this question ?
Thanks for your reply :)

**Comment by brycekahle** [comment]
Can you include a full response? Regardless though, this is a server problem if it is responding with the incorrect headers.
