### ISSUE TITLE
infinite loop of xhr_streaming traffic c[3000, "Go away!"]

### ISSUE THREAD

**Issue by NaorHai** [sockjs/sockjs-client#418]
we are using sockjs-client version 1.1.2.
our backend written in java with spring 4

the socket is working and delivering all our messages but chrome page crashes after several minutes.
we are encountering a batch of  xhr_streaming traffic c[3000, "Go away!"] and it looks like this is the sourse of the failure:
![image](https://user-images.githubusercontent.com/18754684/35320082-3d1cd82a-00eb-11e8-8221-fb98d84bdb20.png)

we've tried the following:
1. upgrade sockjs from 1.1.0 -> 1.1.2
2.  used this workaround: 
if (!self.pollIsClosing) { self.emit('close', code || 1006, reason); self.removeAllListeners(); }
without success
3. changed the protocols order and combinatios
4. followed the steps that you've mentioned in this thread:
https://github.com/sockjs/sockjs-client/issues/308

please advise

**Comment by FZambia** [comment]
@NaorHai there was another issue discussed in #334 and the fixed for it was merged after 1.1.2 was released (in this commit eef1957a4d8007a64e170a4bbb2c635e40d870b2). So you can try SockJS v1.1.4 and hopefully the problem will be solved.

**Comment by NaorHai** [comment]
@FZambia 10x for the quick response.
I didn't know 1.1.4 was released
I'll try to upgrade my version and update if it solved the issue.

**Comment by NaorHai** [comment]
Hi @FZambia I've modified this code and found a workaround, so I m not getting these "go away" errors anymore:

        function XhrReceiver(url, AjaxObject) {
            debug(url);
            EventEmitter.call(this);
            var self = this;

            this.bufferPosition = 0;
            var code = null;
            this.xo = new AjaxObject('POST', url, null);
            this.xo.on('chunk', this._chunkHandler.bind(this));
            this.xo.once('finish', function(status, text) {
                debug('finish', status, text);
// check if we got an go away error
                if (text.indexOf('3000') > -1 && text.indexOf('Go away!') > -1) {
                    code = 3000;
                }
                self._chunkHandler(status, text);
                self.xo = null;
                var reason = status === 200 ? 'network' : 'permanent';
                debug('close', reason);
                self.emit('close', code, reason);
                self._cleanup();
            });
        }



And here:


        Polling.prototype._scheduleReceiver = function() {
            debug('_scheduleReceiver');
            var self = this;
            var poll = this.poll = new this.Receiver(this.receiveUrl, this.AjaxObject);

            poll.on('message', function(msg) {
                debug('message', msg);
                self.emit('message', msg);
            });

            poll.once('close', function(code, reason) {
                debug('close', code, reason, self.pollIsClosing);
                self.poll = poll = null;

                if (!self.pollIsClosing) {
                    if (reason === 'network' && code !== 3000) {  //added code !== 3000
                        self._scheduleReceiver();
                    } else {
                        self.emit('close', code || 1006, reason);
                        self.removeAllListeners();
                    }
                }
            });
        };

I know that its not the best solution, but it worked for me :)

**Comment by FZambia** [comment]
@NaorHai I am not a maintainer of this repo - just came across similar problem in the past - so better to ask @brycekahle

**Comment by NaorHai** [comment]
@FZambia 10x man!

@brycekahle  wdyt?

**Comment by milosonator** [comment]
I'm actually looking for a way to retrieve the close code when the connection is closed. As far as I know the default way of connecting does not give me the close code when the connection is terminated. The reason I want this, is because I want to change client behavior based on this code.

**Comment by manideeppabba1991** [comment]
I had the same issue. My app was running on secure "https://" where as I am trying to fetch the sockjs-0.3.min.js from an "unsecured CDN location" which fails to download the .js file. Which causes it to look for Xhr_Streaming instead of my sockjs methods while disconnecting the socket.
Some references related to http vs https:
https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content

I fixed this issue by changing the "unsecured cdn path to secured cdn path" i.e.,
`index.html

<script src="https://cdn.jsdelivr.net/sockjs/0.3.4/sockjs.min.js"></script>`

**Comment by zbykovskyi** [comment]
I spent a lot of time debugging SockJS and Spring code to figure out with that issue and what I have found.

xhr.js file has next method to parse inbound text message:

```
XhrReceiver.prototype._chunkHandler = function(status, text) {
  debug('_chunkHandler', status);
  if (status !== 200 || !text) {
    return;
  }

  for (var idx = -1; ; this.bufferPosition += idx + 1) {
    var buf = text.slice(this.bufferPosition);
    **idx = buf.indexOf('\n');**
    if (idx === -1) {
      break;
    }
    var msg = buf.slice(0, idx);
    if (msg) {
      debug('message', msg);
      this.emit('message', msg);
    }
  }
};
```

That method expects **\n** at the end of the SockJS text frame.

But Spring Framework sends just 
```
	public static SockJsFrame closeFrame(int code, @Nullable String reason) {
		return new SockJsFrame("c[" + code + ",\"" + (reason != null ? reason : "") + "\"]");
	}
```
without ending **\n**.

I`ve just created copy of org.springframework.web.socket.sockjs.frame.SockJsFrame and put in my classpath to substitute the original file with modified one.
```
    public static SockJsFrame closeFrame(int code, @Nullable String reason) {
        return new SockJsFrame("c[" + code + ",\"" + (reason != null ? reason : "") + "\"]\n");
    }
```

After that fix all works as expected and c[3000, go away!] successfully routes to the 'c' section of next switch
```
SockJS.prototype._transportMessage = function(msg) {
  ...
  switch (type) {
    case 'a':
      if (Array.isArray(payload)) {
        payload.forEach(function(p) {
          debug('message', self.transport, p);
          self.dispatchEvent(new TransportMessageEvent(p));
        });
      }
      break;
    case 'm':
      debug('message', this.transport, payload);
      this.dispatchEvent(new TransportMessageEvent(payload));
      break;
    case 'c':
      if (Array.isArray(payload) && payload.length === 2) {
        this._close(payload[0], payload[1], true);
      }
      break;
  }
};

```

Without that fix message is not parsed as close message.
