### ISSUE TITLE
when I hold my first sockjs request 

### ISSUE THREAD

**Issue by suozq1** [sockjs/sockjs-client#424]
![image](https://user-images.githubusercontent.com/10241390/38018030-5abb20a2-32a6-11e8-848d-a0f379036237.png)

when I hang up my first sockjs request in background,it will hava those errors in browser.
why 1.0.0?

**Comment by FZambia** [comment]
In iframe-based transports you have html file content generated on server side. In that html content server includes script with SockJS URL. Most SockJS server implementations have an option to configure this URL. For example `sockjs-node`:

```
var echo = sockjs.createServer({ sockjs_url: 'http://cdn.jsdelivr.net/sockjs/1.0.1/sockjs.min.js' });
```

The version of SockJS that your web page scripts use must match the version of SockJS set in server configuration.

**Comment by brycekahle** [comment]
@FZambia is correct. Closing.
