### ISSUE TITLE
HPE Fortify detects a possible CSRF vulnerability

### ISSUE THREAD

**Issue by williamhavercamp** [sockjs/sockjs-client#430]
The specific warning is as follows:

"The HTTP request at sockjs.min.js line 3 must contain a user-specific secret in order to prevent an attacker from making unauthorized requests."

sockjs-client version:  v1.1.2
HPE Fortify version: 17.20.0183

**Comment by brycekahle** [comment]
I'm sorry, but I don't have time to chase down a "possible" vulnerability, with so little information provided.

If you have prove a vulnerability exists, I'd be happy to look at it. Often the issues raised by automated security software are false positives.
