### ISSUE TITLE
jsessionid in url

### ISSUE THREAD

**Issue by ilplotkin** [sockjs/sockjs-client#432]
If url rewriting is used for jsessionid then url for info request is composed incorrectly:
```
http://example.com/ws;jsessionid=123/info?t=1524833037318
```
Looks like that the following code does not take into account that url could contain jsessionid:
https://github.com/sockjs/sockjs-client/blob/436e997549f3937cc16bd5085addb218d43cfb60/lib/utils/url.js#L39

Thank you

**Comment by brycekahle** [comment]
The info endpoint does not vary by session, and thus does not require a session id.

**Comment by brycekahle** [comment]
Can you provide a config that does not work correctly?

**Comment by ilplotkin** [comment]
Due to security reasons, our server rejects any request (including info endpoint) without jsessionid and/or special security token.
Anyway, the issue is not actual now as we migrate to native browser websocket.
Thank you

**Comment by brycekahle** [comment]
I'm closing this issue since you are doing url rewriting outside of this library.
