### ISSUE TITLE
200-300ms Delay after library is loaded to when first xhr call is made to sockjs url

### ISSUE THREAD

**Issue by mercuryyy** [sockjs/sockjs-client#435]
Trying to fire sockjs as early as possible but there is a delay from when the library finishes and

var sockjs_url = 'url';
sockjs = new SockJS(sockjs_url);

is executed, then comes a 200-300ms delay until the first xhr call is made to the url

i intently fire the lib and code after the onload event is triggered on my pages, is there a delay set somewhere in the lib i cant figure out how to set SockJS() to fire exactly after the lib finished reading.

I tried various ways but there is always a delay probably somewhere in the sockjs lib, since other scripts exec after
var sockjs_url = 'url';
sockjs = new SockJS(sockjs_url);
gets loaded to the dom before "sockjs_url

**Comment by brycekahle** [comment]
Which URL are you referencing? There is an `info` call that is made before any transports are attempted. In general, you should not be assuming any synchronous behavior from the library and listening for events.

**Comment by mercuryyy** [comment]
im reffering to the first info call to upgrade headers. 

Timeline. 

Sockjs Lib is loaded synchronous once finished var sockjs is set, then other external js calls are mades from the dom.

In the Dom timeline those other external calls are being called to the Dom before sockjs which makes no sense unless there is a 100-200ms timer in the sockjs Lib i couldnt find.

**Comment by mercuryyy** [comment]
Is it possible to fire either or both instantly after lib finished loading? 
the call that changes headers always fire after the info call in any case.

**Comment by brycekahle** [comment]
The info request is executed as soon as possible after constructing the object, as you can see here: https://github.com/sockjs/sockjs-client/blob/ebc3fddd19fde4b90a20663c560c0b10cd14e57e/lib/main.js#L121

I highly suggest you structure your code to handle the asynchronous and inexact latency of network requests. If you need to do something once the connection is established, wait for the `open` event.
