### ISSUE TITLE
version is very outdated. CORS issue cause crash React Native Android app 

### ISSUE THREAD

**Issue by eshikerya** [sockjs/sockjs-client#437]
first you see ```java.lang.String cannot be cast to java.lang.Boolean``` message and spending 2 days to find out why. then you in try to find out why github version of sockets-client 1.1.4 is different to local, clean-fetch-retrieve - nothing helps. then somehow you understand - file lib/browser/abstrach-xhr.js is very outdated and it tagged as 1.1.4

line 74 from release 1.1.4:
```js
this.xhr.withCredentials = 'true';
```

same line from the actual:
```js
this.xhr.withCredentials = true;
```

please release correct version

**Comment by brycekahle** [comment]
`1.1.5` released
