### ISSUE TITLE
Send binary

### ISSUE THREAD

**Issue by jersobh** [sockjs/sockjs-client#441]
Hi there,

How can I send a blob from sockjs-client to aiohttp-sockjs? I've tryied but there's just [object Blob] result. Right now I'm reading the data with File (window.File, window.FileReader), then encoding to base64, JSON.stringfying it and sending through sockjs, then decoding on server side. But that sometimes corrupts my stream, uses more CPU.. it's not the best way to do it, I guess...
I just need to send a webm file through websockets by chunks, then build it on server side, convert it, whatever.

**Comment by brycekahle** [comment]
Binary is currently not supported. See #252
