### ISSUE TITLE
Websocket is closed before the connection is established

### ISSUE THREAD

**Issue by nohanna** [sockjs/sockjs-client#444]
Hello,

I'm using SockJS with Stomp (Spring Boot 2 / Angular 5) and can't determine what's happening.
Everything work fine but when I refresh my browser 2-3 times, I get a "websocket is closed before the connection is established" and when I refresh my browser again, I get a whitelabel error 404.
It happens only when I get the websocket error and only on Apache. 
Everything work fine when I'm in local.

Any suggestions?

**Comment by yairGit** [comment]
Hi,

i have experienced connection closed on slow networks.
i modified the rtt value and it solved it for me but it is a "dirty"  solution.

if you see broken pipe exception in you spring application it might be the case.

**Comment by nohanna** [comment]
Hi,

I didn't find any appropriate solution using SockJS and Stomp, so I tried without SockJS and it seems to work well.
I have no idea what was causing this problem.
However, I will try your solution to see if it works for me.

Thanks

**Comment by brycekahle** [comment]
`websocket is closed before the connection is established` is a warning, and can be safely ignored. That is the result of a refresh happening before the websocket was established. We call `close` on `unload` to ensure the websocket is cleaned up.

**Comment by Tayyib-A60** [comment]
Hello,
websocket is closed before the connection is established, and it's not allowing my Angular Client to make calls to my .Net back end
Please help.

**Comment by LanPodder** [comment]
i've got the same issue as Tayyib-A60

**Comment by HappinessIsLowExpectations** [comment]
Ditto. It looks like this needs more-descriptive logging because actual problems are associated with a warning that isn't always a problem. Or some client library in the chain up to Angular needs that.
