### ISSUE TITLE
Socket is closed before connection RTT issue

### ISSUE THREAD

**Issue by stavsap** [sockjs/sockjs-client#445]
when connecting on slow networks it seems that the socket connection is closed before the handshake is complete, what makes the connection to fail and try other transport protocols. (xhr streaming...)

i have modified the rtt value to some constant value of 10 sec (yes its a lot but just to see if it is the issue) and it seems to solve this problem.

is there any way to set the rtt or rto value before the connection is started?

from what i see in the sockjs.js file in the dist, the rtt is computed on run time and the rto is set accordingly.

i am using wss connectivity with angularjs and angular 5 projects with spring boot as backed server.

my deployment involves some vlans, vpns and also docker overlay network what might cause some slow networking in times, and the compute of the rto is not correct or too little.

it will be nice to have some way to manual set this values.

my current solution is a dirty work around involving modifying the dist sockjs.js file and integrate it to the project without npm.

please advise.

**Comment by brycekahle** [comment]
Would #413 solve your issue?

**Comment by stavsap** [comment]
no, i still manually modify rtt value in sockjs.js file.

**Comment by daniloarcidiacono** [comment]
@brycekahle Please fix this... there are already two PRs for the same problem:

https://github.com/sockjs/sockjs-client/pull/468
https://github.com/sockjs/sockjs-client/pull/460

When connecting to a SockJS service behind a reverse proxy, if said service is down then the client closes the connection before receiving the 502 Bad Gateway HTTP response.

**Comment by brycekahle** [comment]
I believe this change will solve your problem https://github.com/sockjs/sockjs-client/commit/537352c7d8db0b6fbd3b4d63be4a98cb9af6062a

Please let me know if that isn't the case.
