### ISSUE TITLE
rollup

### ISSUE THREAD

**Issue by dhakehurst** [sockjs/sockjs-client#446]
This module is very problematic in rollup (0.63.4)

this module seems to have dependencies on many core node modules (tty, process, etc).

why does it have these dependencies when it is supposed to be for running in the browser, as 'the client'

**Comment by brycekahle** [comment]
@dhakehurst This is designed to be built with browserify, which replaces those core modules with versions written for the browser.

**Comment by dhakehurst** [comment]
Any likelihood of a modern es6+ version build properly for a browser?

**Comment by brycekahle** [comment]
@dhakehurst A big focus of this library is supporting older browsers without Websocket support. Building a version in ES6 (which they would not support) would be contrary to that goal.

**Comment by brycekahle** [comment]
Closing. The value add of re-writing in ES6 is not worth the effort. It would require transpiling for some very old browser targets, which would likely result in a larger library than it currently is.
