### ISSUE TITLE
null is not an object (evaluating 'this._transport.transportName')

### ISSUE THREAD

**Issue by kichik** [sockjs/sockjs-client#448]
Using Sentry to report user exceptions, I get a lot of the following error:

    null is not an object (evaluating 'this._transport.transportName')

I believe it's coming from:

https://github.com/sockjs/sockjs-client/blob/0ab53b8bf24ead0df4bed488333ceb9e81b8c1b7/lib/main.js#L311

I have a separate issue where I'm unable to use the minified version due to #393. Since I'm using the non-minified version, the `debug()` calls are still there in the code and cause this issue.

It looks like some kind of a race condition where the connection is closed before `_open()` is called. It's only the next line that checks for that case. The `debug()` call assumes the connection is open and accesses `_transport` like it's open.

I'm not sure what the best solution for this would be, but in my case I just commented out that line and it seems to resolve the issue.

**Comment by brycekahle** [comment]
A simple workaround for now is to replace it with:
`this._transport && this._transport.transportName`.
