### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND /sockjs/info?cb=ghn2syanfg

### ISSUE THREAD

**Issue by KarthikCTM** [sockjs/sockjs-client#450]
AT my Ethereum wallet, this error message found. How to resolve this 

"Failed to load resource: 
1) net::ERR_FILE_NOT_FOUND /sockjs/info?cb=ghn2syanfg"
2) SourceSansPro-ExtraLightIt.otf 

![image](https://user-images.githubusercontent.com/38301068/44381615-bbfb4a80-a543-11e8-950c-0e2c8fdad56a.png)

**Comment by KarthikCTM** [comment]
Mac, High Sierra OS. Ethereum wallet 0.11.1

**Comment by brycekahle** [comment]
@KarthikCTM It sounds like your wallet software is using SockJS. They must be using it incorrectly. Please open an issue with them.
