### ISSUE TITLE
SockJS doesn't work with ws protocol

### ISSUE THREAD

**Issue by Gennady77** [sockjs/sockjs-client#452]
Try to connect to ws://<server name>/ and got an exception - SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'ws:' is not allowed.
There is a mention in the comment of source code:
// Step 1 of WS spec - parse and validate the url. Issue #8
I'd like to know what's the Issue #8 and what's the problem with ws protocol.
Thanks

**Comment by brycekahle** [comment]
You cannot directly use `ws` or `wss` as the scheme with SockJS. This is because it uses HTTP(s) to fetch metadata from the server, and all the non-Websocket transports use HTTP(s). If you just need WebSockets, use the native browser API.
