### ISSUE TITLE
url-parse vulnerability

### ISSUE THREAD

**Issue by immunity20** [sockjs/sockjs-client#453]
there is a vulnerability for url-parse 1.1.8 version
and it needs to be upgraded to 1.4.3  it has to be done through sockjs-client owner or i can fix it myself?
(I use react-scripts that uses webpack-dev-server and react-dev-utils which use sockjs-client)

**Comment by brycekahle** [comment]
`master` has been updated: https://github.com/sockjs/sockjs-client/blob/841e035b9ddcc5536be6e95b86821d8bf2e3a825/package.json#L33

I just need to do a release.
