### ISSUE TITLE
Whoops! Lost connection to websocket endpoint

### ISSUE THREAD

**Issue by mhabsaoui** [sockjs/sockjs-client#454]
Hi,

I am working with spring websocket v4.2.3 under Java 1.7.
Deploying is made on Tomcat 7.0 server (without spring-boot).

Opening Web Socket...
GET http://localhost:8080/ws/info?t=1536733706374 404 (Introuvable)
Whoops! Lost connection to http://localhost:8080/ws

Any help is welcome.

**Comment by manishparganiha** [comment]
In your web security config class.
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

in configure method put below code.
 @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.cors().and().csrf().disable().authorizeRequests()
                .antMatchers("/ws/info",
                         "/ws/**",                       
                        )
                .permitAll();
    }

It should work.

**Comment by Malikkhoja** [comment]
Hi @manishparganiha ,

I am using an https url for my websocket. It works fine on all the browswer, however doesnt work for my React Native Mobile App. I have tried other solutions as well but none of them worked. 

Can you help?

Thanks in advancee

**Comment by ckrgithub** [comment]
@Malikkhoja I had the same problem. Have you solved it

**Comment by Naishadh8115** [comment]
@Malikkhoja & @ckrgithub Are you able to find solution for react native, Help please if you have solved.

**Comment by GittyAjay** [comment]
> Hi @manishparganiha ,
> 
> I am using an https url for my websocket. It works fine on all the browswer, however doesnt work for my React Native Mobile App. I have tried other solutions as well but none of them worked.
> 
> Can you help?
> 
> Thanks in advancee

https://medium.com/@sormailgu/react-native-stomp-android-whoops-lost-connection-e55daf727e27

**Comment by shailesh-keshri** [comment]
I'm getting this error in my angular application how to resolve this? Someone please suggest any solution I asked GPT as well no solution given
