### ISSUE TITLE
SyntaxError: Unexpected token: name (index)]

### ISSUE THREAD

**Issue by ioana-m** [sockjs/sockjs-client#457]
Hi,

I was using version 1.1.5 successfully, and now with version 1.2.0 I get the following error when using uglify to minimize my code (I use gulp-uglify, 1.5.4)

bower_components\sockjs-client\dist\sockjs.js: SyntaxError: Unexpected token: name (index)]
lineNumber: 4054

I returned to using 1.1.5 but would appreciate if you fix the problem, or tell me if I am doing something wrong.

Thank you.

**Comment by brycekahle** [comment]
It looks like one of the dependencies `debug` started using ES6: https://github.com/sockjs/sockjs-client/blob/4027289acdf484ae511f6ad286761517f61419b6/dist/sockjs.js#L4054

I suggest you upgrade your `gulp-uglify`. This project uses it also and version `3.0.1` is working great.

**Comment by brycekahle** [comment]
Also, is there a reason you cannot use the already minified version? That version removes `debug` and thus does not have this problem.

**Comment by brycekahle** [comment]
Fixed in `1.3.0` by downgrading `debug`.
