### ISSUE TITLE
Is it possible to use an unqualified domain name?

### ISSUE THREAD

**Issue by Tjorriemorrie** [sockjs/sockjs-client#465]
I'm getting the error for attempting a connection:
```
a["{\"type\":\"error\",\"data\":\"Invalid Host header\"}"]
```
which is because I'm using a custom domain name on my local dev, e.g. `sitename:8080`. There are no dots. It works fine when I use `127.0.0.1` of course, but was wondering out of curiosity - as I don't know much about these things - if it is possible to support this or what the reason is that it cannot be supported?

**Comment by brycekahle** [comment]
That error appears to be coming from the server. Which server software are you using?
