### ISSUE TITLE
Firecamp welcomes SockJS

### ISSUE THREAD

**Issue by Nishchit14** [sockjs/sockjs-client#466]
First of all, Thank you all @contributor for bringing this awesome WS emulator in the world.

I need your help and feedback for my mission, I am on the mission to `making developers life easier, every day`. So I am building the [Firecamp](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl), It’s a campsite for all the real-time technology. where  developers can test, debug and manage every realtime event **without creating or being dependent on any frontend.**

[Firecamp](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl) has one feature `auto code snippet generator`, where devs can easily get code snippets in every client language within a single click based on their saved request. A [SocketIO](http://socket.io) code snippet is in the below screenshot.  

[Firecamp](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl) has already integrated [SocketIO](http://socket.io) and WebSocket, now next one is [SockJS](http://sockjs.org).

Now I am planning to build this auto code snippet generator engine for the SockJS, So I am gathering all the SockJS client libs to review their code blocks for connection, close, send and other methods.

Here I have come across the list which I have found so far, Please help me to find more if any and sort list the below libs based on their popularity.

I’ll really appreciate it and share the credit for your contribution, Thank in advance.

**[SockJS](http://sockjs.org) client libraries**

> paython - https://github.com/amagee/sockjs-client
> C# - https://github.com/jarhf/JarhfStomp4Net
> java - https://github.com/jaysridhar/spring-websocket-client/tree/master/src/main/java/sample
> android- https://github.com/vishal-raj/SockJsClientAndroid
> objective c and swift- https://github.com/jeremyfa/openfl-sockjs
> dart- https://github.com/nelsonsilva/sockjs-dart-client/tree/master/example
> go- https://github.com/lavab/sockjs-go-client/blob/master/client.go

**[SocketIO code snippet](https://twitter.com/FirecampHQ/status/1073561820164702210)**
![image](https://user-images.githubusercontent.com/5078921/50882537-191c6d80-140b-11e9-9282-33411f50c803.png)

**Comment by brycekahle** [comment]
It is hard to keep tabs on all the different clients and servers. See a brief, non-exhaustive list here: https://github.com/sockjs/sockjs-client#sockjs-family

Do not forget this repo! It is the main JS client.

**Comment by Nishchit14** [comment]
thanks, @brycekahle , 
They are mostly the sockjs servers, I'm looking for the clients only.

**Comment by UltraNemesis** [comment]
Outside of JavaScript, you don't really need a separate sockjs client like is the case with socket.io. The beauty of sock.js is that can just connect to a sockjs server using plain WebSocket and handle events normally as you would. There are no custom layers on top.

So, you can just use sock.js client for JS (Just to take advantage of fallbacks) and any websocket lib for all other languages.

**Comment by brycekahle** [comment]
@UltraNemesis The large assumption there is that Websockets work in that particular network environment. The non-browser clients supply similar fallbacks in such a case.
