### ISSUE TITLE
chrome70 + stompjs + sockjs-client + java spring boot 2.0 connect too slow

### ISSUE THREAD

**Issue by xzzh999** [sockjs/sockjs-client#470]
**chrome**: 70.0.3538.67
**stompjs**: "^2.3.3",
**sockjs-client**: "^1.3.0",
**spring boot use websocket**: 2.0.2.RELEASE

As the title say, when i print the timestamp of connect function, it takes nearly **6** or **12** **seconds** or even failed to establish the connection, why it's so slow?

Here is the client side code:
```
addStomp(state, url) {
            if (!state.stompClients.has(url))
                state.stompClients.set(url, Stomp.over(new SockJS(url)));
        },
```

```
startSignalMonitor(context, { url, subUrl, callBack, errCallBack }) {
            return new Promise((resolve, reject) => {
                let subscribeClient;
                context.commit('addStomp', config.base_url_name+url)
                let stompClient = context.state.stompClients.get(config.base_url_name+url)
                stompClient.debug = msg => { };
                if (stompClient.connected) {
                    subscribeClient = stompClient.subscribe(subUrl, callBack, errCallBack)
                    resolve(subscribeClient)
                }
                else {
                    // TOO SLOW HERE!!!
                    stompClient.connect({}, () => {
                        subscribeClient = stompClient.subscribe(subUrl, callBack, errCallBack)
                        resolve(subscribeClient)
                    })
                }
            })
        }
```
Need u help, thanks!

**Comment by brycekahle** [comment]
I cannot debug your performance issues for you. I suggest you add timing along your request path to find out where the latency is coming from.

**Comment by xzzh999** [comment]
@brycekahle
Thank u for your reply, i have debugged it and found it's blocked on the **connect** function, maybe i should set a transport when create the object? what are the possible reasons for  **the connect function** is too slow?

**Comment by xzzh999** [comment]
@brycekahle
I found when i add a prefix base url, this will happen, eg:

**In client side (fast)**
```
//OK
ws://localhost:8081/ws/endpointChat   
```
**In client side (slow or failed)**
```
//SLOW or FAILED
ws://localhost:8081/MyServer/ws/endpointChat   
```

**In server side (spring boot application.properties)**
```
server.servlet.contextPath=/MyServer
```

I use vue.js 2.0 and webpack.

**Comment by xzzh999** [comment]
@brycekahle 
When i use proxy table to proxy websocket, the problem comes!(too slow)
Here is the print:

![](https://github.com/xzzh999/markdown-pictures/blob/master/websocket-slow.png?raw=true)

**Comment by brycekahle** [comment]
@xzzh999 You might want to mix the obvious error shown in your log.

**Comment by xzzh999** [comment]
@brycekahle 
Thank you for your reply.
The bug is confirmed, here is the [reason](https://github.com/webpack/webpack-dev-server/issues/474).
