### ISSUE TITLE
SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS

### ISSUE THREAD

**Issue by youarefoodie** [sockjs/sockjs-client#473]
How to solve this situation?

**Comment by brycekahle** [comment]
You need to use `https` in your SockJS URL

**Comment by mding5692** [comment]
So something like this: https://cdn.jsdelivr.net/sockjs/1.0.1/sockjs.min.js?

**Comment by brycekahle** [comment]
Not exactly (although you should definitely load SockJS from `https`  if the page is `https). I'm talking about the URL used when constructing SockJS. Example:

`var sock = new SockJS('https://mydomain.com/my_prefix');`

You can see where the error is being returned: https://github.com/sockjs/sockjs-client/blob/608cf2ff101a27b789d987c8eef00dbe899b650e/lib/main.js#L78-L80
