### ISSUE TITLE
json3 deprecated

### ISSUE THREAD

**Issue by sidoruk-sv** [sockjs/sockjs-client#476]
https://www.npmjs.com/package/json3

> JSON 3 is **deprecated** and **no longer maintained**. Please don't use it in new projects, and migrate existing projects to use the native `JSON.parse` and `JSON.stringify` instead.

**Comment by brycekahle** [comment]
I believe its use as a polyfill is still valid for sockjs. We still target some of the browsers that needed the polyfill in the first place.

**Comment by DaSchTour** [comment]
polyfills generally are not part of a library but are added on demand but the user of a library. This is currently forcing everybody to ship json3 to millions of users that don't need it. I think it will save a lot of carbon dioxide to not ship it to the 99.9% of users that doesn't need it.
Just let the user include https://polyfill.io/v3/ with JSON and only the few users that really need it will have to download JSON polyfill.

**Comment by brycekahle** [comment]
Removing JSON3 would be a breaking change for some users, which is not something I'm interested in doing at the moment.

**Comment by DaSchTour** [comment]
That's why there is semver I guess.

**Comment by jonkoops** [comment]
@brycekahle What is your intention in regards to browser support in the future? Will support for IE below v11 be dropped at some point?
