### ISSUE TITLE
Certificate Pinning with SockJS

### ISSUE THREAD

**Issue by ashenwgt** [sockjs/sockjs-client#479]
What is the SockJS way of pinning SSL Certificates when contacting `wss://` to avoid CA trust?

I know that, when using modules like HTTPS or WS, we can listen to the `socket` event and then on `secureConnect`, we can get fingerprints via `getPeerCertificate()` and compare against a hardcoded valid fingerprint like below. Is there a similar approach for SockJS as well?

Please see these references as well: 
[1. WSS](https://github.com/websockets/ws/issues/1281)
[2. HTTPS](http://hassansin.github.io/certificate-pinning-in-nodejs)

```
const ws = new WebSocket(url);
const validFingerprint = 'CA:06:F5:6B:25:8B:7A:0D:4F:2B:05:47:09:39:47:86:51:15:19:84';

ws._req.on('socket', function (socket) {
  socket.on('secureConnect', function () {
    const { fingerprint } = socket.getPeerCertificate();

    if (fingerprint !== validFingerprint) ws.close();
  });
});
```

**Comment by brycekahle** [comment]
There isn't an official way that would work across multiple transports.

**Comment by ashenwgt** [comment]
Hi @brycekahle, thanks for the reply. And hats off for maintaining this plugin. 

If there's no any official way, do you have any recommended approach to implement SSL pinning with SockJS Client? Or have you seen any instances where users modify this module to cater the pinning feature? All I want to get is the peer certificate while connecting via a secure websocket. Could you please advise me?

**Comment by brycekahle** [comment]
If you only want websockets, then SockJS is not what you want. SockJS can use multiple non-websocket transports under the hood. Check out https://github.com/faye/faye-websocket-node/

**Comment by ashenwgt** [comment]
Thanks @brycekahle  for the suggestion. I'll check it out. Cheers!
