### ISSUE TITLE
Sockjs Stomp through AWS Api Gateway

### ISSUE THREAD

**Issue by lcorniglione** [sockjs/sockjs-client#480]
Hi everyone, 

I am developing an web app, using Stomp over Sockjs. I also have a RabbitMQ server in order to manage websockets connections.
The problem is that I have all setted up through AWS Api Gateway. So in my client when I try to connect to websocket behind the Api Gateway I have this error: 

> WebSocket connection to 'wss://{url}/v1/audit/221/3d0ozc1y/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

I think that I am missing something about it, becouse all the traffic is over HTTPS, but behind I suppose that Sockjs or Stomp is trying to send a request through wss protocol and I dont have a handler for it in the api gateway.

I am wondering to know if someone have faced an issue like this and can give me some insight to solve it.

Thanks you all.

**Comment by brycekahle** [comment]
I don't believe SockJS is compatible with AWS API Gateway.
