### ISSUE TITLE
"SecurityError: An insecure SockJS connection" should be ignored when using "localhost"

### ISSUE THREAD

**Issue by sirloon** [sockjs/sockjs-client#482]
Hi,

Referencing that line: https://github.com/sockjs/sockjs-client/blob/master/lib/main.js#L79

I think there should be an exception when the websocket is running on localhost. It's basically rare to have https:// running on localhost, and for the same reason a brower will allow to load unsecure content from localhost when the main site is https, there should be a check on the host.

Hope that makes sense :)

**Comment by brycekahle** [comment]
Can you explain the situation where the page you are loading is `https` but you want to access SockJS via `localhost`?

**Comment by sirloon** [comment]
I have a webapp, static files only, getting its data using an API, through sockjs. This webapp is publicly accessible, but the API can be private, requiring for instance an SSH tunnel to the server hosting the API, exposing it as localhost. So I would "ssh -L 7080:localhost:7080 myserver, and then reference http://localhost:7080 in my webapp served in https.

Another common scenario is when I just develop the API on my own computer but still want to use the public webapp.

**Comment by brycekahle** [comment]
If I check for `localhost`, then I would also have to check for all private IP ranges, including IPv6. I don't think the value add from that is worth the extra code or risk, for such a non-typical setup.

I suggest setting up a local hostname alias w/ a self-signed (or lets encrypt) cert.
