### ISSUE TITLE
SockJS slows the client down when sending a lot of mesages

### ISSUE THREAD

**Issue by dolanmiu** [sockjs/sockjs-client#483]
I am sending about 2262 messages per second to the client, and experiencing slowness on these particular files/functions:

node_modules\sockjs-client\lib\transport\receiver\xhr.js
node_modules\sockjs-client\lib\event\emitter.js

Or:

https://github.com/sockjs/sockjs-client/blob/master/dist/sockjs.js#L73
https://github.com/sockjs/sockjs-client/blob/master/dist/sockjs.js#L2611

Check the picture below:

![image](https://user-images.githubusercontent.com/2917613/62467212-190b0300-b78b-11e9-9294-5243c0ced2ba.png)

**Comment by brycekahle** [comment]
@dolanmiu It looks like your test is using the XHR transport, which is naturally going to limit the messages per second that you can receive.

**Comment by dolanmiu** [comment]
so to not use XHR transport, I need to use websocket right?

is there some setting in the client side, or is the transport mechanism dictated by the server?

**Comment by brycekahle** [comment]
There are definitely [options](https://github.com/sockjs/sockjs-client#sockjs-class) but I'm guessing that something about your browser/network setup is forcing a fallback to XHR.
