### ISSUE TITLE
Is it possible to allow 127.0.0.1 when accessed under secure domain?

### ISSUE THREAD

**Issue by cyjake** [sockjs/sockjs-client#486]
Chrome allows loading resources from http://127.0.0.1 AFAICT and it helps local developments a lot. webpack-dev-server usually serves resources at http://127.0.0.1 also (and sometimes on a different port against the main express/egg service for better build performance).

**Comment by nougad** [comment]
Any update here? By now http://127.0.0.1 works in Firefox as well.

It looks like this line requires an update: https://github.com/sockjs/sockjs-client/blob/89f0128e901e30d609bc46266e2d0900fcb19c6b/lib/main.js#L77-L81

Instead of `!secure` it should be something like:

```
if (loc.protocol === 'https:' && parsedUrl.hostname !== '127.0.0.1' && !secure) {
```
