### ISSUE TITLE
Multiple Websocket connections

### ISSUE THREAD

**Issue by dennislabajo** [sockjs/sockjs-client#489]
Is there a way or feature I can use to tell how many websocket connections the client has made to the server?  I would like to be able to manage these and ensure there should only be one.  The reason for the question is because I'm seeing at the server http logs multiple xhr_streaming calls originating from the same client.  It does not happen all the time, for the most part, there's only one connection which is good but there are cases where we're seeing multiple connections which we would like to prevent as this could max out server connection resources.

**Comment by brycekahle** [comment]
One instance of SockJS will only have a single open connection at a time. Is it possible they have multiple tabs open? How are you distinguishing clients from each other?

**Comment by dennislabajo** [comment]
Hi Bryce.  It is not possible to have multiple tabs.  The browser is hard-wired to connect to just one and specific web application and the device is locked-down. There are no users that can directly intervene/open a secondary tab.  To distinguish a client from each other, a client has a unique identifier passed as a parameter to the xhr_streaming event that I can key off from the http access logs and count the instances.

**Comment by brycekahle** [comment]
Do you have logs that you can share to help debug this issue?

**Comment by rupebac** [comment]
I think this may be related with my issue here:
https://github.com/sockjs/sockjs-client/issues/493
