### ISSUE TITLE
Probably a silly question, sorry.

### ISSUE THREAD

**Issue by zerocarbthirty** [sockjs/sockjs-client#492]
Hello, I am connecting to a 3rd party service that uses SockJS. They gave me an https:// url and I was able to build a very simple application that is able to connect to that service in JS using the SockJS client library.

However, I am trying to connect to it in C# and I'm not sure that the SockJS library available for c# actually works.

I've read that any SockJS server is available to connect over wss:// and when looking in my browser when running my JS application I see a connection to a wss:// server but I haven't been able to find the 'initial' URL. By the time the wss:// url shows up in Chrome it already has a session id on it and looks like this:

wss://hostname/ws/050/k2p35oq0/websocket so what URL would I use for just an initial websocket connection to this service on? Thanks for any help you can provide me with.

**Comment by brycekahle** [comment]
Here is the documentation about that feature: https://github.com/sockjs/sockjs-node#connecting-to-sockjs-node-without-the-client

**Comment by zerocarbthirty** [comment]
Unfortunately just adding /websocket to the end of the url and changing the https to wss doesn't seem to work. Anyway, I am having a problem getting c# to send JSON to the SockJS server. Every time I send a string with double quotes " the server returns a 500 server error.

I notice in the sockjs code it shows:

SockJS.prototype.send = function(data) {
if (this.readyState !== SockJS.OPEN) {
return;
 }
this._transport.send(escape.quote(data));
 };
Is escaping quotes the only thing the send() function does to the string prior to sending it to the server?

**Comment by brycekahle** [comment]
It is possible they have turned off the raw websocket option. What is the error being returned when you get a `500`. That would provide some insight as to what is occurring?

**Comment by zerocarbthirty** [comment]
So the Javascript version of the app (which works fine) pulls JSON from the remote host to build the payload.  In that JSON from the remote host there is an array, that array has all double-quotes escaped already (from the remote host). So when I use JSON.stringify on it the string doesn't change at all.

`"password":"{\"username\"`

 but when I use .send (SockJS in chrome) all of the double quotes are escaped and all of the already escaped double quotes in that array are double escaped.

`\"password\":\"{\\\"username\\\"`

I'm pretty sure my problem is just getting the JSON sent to the server in c# the same way that the SockJS client is sending it. (escaping the quotes, etc.) 

Should I be "un-escaping" the initial response from the server prior to building the JSON string to send back to the web socket?
