### ISSUE TITLE
Console error "SCRIPT445: Object doesn't support this action" only in IE11 where emit is triggered when socket is closed on unload 

### ISSUE THREAD

**Issue by pskushw** [sockjs/sockjs-client#494]
We are getting a console error "SCRIPT445: Object doesn't support this action" from sockjs.js and only in IE11, which is coming from EventEmitter.prototype.emit function from the line` var args = new Array(l - 1);` where Array is undefined( Array constructor is not available) and this error occurs only happen when navigating away from the page (say by clicking the header back). 
I can see EventEmitter.prototype.emit is getting called many time but error occurs only when it is getting called from this.unloadRef -> this.ws.onclose ->self.emit('close', e.code, e.reason);  within function WebSocketTransport

Below is the code from where EventEmitter.prototype.emit is getting called and the error occurs. This issue is similar to https://bugzilla.mozilla.org/show_bug.cgi?id=696085 and it is already mentioned in the comments of code but seems like this issue has not been resolved completely for IE11 

```
  // Firefox has an interesting bug. If a websocket connection is
  // created after onunload, it stays alive even when user
  // navigates away from the page. In such situation let's lie -
  // let's not open the ws connection at all. See:
  // https://github.com/sockjs/sockjs-client/issues/28
  // https://bugzilla.mozilla.org/show_bug.cgi?id=696085
  this.unloadRef = utils.unloadAdd(function() {
    debug('unload');
    self.ws.close();
  });
this.ws.onclose = function(e) {
    debug('close event', e.code, e.reason);
    self.emit('close', e.code, e.reason); 
    self._cleanup();
  };
```

**Comment by brycekahle** [comment]
How is the `Array` constructor not available when JavaScript code is running? That seems bizarre.

**Comment by pskushw** [comment]
Even I am not sure but that's happening only in IE11 and only when self.ws.close() is getting called from this.unloadRef. 
I tried to find and found this and maybe this could answer: https://stackoverflow.com/questions/35153417/getting-error-in-ie11-for-javascript-array

**Comment by MasonBergstrom** [comment]
I'm getting this same issue, it's not just Array that we're losing the context to though. My project then tries to catch that error in react-error-overlay where `n instanceof Error` also fails since the Error constructor is now undefined.
