### ISSUE TITLE
escape.quote(data) will change data to string, why need this line?

### ISSUE THREAD

**Issue by yanguoyu** [sockjs/sockjs-client#501]
https://github.com/sockjs/sockjs-client/blob/3ccf61d256f13d6108870e5057363df9779e2b14/lib/main.js#L164
this line will change data to string, why need this line?
https://github.com/sockjs/sockjs-client/blob/3ccf61d256f13d6108870e5057363df9779e2b14/lib/main.js#L155

` 
if (typeof data !== 'string') {
    data = '' + data;
  }
`

**Comment by brycekahle** [comment]
If look at the reference issue in the comment above, it is because we are only supporting the `string` type of data for Websockets. https://github.com/sockjs/sockjs-client/issues/13
