### ISSUE TITLE
@types/sockjs-client Options interface doesn't include timeout

### ISSUE THREAD

**Issue by steviemo** [sockjs/sockjs-client#503]
`interface Options {
        server?: string;
        sessionId?: number | SessionGenerator;
        transports?: string | string[];
    }`

Timeout should be supported as it is used (as per the documentation).

**Comment by brycekahle** [comment]
Those types are not maintained by me or in this repo. You should suggest the change here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sockjs-client
