### ISSUE TITLE
Whoops! Lost connection to websocket endpoint

### ISSUE THREAD

**Issue by Malikkhoja** [sockjs/sockjs-client#505]
Hi,

I am working with websocket with React Native.
The same websocket works in all my browser. However when I try the same in React Native, I get below error:

Opening Web Socket...
Whoops! Lost connection to Socket URL

Note: I am using https url for Websocket.

Any help is welcome.

**Comment by StefanoMartella** [comment]
Hi,

I've a similiar issue but with a really weird behaviour. My code is the following:

`
...
import SockJS from 'sockjs-client'; // Note this line
import Stomp from 'stompjs';

function ChatScreen() {
useEffect(() => {
    const socket = new SockJS('http://localhost:8080/chat');
    const stompClient = Stomp.over(socket);
    stompClient.connect({Authorization: `Bearer ${jwt}`}, () => {
      stompClient.subscribe(
        `/user/${user.username}/queue/messages`, console.log, {Authorization: `Bearer ${jwt}`},
      );
    });
    return () => stompClient && stompClient.disconnect();
  }, [dispatch, jwt, user.username]);

...
}
`

In this case I get:
> Whoops! Lost connection to http://localhost:8080/chat

Then if I change the SockJS import line from `import SockJS from 'sockjs-client';` to `import SockJS from 'sockjs-client/dist/sockjs';` without reloading with double "r", but letting hot reloading do its job, I successfully obtain a connection to the websocket and everything works fine. Now, if I reload with double "r" I get again the message:

> Whoops! Lost connection to http://localhost:8080/chat

Switching back to `import SockJS from 'sockjs-client';` from `import SockJS from 'sockjs-client/dist/sockjs';` I successfully obtain a new working connection but double "r" breaks it down again.

For a better understanding on what I mean this is a video that reports the behaviour:
https://bit.ly/2ZtRsaX

**Comment by StefanoMartella** [comment]
Hi @Malikkhoja, in my case the problem was that I was using `http://localhost:8080/chat` in the websocket url; since I'm on an Android emulator I had to use `http://10.0.2.2:8080/chat` instead.

**Comment by Kimidori** [comment]
@StefanoMartella where do you config or replace http://localhost:8080/chat to http://10.0.2.2:8080/chat? also I'm running on a real device and still cannot connect.

**Comment by StefanoMartella** [comment]
@Kimidori Hi, I used it as the URL of the endpoint to connect. I'm using this library:

https://github.com/lahsivjar/react-stomp 

My code to enstablish a working connection:
```
<SockJsClient
          ref={sockJsRef}
          url="http://10.0.2.2:8080/chat"
          topics={[`/user/${user.username}/queue/messages`]}
          onMessage={(message) => dispatch(storeMessage(message))}
 />
```

Hope this helps
