### ISSUE TITLE
Why is the code and reason passed in by the close method invalid?

### ISSUE THREAD

**Issue by siaikin** [sockjs/sockjs-client#508]
https://github.com/sockjs/sockjs-client/blob/3ccf61d256f13d6108870e5057363df9779e2b14/lib/main.js#L329

https://github.com/sockjs/sockjs-client/blob/3ccf61d256f13d6108870e5057363df9779e2b14/lib/main.js#L339

if i understand correctly, `this._transport` is a WebSocket object. however, the passed in `code` and `reason` is not passed into `this._transport.close` method.

is this the design? or what did i miss?

**Comment by brycekahle** [comment]
`this._transport` is not a WebSocket necessarily. This library supports many different transports, most of which do not support sending an error code and reason upon close.
