### ISSUE TITLE
Uncaught TypeError: onUnload[ref] is not a function

### ISSUE THREAD

**Issue by dgofman** [sockjs/sockjs-client#509]
I am using Angular 10 is installing the package dependencies sockjs "version": "0.3.20" and sockjs-client "version": "1.4.0".
By clicking a Refresh button or F5 I was able to capture the errors in the Chrome Dev Tools -> Console. 

![TypeError](https://user-images.githubusercontent.com/147298/88599870-b5c05380-d021-11ea-90bc-36ac145c16fe.png)

**Comment by brycekahle** [comment]
All the usages in sockjs are definitely functions. If you can set a breakpoint and determine what `unLoad[ref]` is, that would be very helpful.
