### ISSUE TITLE
header management for XHR fallback requests

### ISSUE THREAD

**Issue by mrik974** [sockjs/sockjs-client#515]
I understand that browsers do not let websocket requests being modified by SockJS. 
But is there a way to modify the headers for the XHR requests that are used as fallbacks when websocket is not available? 

I need to implement CSRF headers specifically. I'm using Spring as a backend, and CSRF support in websocket is enabled and working, but when I disable websocket to test the fallback queries, the CSRF protection prevents them from working.

Right now, it means I have to disable CSRF server-side protection for any fallback query but this is not the most secure way.

**Comment by brycekahle** [comment]
The individual SockJS requests are not performing risky operations, so CSRF does not really apply. This is also why we don't expose cookies. If you need protection, you should be doing it within the content of your SockJS messages, rather than relying on the transport layer.
