### ISSUE TITLE
WebSockets and Security

### ISSUE THREAD

**Issue by ultimatesecpro** [sockjs/sockjs-client#520]
We are going to use SockJS and I will be happy to clarify a couple of questions related to security.
(It is not a one question, but it is important and I will be happy for your help)

According to my understanding during the WebSocket handshake SockJS tries first to upgrade to the WebSocket protocol.

What happens if the upgrade successes?

Should we allow the WebSocket protocol in a firewall between a browser and a server? 
Or enough to allow only HTTPS between a browser and a server?
What affects if the upgrade to the WebSocket protocol succeeds?
Browser configuration? Server configuration?

What happens if the upgrade to the WebSocket protocol fails?

What protocol will be used?
What protocol should be configured in a firewall between a browser and a server? Is it enough to allow only HTTPS between a browser and a server?

Last, but not least: in all cases we need to configure both client and server to protect our WebSocket application against WebSocket attacks.

Correct?

Thanks in advance for your help.

**Comment by brycekahle** [comment]
Some of your questions do not make sense to me, so I'll answer the ones that do.

> What happens if the upgrade successes?

It uses the WebSocket protocol.

> Should we allow the WebSocket protocol in a firewall between a browser and a server?

If you want to support WebSocket, yes.

> What happens if the upgrade to the WebSocket protocol fails?

It falls back to the other HTTP-based transports.

> What protocol will be used?

This depends on the browser/client, network, and what your server supports. The library will attempt transports in order, until finding one that succeeds. See https://github.com/sockjs/sockjs-client#supported-transports-by-browser-html-served-from-http-or-https for a list.

> Last, but not least: in all cases we need to configure both client and server to protect our WebSocket application against WebSocket attacks.

I'm not sure what precisely you mean by "WebSocket attacks" here, but the degree to which you protect your server is your decision.

**Comment by ultimatesecpro** [comment]
Thanks!
