### ISSUE TITLE
The connection is successful，But send a lot of Ajax requests

### ISSUE THREAD

**Issue by zdyWork** [sockjs/sockjs-client#522]
Browser version：Google Chrome More than 70
Problem description：I created a WebSocket connection and it successful，and my browser supports Websoket。Why send so many "xhr? t =" request ? All of these requests return “h”
![p1](https://user-images.githubusercontent.com/24384477/100730237-c8e69400-3404-11eb-9b8c-eaf388d13f28.png)
![p2](https://user-images.githubusercontent.com/24384477/100730243-cab05780-3404-11eb-9cea-eccedcb968df.png)
![p3](https://user-images.githubusercontent.com/24384477/100730245-cb48ee00-3404-11eb-966d-01dcdb93a12b.png)

**Comment by brycekahle** [comment]
You will likely find a websocket that did not actually complete successfully. You can also turn on logging to get more debugging information. I cannot debug your code/network with screenshots.
