### ISSUE TITLE
Need support: Possible to Increase retry timeout and restrict other transports?

### ISSUE THREAD

**Issue by vishnu-konduru** [sockjs/sockjs-client#531]
Hi, 
I'm new to websockets. I decided to post here as other sites offered less support for my issue. We're accessing our streaming server using sock js. When we connect to a websocket, we're seeing two failed requests being sent to the streaming svc at randome times from stomp client.connect(...). Upon checking the console, the two requests are as follows:

POST: https://<ip>/<streaming_url>/ws/<some_id>/<some_id>/xhr_streaming?access_token=....
POST: https://<ip>/<streaming_url>/ws/<some_id>/<some_id>/xhr_send?access_token=....

In error callback if we log the error message string we get:
Whoops! Lost connection to https://<ip>/<streaming_url>/ws?access_token=......

But the connection to streaming svc is established after this errors and the application runs smoothly. Because of the above said failures, we're throwing an error snackbar in UI which is misleading as the streaming svc is getting connected after these failed ones.

Right now, we're expecting only GET requests for the streaming service and this xhr_streaming/xhr_send is not a part of them. I'd like to know if these requests are being sent from sockjs internally and whether if this mandatory to be allowed and what it is used for. Based on other issues I've kept allowed-origins="*" but still didn't solve the issue.

Using version:
Angular 8, Sockjs : 1.1.4, stompjs: 4.0.2

Please let me know if anything can be helped.

**Update:**
I got to know that the xhr_streaming and xhr_send will be attempted when the inital websocket connection call sent to backend fails. But still this looks like a latency related issue as the websocket is able to be successfully connected after a few secs. 

Since these xhr requests are causing unexpected failures, **any way we can disable them and increase the retry wait time**...?

Any suggestions would be nice.

**Comment by brycekahle** [comment]
>  I'd like to know if these requests are being sent from sockjs internally

Yes. These are from SockJS.

> whether if this mandatory to be allowed

SockJS is bi-directional. For transports that don't support that natively, it has to send data (POST) separately from receiving it (GET).

> any way we can disable them

You can configure which transports you support, using the `transports` option of the SockJS constructor: https://github.com/sockjs/sockjs-client#sockjs-class

In general, errors are bound to happen with any network application, and I suggest you try to handle them gracefully.
