### ISSUE TITLE
sockjs does not work on ie8- since v1.2.0

### ISSUE THREAD

**Issue by SwordRays** [sockjs/sockjs-client#541]
os  win10x64
IE8 is simulated by IE11
1.1.5 works ok, but newer versions will report an error, which seems to be related to the debug module

e.g：v1.5.1 error report is line 4099,15

function setup(env) {
  createDebug.debug = createDebug;
  createDebug.default = createDebug;
  createDebug.coerce = coerce;
  createDebug.disable = disable;
  createDebug.enable = enable;
  createDebug.enabled = enabled;
  createDebug.humanize = require('ms');
  Object.keys(env).forEach(function (key) {
    createDebug[key] = env[key];
  });

**Comment by brycekahle** [comment]
There was a fix to the debug module in 1.3.0. Does that version work? 

Also IE8 is 0.03% of global usage at this point, so not something I'm going to bend over backwards to support.

**Comment by SwordRays** [comment]
Thank you very much for the sockjs project.

 I tested that 1.1.5 can work normally, but from 1.2.0 to 1.5.1, it can't run under IE8-, and the error position is roughly the same.

The main cause of the problem is probably the debugging module. Can this part of the function be blocked on the lower version of IE to simply solve it? As long as the basic functions of websocket can be used on these ancient browsers, it should be enough.

In fact, many people like me use sockjs to be able to use websocket on lower versions of IE, otherwise the native websocket can meet the demand.

Finally, I still hope to provide basic support for IE7~8 when conditions permit~Thank you!

**Comment by DaSchTour** [comment]
> There was a fix to the debug module in 1.3.0. Does that version work?
> 
> Also IE8 is 0.03% of global usage at this point, so not something I'm going to bend over backwards to support.

But keeping JSON3 polyfill bundled into the library 🤨 so if IE8 doesn't work, the polyfill also doesn't make any sense
