### ISSUE TITLE
global is not defined  in vue3

### ISSUE THREAD

**Issue by yanwenjia** [sockjs/sockjs-client#547]

**Comment by TranksJ** [comment]
Is this problem solved? I also encountered the global undefined problem

**Comment by DolphaGo** [comment]
I have save issue.
```

event.js:8 Uncaught ReferenceError: global is not defined
    at node_modules/sockjs-client/lib/utils/event.js (event.js:8)
    at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
    at node_modules/sockjs-client/lib/transport/websocket.js (websocket.js:3)
    at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
    at node_modules/sockjs-client/lib/transport-list.js (transport-list.js:5)
    at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
    at node_modules/sockjs-client/lib/entry.js (entry.js:3)
    at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
    at dep:sockjs-client:1
node_modules/sockjs-client/lib/utils/event.js @ event.js:8
__require @ chunk-T7KYDC53.js?v=a7e674ed:6
node_modules/sockjs-client/lib/transport/websocket.js @ websocket.js:3
__require @ chunk-T7KYDC53.js?v=a7e674ed:6
node_modules/sockjs-client/lib/transport-list.js @ transport-list.js:5
__require @ chunk-T7KYDC53.js?v=a7e674ed:6
node_modules/sockjs-client/lib/entry.js @ entry.js:3
__require @ chunk-T7KYDC53.js?v=a7e674ed:6
(anonymous) @ dep:sockjs-client:1
```

**Comment by andyqier88** [comment]
@

> I have the same issue.
> 
> ```
> 
> event.js:8 Uncaught ReferenceError: global is not defined
>     at node_modules/sockjs-client/lib/utils/event.js (event.js:8)
>     at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
>     at node_modules/sockjs-client/lib/transport/websocket.js (websocket.js:3)
>     at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
>     at node_modules/sockjs-client/lib/transport-list.js (transport-list.js:5)
>     at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
>     at node_modules/sockjs-client/lib/entry.js (entry.js:3)
>     at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
>     at dep:sockjs-client:1
> node_modules/sockjs-client/lib/utils/event.js @ event.js:8
> __require @ chunk-T7KYDC53.js?v=a7e674ed:6
> node_modules/sockjs-client/lib/transport/websocket.js @ websocket.js:3
> __require @ chunk-T7KYDC53.js?v=a7e674ed:6
> node_modules/sockjs-client/lib/transport-list.js @ transport-list.js:5
> __require @ chunk-T7KYDC53.js?v=a7e674ed:6
> node_modules/sockjs-client/lib/entry.js @ entry.js:3
> __require @ chunk-T7KYDC53.js?v=a7e674ed:6
> (anonymous) @ dep:sockjs-client:1
> ```
> 
> and it works for me to add `<script>global = globalThis</script>`in index.html

I have the same problem; but when I add `<script>global = globalThis</script>`in index.html ,another problem has arisen `vue-router.esm-bundler.js:3248 TypeError: util.inherits is not a function
    at eventsource.js:315
    at chunk-KHGO2BKN.js?v=76cbd4e4:4
    at eventsource.js:5
    at chunk-KHGO2BKN.js?v=76cbd4e4:4
    at eventsource.js:5
    at chunk-KHGO2BKN.js?v=76cbd4e4:4
    at transport-list.js:8
    at chunk-KHGO2BKN.js?v=76cbd4e4:4
    at entry.js:3
    at chunk-KHGO2BKN.js?v=76cbd4e4:4`
    Have you ever met?

**Comment by TranksJ** [comment]
> @
> 
> > 我有同样的问题。
> > ```
> > 
> > event.js:8 Uncaught ReferenceError: global is not defined
> >     at node_modules/sockjs-client/lib/utils/event.js (event.js:8)
> >     at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
> >     at node_modules/sockjs-client/lib/transport/websocket.js (websocket.js:3)
> >     at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
> >     at node_modules/sockjs-client/lib/transport-list.js (transport-list.js:5)
> >     at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
> >     at node_modules/sockjs-client/lib/entry.js (entry.js:3)
> >     at __require (chunk-T7KYDC53.js?v=a7e674ed:6)
> >     at dep:sockjs-client:1
> > node_modules/sockjs-client/lib/utils/event.js @ event.js:8
> > __require @ chunk-T7KYDC53.js?v=a7e674ed:6
> > node_modules/sockjs-client/lib/transport/websocket.js @ websocket.js:3
> > __require @ chunk-T7KYDC53.js?v=a7e674ed:6
> > node_modules/sockjs-client/lib/transport-list.js @ transport-list.js:5
> > __require @ chunk-T7KYDC53.js?v=a7e674ed:6
> > node_modules/sockjs-client/lib/entry.js @ entry.js:3
> > __require @ chunk-T7KYDC53.js?v=a7e674ed:6
> > (anonymous) @ dep:sockjs-client:1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 它适合我添加`<script>global = globalThis</script>`index.html
> 
> 我也有同样的问题; 但是当我`<script>global = globalThis</script>`在 index.html 中添加时，出现了另一个问题`vue-router.esm-bundler.js:3248 TypeError: util.inherits is not a function at eventsource.js:315 at chunk-KHGO2BKN.js?v=76cbd4e4:4 at eventsource.js:5 at chunk-KHGO2BKN.js?v=76cbd4e4:4 at eventsource.js:5 at chunk-KHGO2BKN.js?v=76cbd4e4:4 at transport-list.js:8 at chunk-KHGO2BKN.js?v=76cbd4e4:4 at entry.js:3 at chunk-KHGO2BKN.js?v=76cbd4e4:4`
> 你见过吗？

直接index.html里  script标签引入使用，先这么用吧

**Comment by ZingerLittleBee** [comment]
any update?
i still has this problem in Vue3
it not works for me to add <script>global = globalThis</script>in index.html

**Comment by TranksJ** [comment]
> any update?
> i still has this problem in Vue3
> it not works for me to add <script>global = globalThis</script>in index.html



> 任何更新？
> 我在 Vue3 中仍然有这个问题，
> 在 index.html 中添加 <script>global = globalThis</script> 对我不起作用

Just introduce dependencies into the script tag

**Comment by ZingerLittleBee** [comment]
> > any update?
> > i still has this problem in Vue3
> > it not works for me to add <script>global = globalThis</script>in index.html
> 
> > 任何更新？
> > 我在 Vue3 中仍然有这个问题，
> > 在 index.html 中添加 <script>global = globalThis</script> 对我不起作用
> 
> Just introduce dependencies into the script tag

Thanks, introduce sockjs by cdn this is useful to me
~~however, lost TS support in this way~~

**Comment by hanz520** [comment]
import SockJs from 'sockjs-client/dist/sockjs.min.js'

**Comment by oyed** [comment]
The comment from @hanz520 works great, and if you use TypeScript, be sure to add this in a `.d.ts` file:

```
declare module 'sockjs-client/dist/sockjs.min.js' {
    import Client from 'sockjs-client';
    export default Client;
}
```

**Comment by diduweiwu** [comment]
> import SockJs from 'sockjs-client/dist/sockjs.min.js'

This works for me and no issue raised. Thanks a lot:)

**Comment by oliver225** [comment]
I have the same problem     
if (typeof (window as any).global === 'undefined') {
  (window as any).global = window;
}
but  new problem:
usePage.ts:13 
          TypeError: util.inherits is not a function
    at node_modules/eventsource/lib/eventsource.js (eventsource.js:315:6)
    at __require2 (chunk-6TNEX7YP.js?v=0376d2cc:36:44)
    at node_modules/sockjs-client/lib/transport/receiver/eventsource.js (eventsource.js:5:25)
    at __require2 (chunk-6TNEX7YP.js?v=0376d2cc:36:44)
    at node_modules/sockjs-client/lib/transport/eventsource.js (eventsource.js:5:27)
    at __require2 (chunk-6TNEX7YP.js?v=0376d2cc:36:44)
    at node_modules/sockjs-client/lib/transport-list.js (transport-list.js:8:3)
    at __require2 (chunk-6TNEX7YP.js?v=0376d2cc:36:44)
    at node_modules/sockjs-client/lib/entry.js (entry.js:3:21)
    at __require2 (chunk-6TNEX7YP.js?v=0376d2cc:36:44)
