### ISSUE TITLE
Request headers with xhr-polling

### ISSUE THREAD

**Issue by alindumitru25** [sockjs/sockjs-client#553]
We have an environment where we want to use xhr-polling by default without using websockets implementation. We set request headers on every POST request for authentication purposes, is it possible to somehow add request headers?

**Comment by brycekahle** [comment]
We don't support setting headers because not all transports support them.

**Comment by alindumitru25** [comment]
Thank you for the response @brycekahle . Would it be possible to modify the options hash to contain some kind of xhr.polling.headers that are only taken into consideration when xhr-polling is used?

There are certain network environments in which we can't rely on web sockets at all, they are too restrictive. Unfortunately we can't fallback to long-polling since every API POST request needs to specify a request header. The authentication system is too convoluted to be changed, it will take months since it used across many systems so our only option is to modify the library to support the request header.
