### ISSUE TITLE
Duplicate messages emitted after error in onmessage

### ISSUE THREAD

**Issue by jcheng5** [sockjs/sockjs-client#563]
Using xhr-streaming, xhr-polling, or jsonp-polling, if an error is raised in the socket.onmessage event handler, then the next time a message is received SockJS will replay the message that caused the error.

For example, message A is received and the client `onmessage` event handler throws an uncaught error; later, message B is received, and `onmessage` is called again with message A.

Repro repo: https://github.com/jcheng5/sockjs-error-test

The problem appears to be here:

https://github.com/sockjs/sockjs-client/blob/71876b30849299255f34131af6474d959d61cbb2/lib/transport/receiver/xhr.js#L40-L52

When `this.emit('message', msg);` throws an exception, `this.bufferPosition` doesn't get updated (third clause of the for-loop). If you update `this.bufferPosition` before emitting the message, the problem goes away.

**Comment by aronatkins** [comment]
This appears to be the 0.3.4 equivalent code, which updates the buffer position ahead of sending an event and does not suffer from duplicate messages after error:
https://github.com/sockjs/sockjs-client/blob/0c70698bddcfab826c7b241ed709f69b5b0d41f7/lib/trans-receiver-xhr.js#L14-L24

**Comment by aronatkins** [comment]
False no-activity. Discussion is in #564; waiting for feedback from @brycekahle.

**Comment by aronatkins** [comment]
Ping to keep open; #564 is still waiting for feedback from @brycekahle.
