### ISSUE TITLE
global is not defined in vue3

### ISSUE THREAD

**Issue by Xqrrrr** [sockjs/sockjs-client#565]

**Comment by Zhengqbbb** [comment]
yes,I also encountered the same painful thing😭

**Comment by Xqrrrr** [comment]
> yes,I also encountered the same painful thing😭

You can introduce "sockjs-client/dist/sockjs.nin.js" in this way

**Comment by Xqrrrr** [comment]
> yes,I also encountered the same painful thing😭

You can introduce "sockjs-client/dist/sockjs.min.js" in this way

**Comment by brycekahle** [comment]
How are you using the library? `browserify` handles this transparently when building the bundled version (which you should be using in a browser context).

**Comment by Xqrrrr** [comment]
> How are you using the library? `browserify` handles this transparently when building the bundled version (which you should be using in a browser context).

I use Vite to build vue3. You can take a look at this issues https://github.com/sockjs/sockjs-client/issues/547

**Comment by Zhengqbbb** [comment]
nice!

**Comment by Zhengqbbb** [comment]
nice!
I use vue3 + vite + ts.
it’s great work.
```ts
import SockJs from 'sockjs-client/dist/sockjs.min.js'
```

and u sure to add .d.ts in your workspace :
```ts
// socket.d.ts

declare module 'sockjs-client/dist/sockjs.min.js' {
  import Client from 'sockjs-client';
  export default Client;
}
```
