### ISSUE TITLE
Websockets failing to connect with Chrome Version 95.0.4638.54 (Official Build) (x86_64) on Mac

### ISSUE THREAD

**Issue by dceejay** [sockjs/sockjs-client#568]
Hi I've suddenly started to get Connection failed when trying to connect  - the console log reports

![image](https://user-images.githubusercontent.com/5375409/138301381-3914f4ed-c4f7-431b-848e-b34357ceb4b6.png)

Worst part is it also takes down the server side
```
21 Oct 15:41:09 - [red] Uncaught Exception:
21 Oct 15:41:09 - [error] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
```

This was working prior to latest Chrome upgrade - and if I force sockjs to use xhr transports it works OK... but hardly a desired fix.

Any clues what has been deprecated and how to fix ?

**Comment by dceejay** [comment]
Any feedback ?

**Comment by brycekahle** [comment]
That warning has nothing to do with SockJS and is probably coming from a plugin you have installed. https://bugs.chromium.org/p/chromium/issues/detail?id=1173575
