### ISSUE TITLE
Update url-parse due to security vulnerability

### ISSUE THREAD

**Issue by sandeepanaplan** [sockjs/sockjs-client#576]
There has been a new security vulnerablity found in url-parse version below 1.5.6. Please see [here](https://github.com/advisories/GHSA-rqff-837h-mm52) for more details

`Sockjs-client` is the using `1.5.3` version at the moment. 

Please update the `url-parse` library to version > `1.5.6` (latest)

**Comment by brycekahle** [comment]
`1.6.0` was just published
