### ISSUE TITLE
new release request due to deprecation of json3

### ISSUE THREAD

**Issue by eebrown** [sockjs/sockjs-client#577]
I was wondering if it would be possible to put out a new release, since the json3 dependency has been deprecated from npm (https://www.npmjs.com/package/json3). I understand that json3 has already been removed as a dependency (https://github.com/sockjs/sockjs-client/commit/d9584abe2c7c913ce95a1aea29e5744dd85e1af4).

This would be helpful because the Debian team is looking to update socksjs-client package in Debian, which currently doesn't build as node-json3 has been removed from Debian, and socksjs-client is needed for some current packaging work.

Thank you very much for considering.

**Comment by brycekahle** [comment]
@eebrown `1.6.0` was just published
