### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by VladislavLobakh** [sockjs/sockjs-client#581]
Hello everyone!

There's an issue with sockjs that already existed for years.

```
Error: Uncaught (in promise): ReferenceError: global is not defined
ReferenceError: global is not defined
```

It was opened before https://github.com/sockjs/sockjs-client/issues/439 but wasn't fixed.
I know the hotfix to add `(window as any).global = window;` into polyfills. 

But is it going to be fixed?

**Comment by brycekahle** [comment]
It isn't an issue, because if you use the pre-bundled files, it works fine. If you are bundling yourself, then you need to take care of it yourself.

**Comment by brycekahle** [comment]
Please don't open new issues for existing issues.
