### ISSUE TITLE
Unload event is blocking bfcache

### ISSUE THREAD

**Issue by kevinfarrugia** [sockjs/sockjs-client#584]
The `unload` event at https://github.com/sockjs/sockjs-client/blob/main/lib/utils/event.js#L72 is preventing back/forward cache from working. As a result, it negatively affects performance.

Is it possible to utilise the `visibilitychange` or `pagehide` events instead? Or perhaps have a legacy and modern build?

Read more: https://web.dev/bfcache/#never-use-the-unload-event

**Comment by kevinfarrugia** [comment]
Should I go ahead and create a PR please?

**Comment by kevinfarrugia** [comment]
Will prepare PR

**Comment by jimmywarting** [comment]
came here cuz lighthouse gave me a lower score.
