### ISSUE TITLE
version 1.6.1 can't work on ie

### ISSUE THREAD

**Issue by huangpiqiao** [sockjs/sockjs-client#605]
internet explorer?

**Comment by fengyuanchen** [comment]
A syntax error was thrown when using v1.6.1 in IE11, and it worked fine after downgrading to v1.6.0.

**Comment by Finesse** [comment]
+1

Version 1.6.1 has introduced a breaking change which is switching from ES5 to ES6 syntax in the distributive files. Such change must bump the major version.

**Comment by auvipy** [comment]
new maintainer here. I am not sure if the es 6 syntax is actually merged in new release?

**Comment by Finesse** [comment]
@auvipy It is in version 1.6.1. You can see it here: https://cdn.jsdelivr.net/npm/sockjs-client@1.6.1/dist/sockjs.js (`exports.destroy = (() => { ...`)

**Comment by auvipy** [comment]
ugh. then we have to do a major version release

**Comment by Finesse** [comment]
@auvipy Could you please release version 1.6.2 which reverts the syntax back to ES5? It’s necessary to keep the v1 compatibility.

**Comment by auvipy** [comment]
can you send a PR to revert that?

**Comment by Finesse** [comment]
@auvipy, I don't need it already, sorry. I'll drop IE support in my projects very soon.
