### ISSUE TITLE
SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'wss:' is not allowed.

### ISSUE THREAD

**Issue by akl7777777** [sockjs/sockjs-client#621]
SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'wss:' is not allowed.

I am requesting a certain wss, but this error is reported, is the URL starting with wss not supported?

**Comment by auvipy** [comment]
can you provide a failing test to verify?

**Comment by FZambia** [comment]
Duplicate of https://github.com/sockjs/sockjs-client/issues/452
