### ISSUE TITLE
SockJS Client in React doesn't subscribe to the 'initial/queue' and one other topic

### ISSUE THREAD

**Issue by marinavelvet** [sockjs/sockjs-client#630]
Hi, I can't get SockJS Client to subscribe to the 'initial/queue' and 'dashboard/livestream' topic. I only get 'topic/livestream', no matter what I do.
Here is my code snippet, and also a reminder that in the backend everything is configured fine, so the problem is somewhere either in this logic or in SockJs library. Please help!

import React from 'react';
import SockJsClient from 'react-stomp';

class TableDataStream extends React.Component {
constructor(props) {
super(props);
this.state = {
clientConnected: false,
messages: [],
data: [],
circulatingSupply: '',
figures: '',
initialDataReceived: false
};
}

componentDidMount() {
this.setState({ clientConnected: true });
}

componentWillUnmount() {
this.setState({ clientConnected: false });
}

sendMessage = () => {
if (this.clientRef && this.clientRef.state && this.clientRef.state.connected) {
console.log(this.clientRef);
console.log(this.clientRef.state);
console.log(this.clientRef.state.connected);
this.clientRef.sendMessage('/dashboard/livestream', {});
}
};

handleMessage = (event) => {
if (event.topic === '/queue/initial') {

  this.setState({ initialDataReceived: true }); 
}
this.props.handleEvents(event);

};

handleDisconnect = () => {
console.log('SockJSClient is disconnected');
};

render() {
const { initialDataReceived, clientConnected } = this.state;

return (
  <div>
    {clientConnected && (
      <SockJsClient
        url={window.ENVIRONMENT.REACT_APP_BACKEND_SERVICE_LOCATION + '/register'}
        topics={['/queue/initial', '/topic/livestream']}
        onMessage={(msg) => {
          this.handleMessage(msg);
        }}
        ref={(client) => {
          this.clientRef = client;
        }}
        onConnect={() => {
          this.sendMessage();
        }}
        onDisconnect={this.handleDisconnect}
        debug={true}
      />
    )}
  </div>
);

}
}

export default TableDataStream

**Comment by jdratnayake** [comment]
**Issue: Unable to Subscribe to Multiple Topics with SockJS Client**

**Solution:**

To resolve the problem of not being able to subscribe to 'initial/queue' and 'dashboard/livestream' topics with SockJS Client, make the following changes in the code:

1. In the sendMessage method, update the topic to '/queue/initial' for initial data subscription:
```
sendMessage = () => {
  if (this.clientRef && this.clientRef.state && this.clientRef.state.connected) {
    this.clientRef.sendMessage('/queue/initial', {}); // Change the topic to '/queue/initial'
  }
};
```
2. In the render method, ensure that you are subscribing to both topics:
```
render() {
  const { initialDataReceived, clientConnected } = this.state;

  return (
    <div>
      {clientConnected && (
        <SockJsClient
          url="your_websocket_url_here" // Replace with your actual WebSocket URL
          topics={['/queue/initial', '/dashboard/livestream']} // Subscribe to both topics here
          onMessage={(msg) => this.handleMessage(msg)}
          ref={(client) => { this.clientRef = client; }}
          onConnect={() => { this.sendMessage(); }}
          onDisconnect={this.handleDisconnect}
          debug={true}
        />
      )}
    </div>
  );
}
```

Remember to replace "your_websocket_url_here" with the correct WebSocket URL that connects to the backend server.

By implementing these changes, the SockJS Client should now successfully subscribe to both topics and receive messages accordingly.

If you encounter any further issues, feel free to ask for more assistance!

**Comment by marinavelvet** [comment]
Thank you for your answer. I've tried doing what you suggested and it still reads/shows only '/dahsboard/livestream'. Can it maybe really be the backend problem or is there some issue with the library?
I'm getting this message from console: id:sub-0

**Comment by marinavelvet** [comment]
This issue is solved by adding componentDidUpdate method, so now the code looks like this:

```
class TableDataStream extends React.Component {
      constructor(props) {
      super(props);
      this.state = {
      clientConnected: false,
      messages: [],
      data: [],
      circulatingSupply: '',
      figures: ''
      }
      }

      sendMessage = () => {
      if (this.clientRef && this.clientRef.state && this.clientRef.state.connected) {
      this.clientRef.sendMessage("/dashboard/livestream", {});
      }
      }

      componentDidMount = () => {
      this.setState({ clientConnected: true});
      }

      componentDidUpdate = () => {
      if (this.state.clientConnected === true && this.clientRef && this.clientRef.state && this.clientRef.state.connected) {
      this.clientRef.sendMessage("/dashboard/livestream", {});
      this.setState({ clientConnected: false});
      }
      }

      handleMessage = (event) => {
      this.props.handleEvents(event);
      }

      handleDisconnect = () => {
      console.log('SockJSClient is disconnected');
      }

        render() {
        return (
            <div>
            <SockJsClient 
                url={window.ENVIRONMENT.REACT_APP_BACKEND_SERVICE_LOCATION + "/register"} 
                topics={["/user/queue/initial", "/topic/livestream"]}
                onMessage={(msg) => { this.handleMessage(msg); }}
                ref={(client) => {this.clientRef = client;}}
                onConnect={() => {
                  this.setState({ clientConnected: true});
                  this.sendMessage();}}
                onDisconnect={this.handleDisconnect}
              debug={true}
              />
            </div>
            );
            }
            }

    export default TableDataStream;
```

**Comment by marinavelvet** [comment]
This issue is solved by adding componentDidUpdate method, so now the code looks like this:

```
class TableDataStream extends React.Component {
      constructor(props) {
      super(props);
      this.state = {
      clientConnected: false,
      messages: [],
      data: [],
      circulatingSupply: '',
      figures: ''
      }
      }

      sendMessage = () => {
      if (this.clientRef && this.clientRef.state && this.clientRef.state.connected) {
      this.clientRef.sendMessage("/dashboard/livestream", {});
      }
      }

      componentDidMount = () => {
      this.setState({ clientConnected: true});
      }

      componentDidUpdate = () => {
      if (this.state.clientConnected === true && this.clientRef && this.clientRef.state && this.clientRef.state.connected) {
      this.clientRef.sendMessage("/dashboard/livestream", {});
      this.setState({ clientConnected: false});
      }
      }

      handleMessage = (event) => {
      this.props.handleEvents(event);
      }

      handleDisconnect = () => {
      console.log('SockJSClient is disconnected');
      }

        render() {
        return (
            <div>
            <SockJsClient 
                url={window.ENVIRONMENT.REACT_APP_BACKEND_SERVICE_LOCATION + "/register"} 
                topics={["/user/queue/initial", "/topic/livestream"]}
                onMessage={(msg) => { this.handleMessage(msg); }}
                ref={(client) => {this.clientRef = client;}}
                onConnect={() => {
                  this.setState({ clientConnected: true});
                  this.sendMessage();}}
                onDisconnect={this.handleDisconnect}
              debug={true}
              />
            </div>
            );
            }
            }

    export default TableDataStream;
```
