### ISSUE TITLE
Optionally expect heartbeats from the server

### ISSUE THREAD

**Issue by majek** [sockjs/sockjs-client#67]
The server may send an option telling the client how often it will send 'heartbeat' frames.

We should read this option and, indeed, expect heartbeats. We should kill the session on a heartbeat miss.

**Comment by rikoe** [comment]
Hi. This issue has been open for almost 5 years now. It was recently discussed in #297. Is there any plan to implement this feature? The client not being aware of the server disappearing from the network seems to be a major flaw.

What is the "dev" branch mentioned above that has never been merged if one wants to take a look at it?

**Comment by harshakakumanu** [comment]
Are there any plans in implementing this issue? Is there any work around ?
