### ISSUE TITLE
Support query string on a sockjs url

### ISSUE THREAD

**Issue by majek** [sockjs/sockjs-client#72]
We should support query string on a sockjs url.

**Comment by cpandey05** [comment]
Is this feature available in latest SockJs client build -adding query string to sockjs URL?

**Comment by brycekahle** [comment]
Yes

**Comment by cpandey05** [comment]
Ohh.. this is great. Is it only for iframe or other transports as well like xdr, xhr etc. I referred the readme but could not find how to use it or pass it in the constructor - any reference which i can use for implementing this

**Comment by brycekahle** [comment]
It is for all transports. You add it as part of the url you pass in to the constructor. I will try and get that added to the docs. If you want to file an issue for the docs, that would be great.

**Comment by cpandey05** [comment]
I created an issue but was unable to apply a Label https://github.com/sockjs/sockjs-client/issues/248
