### ISSUE TITLE
Investigate if Opera 12 can do streaming ajax

### ISSUE THREAD

**Issue by majek** [sockjs/sockjs-client#92]
@Yaffle in #60 suggests that Opera 12 might be able to do XHR streamiing, but in a slightly different flavour than other browsers.

Also, we don't know if that works on single-domain.

the spec speaks about "onprogress" callback: http://www.w3.org/TR/XMLHttpRequest/

**Comment by Mouvedia** [comment]
> there is no bug, if the delay will be larger than ~35-50ms

here's why: https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#make-progress-notifications

**Comment by Mouvedia** [comment]
.
