### ISSUE TITLE
SockJS thinks connection is OPEN even though websocket handshake fails

### ISSUE THREAD

**Issue by cilia** [sockjs/sockjs-client#94]
In some (probably misconfigured) network, websocket handshake fails to complete with the server even on port 80. However, SockJS assumes the connection is OPEN, as 'onopen' event is fired.

This causes the client to believe that a websocket connection is established, but any msg sent between the client and the server will go missing. The client-server interaction simply hangs till timeout. In addition, it also prevents SockJS to switch to another (potentially working) transport, because websocket is already in use.

**Comment by scrapmac** [comment]
I have a related but not all together similar issue. My web socket connection is established successfully including a correct handshake and ```o``` message. The problem I am facing is that at times, the box which hosts the sock js server runs out of connections, i.e. max connection possible are reached. In this case, even the connected websocket connection is dropped. This may happen after some of the data has been transferred or even before that.

So my question is - is there anyway to handle a sudden drop in connection and reestablish it using a different mechanism for seamless data communication ?

**Comment by justQing00** [comment]
You can rewrite  these code
`
const socket = new SockJS('/api/ws/msg')
const oldtransportClose = socket.__proto__._transportClose
socket.__proto__._transportClose  = function(code, reason) {
  //  To do 
  // ...
  return oldtransportClose.call(this, code, reason);
}
`

, this can listen handshake fails.
