### ISSUE TITLE
Expose `bufferedAmount`

### ISSUE THREAD

**Issue by Raynos** [sockjs/sockjs-client#95]
[`bufferedAmount`](http://www.whatwg.org/specs/web-apps/current-work/multipage/network.html#dom-websocket-bufferedamount) exposes how much of the data is being buffered right now.

If you want to implement some kind of backpressure mechanism with say high and low watermarks you would need to check `bufferedAmount` > high mark and apply back pressure then emit some kind of `"drain"` event when `bufferedAmount` < low mark.

To do this sockJS needs to expose this information.

**Comment by dmnsgn** [comment]
Is there an equivalent concept to `bufferedAmount` for xhr?

**Comment by brycekahle** [comment]
Not that I'm aware of.
